// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package reliabilitydb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type WorkosReliabilityIncidentAction struct {
	IncidentID       string      `json:"incident_id"`
	Action           string      `json:"action"`
	ActionKey        string      `json:"action_key"`
	Outcome          string      `json:"outcome"`
	ResultGeneration pgtype.Int8 `json:"result_generation"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type WorkosReliabilitySupervisorCheckpoint struct {
	ID         string    `json:"id"`
	LastPollAt time.Time `json:"last_poll_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type WorkosReliabilitySupervisorWorkload struct {
	WorkloadID       string    `json:"workload_id"`
	Generation       int64     `json:"generation"`
	LastState        string    `json:"last_state"`
	LastHealth       string    `json:"last_health"`
	LastExit         string    `json:"last_exit"`
	LastRestartCount int32     `json:"last_restart_count"`
	StablePolls      int32     `json:"stable_polls"`
	ExitOccurrence   int32     `json:"exit_occurrence"`
	HealthOccurrence int32     `json:"health_occurrence"`
	OomOccurrence    int32     `json:"oom_occurrence"`
	PidsOccurrence   int32     `json:"pids_occurrence"`
	FirstSeenAt      time.Time `json:"first_seen_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
