// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package reliabilitydb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeIncident = `-- name: AcknowledgeIncident :execrows
UPDATE workos_reliability.incidents SET
    acknowledged_at = $1,
    acknowledge_key = $2,
    revision = revision + 1,
    updated_at = $3
WHERE id = $4
  AND owner_user_id = $5
  AND acknowledged_at IS NULL
`

type AcknowledgeIncidentParams struct {
	AcknowledgedAt *time.Time  `json:"acknowledged_at"`
	AcknowledgeKey pgtype.Text `json:"acknowledge_key"`
	UpdatedAt      time.Time   `json:"updated_at"`
	ID             string      `json:"id"`
	OwnerUserID    string      `json:"owner_user_id"`
}

// The owner acknowledgement is a separate fact from mitigation and never
// claims the fault is repaired; the idempotency key is persisted so the same
// key replays the same state and the (owner, key) uniqueness is enforced by
// the partial unique index from 017. Repeat acknowledges are no-ops.
func (q *Queries) AcknowledgeIncident(ctx context.Context, arg AcknowledgeIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, acknowledgeIncident,
		arg.AcknowledgedAt,
		arg.AcknowledgeKey,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIncident = `-- name: GetIncident :one
SELECT id, owner_user_id, project_id, app_instance_id, app_id, workload_id,
       workload_generation, violation, severity, summary, occurrence_digest,
       evidence_digest, state, restart_outcome, revision, acknowledge_key,
       acknowledged_at, mitigated_at, resolved_at, created_at, updated_at
FROM workos_reliability.incidents
WHERE id = $1
`

type GetIncidentRow struct {
	ID                 string      `json:"id"`
	OwnerUserID        string      `json:"owner_user_id"`
	ProjectID          string      `json:"project_id"`
	AppInstanceID      string      `json:"app_instance_id"`
	AppID              string      `json:"app_id"`
	WorkloadID         string      `json:"workload_id"`
	WorkloadGeneration int64       `json:"workload_generation"`
	Violation          string      `json:"violation"`
	Severity           string      `json:"severity"`
	Summary            string      `json:"summary"`
	OccurrenceDigest   string      `json:"occurrence_digest"`
	EvidenceDigest     string      `json:"evidence_digest"`
	State              string      `json:"state"`
	RestartOutcome     string      `json:"restart_outcome"`
	Revision           int64       `json:"revision"`
	AcknowledgeKey     pgtype.Text `json:"acknowledge_key"`
	AcknowledgedAt     *time.Time  `json:"acknowledged_at"`
	MitigatedAt        *time.Time  `json:"mitigated_at"`
	ResolvedAt         *time.Time  `json:"resolved_at"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

func (q *Queries) GetIncident(ctx context.Context, id string) (GetIncidentRow, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i GetIncidentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.AppInstanceID,
		&i.AppID,
		&i.WorkloadID,
		&i.WorkloadGeneration,
		&i.Violation,
		&i.Severity,
		&i.Summary,
		&i.OccurrenceDigest,
		&i.EvidenceDigest,
		&i.State,
		&i.RestartOutcome,
		&i.Revision,
		&i.AcknowledgeKey,
		&i.AcknowledgedAt,
		&i.MitigatedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentAction = `-- name: GetIncidentAction :one
SELECT incident_id, action, action_key, outcome, result_generation, created_at, updated_at
FROM workos_reliability.incident_actions
WHERE incident_id = $1 AND action = $2
`

type GetIncidentActionParams struct {
	IncidentID string `json:"incident_id"`
	Action     string `json:"action"`
}

func (q *Queries) GetIncidentAction(ctx context.Context, arg GetIncidentActionParams) (WorkosReliabilityIncidentAction, error) {
	row := q.db.QueryRow(ctx, getIncidentAction, arg.IncidentID, arg.Action)
	var i WorkosReliabilityIncidentAction
	err := row.Scan(
		&i.IncidentID,
		&i.Action,
		&i.ActionKey,
		&i.Outcome,
		&i.ResultGeneration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentByOccurrence = `-- name: GetIncidentByOccurrence :one
SELECT id, owner_user_id, project_id, app_instance_id, app_id, workload_id,
       workload_generation, violation, severity, summary, occurrence_digest,
       evidence_digest, state, restart_outcome, revision, acknowledge_key,
       acknowledged_at, mitigated_at, resolved_at, created_at, updated_at
FROM workos_reliability.incidents
WHERE occurrence_digest = $1
`

type GetIncidentByOccurrenceRow struct {
	ID                 string      `json:"id"`
	OwnerUserID        string      `json:"owner_user_id"`
	ProjectID          string      `json:"project_id"`
	AppInstanceID      string      `json:"app_instance_id"`
	AppID              string      `json:"app_id"`
	WorkloadID         string      `json:"workload_id"`
	WorkloadGeneration int64       `json:"workload_generation"`
	Violation          string      `json:"violation"`
	Severity           string      `json:"severity"`
	Summary            string      `json:"summary"`
	OccurrenceDigest   string      `json:"occurrence_digest"`
	EvidenceDigest     string      `json:"evidence_digest"`
	State              string      `json:"state"`
	RestartOutcome     string      `json:"restart_outcome"`
	Revision           int64       `json:"revision"`
	AcknowledgeKey     pgtype.Text `json:"acknowledge_key"`
	AcknowledgedAt     *time.Time  `json:"acknowledged_at"`
	MitigatedAt        *time.Time  `json:"mitigated_at"`
	ResolvedAt         *time.Time  `json:"resolved_at"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

func (q *Queries) GetIncidentByOccurrence(ctx context.Context, occurrenceDigest string) (GetIncidentByOccurrenceRow, error) {
	row := q.db.QueryRow(ctx, getIncidentByOccurrence, occurrenceDigest)
	var i GetIncidentByOccurrenceRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.AppInstanceID,
		&i.AppID,
		&i.WorkloadID,
		&i.WorkloadGeneration,
		&i.Violation,
		&i.Severity,
		&i.Summary,
		&i.OccurrenceDigest,
		&i.EvidenceDigest,
		&i.State,
		&i.RestartOutcome,
		&i.Revision,
		&i.AcknowledgeKey,
		&i.AcknowledgedAt,
		&i.MitigatedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupervisorCheckpoint = `-- name: GetSupervisorCheckpoint :one
SELECT id, last_poll_at, updated_at
FROM workos_reliability.supervisor_checkpoints
WHERE id = 'supervisor'
`

func (q *Queries) GetSupervisorCheckpoint(ctx context.Context) (WorkosReliabilitySupervisorCheckpoint, error) {
	row := q.db.QueryRow(ctx, getSupervisorCheckpoint)
	var i WorkosReliabilitySupervisorCheckpoint
	err := row.Scan(&i.ID, &i.LastPollAt, &i.UpdatedAt)
	return i, err
}

const incidentAcknowledgeKeyExists = `-- name: IncidentAcknowledgeKeyExists :one
SELECT EXISTS (
    SELECT 1 FROM workos_reliability.incidents
    WHERE owner_user_id = $1
      AND acknowledge_key = $2
      AND id <> $3
) AS exists_on_other
`

type IncidentAcknowledgeKeyExistsParams struct {
	OwnerUserID    string      `json:"owner_user_id"`
	AcknowledgeKey pgtype.Text `json:"acknowledge_key"`
	ID             string      `json:"id"`
}

func (q *Queries) IncidentAcknowledgeKeyExists(ctx context.Context, arg IncidentAcknowledgeKeyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, incidentAcknowledgeKeyExists, arg.OwnerUserID, arg.AcknowledgeKey, arg.ID)
	var exists_on_other bool
	err := row.Scan(&exists_on_other)
	return exists_on_other, err
}

const insertIncident = `-- name: InsertIncident :execrows

INSERT INTO workos_reliability.incidents (
    id, owner_user_id, project_id, app_instance_id, app_id, workload_id,
    workload_generation, violation, severity, summary, occurrence_digest,
    evidence_digest, state, restart_outcome, revision, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17
)
ON CONFLICT (occurrence_digest) DO NOTHING
`

type InsertIncidentParams struct {
	ID                 string    `json:"id"`
	OwnerUserID        string    `json:"owner_user_id"`
	ProjectID          string    `json:"project_id"`
	AppInstanceID      string    `json:"app_instance_id"`
	AppID              string    `json:"app_id"`
	WorkloadID         string    `json:"workload_id"`
	WorkloadGeneration int64     `json:"workload_generation"`
	Violation          string    `json:"violation"`
	Severity           string    `json:"severity"`
	Summary            string    `json:"summary"`
	OccurrenceDigest   string    `json:"occurrence_digest"`
	EvidenceDigest     string    `json:"evidence_digest"`
	State              string    `json:"state"`
	RestartOutcome     string    `json:"restart_outcome"`
	Revision           int64     `json:"revision"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

// Reliability Incident persistence queries (reliability-host owned tables
// only; the runtime schema is never queried).
// The occurrence_digest unique key is the at-least-once arbiter: a replayed
// episode inserts nothing and the caller reads the stored row instead.
func (q *Queries) InsertIncident(ctx context.Context, arg InsertIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIncident,
		arg.ID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.AppInstanceID,
		arg.AppID,
		arg.WorkloadID,
		arg.WorkloadGeneration,
		arg.Violation,
		arg.Severity,
		arg.Summary,
		arg.OccurrenceDigest,
		arg.EvidenceDigest,
		arg.State,
		arg.RestartOutcome,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listIncidentsPage = `-- name: ListIncidentsPage :many
SELECT i.id, i.owner_user_id, i.project_id, i.app_instance_id, i.app_id, i.workload_id,
       i.workload_generation, i.violation, i.severity, i.summary, i.occurrence_digest,
       i.evidence_digest, i.state, i.restart_outcome, i.revision, i.acknowledge_key,
       i.acknowledged_at, i.mitigated_at, i.resolved_at, i.created_at, i.updated_at
FROM workos_reliability.incidents i
WHERE i.owner_user_id = $1
  AND ($2::text = '' OR i.project_id = $2::uuid)
  AND (
    $3::text = ''
    OR (i.created_at, i.id) > (
      SELECT p.created_at, p.id FROM workos_reliability.incidents p
      WHERE p.id = $3::uuid
    )
  )
ORDER BY i.created_at, i.id
LIMIT $4
`

type ListIncidentsPageParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ProjectID   string `json:"project_id"`
	PageToken   string `json:"page_token"`
	RowLimit    int32  `json:"row_limit"`
}

type ListIncidentsPageRow struct {
	ID                 string      `json:"id"`
	OwnerUserID        string      `json:"owner_user_id"`
	ProjectID          string      `json:"project_id"`
	AppInstanceID      string      `json:"app_instance_id"`
	AppID              string      `json:"app_id"`
	WorkloadID         string      `json:"workload_id"`
	WorkloadGeneration int64       `json:"workload_generation"`
	Violation          string      `json:"violation"`
	Severity           string      `json:"severity"`
	Summary            string      `json:"summary"`
	OccurrenceDigest   string      `json:"occurrence_digest"`
	EvidenceDigest     string      `json:"evidence_digest"`
	State              string      `json:"state"`
	RestartOutcome     string      `json:"restart_outcome"`
	Revision           int64       `json:"revision"`
	AcknowledgeKey     pgtype.Text `json:"acknowledge_key"`
	AcknowledgedAt     *time.Time  `json:"acknowledged_at"`
	MitigatedAt        *time.Time  `json:"mitigated_at"`
	ResolvedAt         *time.Time  `json:"resolved_at"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

// Owner-scoped, project-optional, keyed pagination on (created_at, id). The
// caller probes limit+1 rows so a full final page never phantom-pages.
func (q *Queries) ListIncidentsPage(ctx context.Context, arg ListIncidentsPageParams) ([]ListIncidentsPageRow, error) {
	rows, err := q.db.Query(ctx, listIncidentsPage,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.PageToken,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentsPageRow
	for rows.Next() {
		var i ListIncidentsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.ProjectID,
			&i.AppInstanceID,
			&i.AppID,
			&i.WorkloadID,
			&i.WorkloadGeneration,
			&i.Violation,
			&i.Severity,
			&i.Summary,
			&i.OccurrenceDigest,
			&i.EvidenceDigest,
			&i.State,
			&i.RestartOutcome,
			&i.Revision,
			&i.AcknowledgeKey,
			&i.AcknowledgedAt,
			&i.MitigatedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIncidentsForWorkload = `-- name: ListOpenIncidentsForWorkload :many
SELECT id, owner_user_id, project_id, app_instance_id, app_id, workload_id,
       workload_generation, violation, severity, summary, occurrence_digest,
       evidence_digest, state, restart_outcome, revision, acknowledge_key,
       acknowledged_at, mitigated_at, resolved_at, created_at, updated_at
FROM workos_reliability.incidents
WHERE workload_id = $1
  AND workload_generation = $2
  AND state IN ('open', 'mitigated')
ORDER BY created_at, id
`

type ListOpenIncidentsForWorkloadParams struct {
	WorkloadID         string `json:"workload_id"`
	WorkloadGeneration int64  `json:"workload_generation"`
}

type ListOpenIncidentsForWorkloadRow struct {
	ID                 string      `json:"id"`
	OwnerUserID        string      `json:"owner_user_id"`
	ProjectID          string      `json:"project_id"`
	AppInstanceID      string      `json:"app_instance_id"`
	AppID              string      `json:"app_id"`
	WorkloadID         string      `json:"workload_id"`
	WorkloadGeneration int64       `json:"workload_generation"`
	Violation          string      `json:"violation"`
	Severity           string      `json:"severity"`
	Summary            string      `json:"summary"`
	OccurrenceDigest   string      `json:"occurrence_digest"`
	EvidenceDigest     string      `json:"evidence_digest"`
	State              string      `json:"state"`
	RestartOutcome     string      `json:"restart_outcome"`
	Revision           int64       `json:"revision"`
	AcknowledgeKey     pgtype.Text `json:"acknowledge_key"`
	AcknowledgedAt     *time.Time  `json:"acknowledged_at"`
	MitigatedAt        *time.Time  `json:"mitigated_at"`
	ResolvedAt         *time.Time  `json:"resolved_at"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

func (q *Queries) ListOpenIncidentsForWorkload(ctx context.Context, arg ListOpenIncidentsForWorkloadParams) ([]ListOpenIncidentsForWorkloadRow, error) {
	rows, err := q.db.Query(ctx, listOpenIncidentsForWorkload, arg.WorkloadID, arg.WorkloadGeneration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenIncidentsForWorkloadRow
	for rows.Next() {
		var i ListOpenIncidentsForWorkloadRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.ProjectID,
			&i.AppInstanceID,
			&i.AppID,
			&i.WorkloadID,
			&i.WorkloadGeneration,
			&i.Violation,
			&i.Severity,
			&i.Summary,
			&i.OccurrenceDigest,
			&i.EvidenceDigest,
			&i.State,
			&i.RestartOutcome,
			&i.Revision,
			&i.AcknowledgeKey,
			&i.AcknowledgedAt,
			&i.MitigatedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadSupervisorProgress = `-- name: LoadSupervisorProgress :one
SELECT workload_id, generation, last_state, last_health, last_exit,
       last_restart_count, stable_polls, exit_occurrence, health_occurrence,
       oom_occurrence, pids_occurrence, first_seen_at, updated_at
FROM workos_reliability.supervisor_workloads
WHERE workload_id = $1
`

func (q *Queries) LoadSupervisorProgress(ctx context.Context, workloadID string) (WorkosReliabilitySupervisorWorkload, error) {
	row := q.db.QueryRow(ctx, loadSupervisorProgress, workloadID)
	var i WorkosReliabilitySupervisorWorkload
	err := row.Scan(
		&i.WorkloadID,
		&i.Generation,
		&i.LastState,
		&i.LastHealth,
		&i.LastExit,
		&i.LastRestartCount,
		&i.StablePolls,
		&i.ExitOccurrence,
		&i.HealthOccurrence,
		&i.OomOccurrence,
		&i.PidsOccurrence,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markIncidentResolved = `-- name: MarkIncidentResolved :execrows
UPDATE workos_reliability.incidents SET
    state = 'resolved',
    resolved_at = $1,
    revision = revision + 1,
    updated_at = $2
WHERE id = $3 AND state IN ('open', 'mitigated')
`

type MarkIncidentResolvedParams struct {
	ResolvedAt *time.Time `json:"resolved_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	ID         string     `json:"id"`
}

func (q *Queries) MarkIncidentResolved(ctx context.Context, arg MarkIncidentResolvedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markIncidentResolved, arg.ResolvedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIncidentOutcome = `-- name: UpdateIncidentOutcome :execrows
UPDATE workos_reliability.incidents SET
    state = $1,
    restart_outcome = $2,
    mitigated_at = $3,
    revision = revision + 1,
    updated_at = $4
WHERE id = $5 AND state = 'open'
`

type UpdateIncidentOutcomeParams struct {
	State          string     `json:"state"`
	RestartOutcome string     `json:"restart_outcome"`
	MitigatedAt    *time.Time `json:"mitigated_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	ID             string     `json:"id"`
}

func (q *Queries) UpdateIncidentOutcome(ctx context.Context, arg UpdateIncidentOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateIncidentOutcome,
		arg.State,
		arg.RestartOutcome,
		arg.MitigatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertIncidentAction = `-- name: UpsertIncidentAction :exec
INSERT INTO workos_reliability.incident_actions (
    incident_id, action, action_key, outcome, result_generation,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (incident_id, action) DO UPDATE
SET outcome = $4,
    result_generation = $5,
    updated_at = $7
`

type UpsertIncidentActionParams struct {
	IncidentID       string      `json:"incident_id"`
	Action           string      `json:"action"`
	ActionKey        string      `json:"action_key"`
	Outcome          string      `json:"outcome"`
	ResultGeneration pgtype.Int8 `json:"result_generation"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

func (q *Queries) UpsertIncidentAction(ctx context.Context, arg UpsertIncidentActionParams) error {
	_, err := q.db.Exec(ctx, upsertIncidentAction,
		arg.IncidentID,
		arg.Action,
		arg.ActionKey,
		arg.Outcome,
		arg.ResultGeneration,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertSupervisorCheckpoint = `-- name: UpsertSupervisorCheckpoint :exec
INSERT INTO workos_reliability.supervisor_checkpoints (id, last_poll_at, updated_at)
VALUES ('supervisor', $1, $2)
ON CONFLICT (id) DO UPDATE
SET last_poll_at = $1,
    updated_at = $2
`

type UpsertSupervisorCheckpointParams struct {
	LastPollAt time.Time `json:"last_poll_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) UpsertSupervisorCheckpoint(ctx context.Context, arg UpsertSupervisorCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertSupervisorCheckpoint, arg.LastPollAt, arg.UpdatedAt)
	return err
}

const upsertSupervisorProgress = `-- name: UpsertSupervisorProgress :exec
INSERT INTO workos_reliability.supervisor_workloads (
    workload_id, generation, last_state, last_health, last_exit,
    last_restart_count, stable_polls, exit_occurrence, health_occurrence,
    oom_occurrence, pids_occurrence, first_seen_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13
)
ON CONFLICT (workload_id) DO UPDATE
SET generation = $2,
    last_state = $3,
    last_health = $4,
    last_exit = $5,
    last_restart_count = $6,
    stable_polls = $7,
    exit_occurrence = $8,
    health_occurrence = $9,
    oom_occurrence = $10,
    pids_occurrence = $11,
    updated_at = $13
`

type UpsertSupervisorProgressParams struct {
	WorkloadID       string    `json:"workload_id"`
	Generation       int64     `json:"generation"`
	LastState        string    `json:"last_state"`
	LastHealth       string    `json:"last_health"`
	LastExit         string    `json:"last_exit"`
	LastRestartCount int32     `json:"last_restart_count"`
	StablePolls      int32     `json:"stable_polls"`
	ExitOccurrence   int32     `json:"exit_occurrence"`
	HealthOccurrence int32     `json:"health_occurrence"`
	OomOccurrence    int32     `json:"oom_occurrence"`
	PidsOccurrence   int32     `json:"pids_occurrence"`
	FirstSeenAt      time.Time `json:"first_seen_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

func (q *Queries) UpsertSupervisorProgress(ctx context.Context, arg UpsertSupervisorProgressParams) error {
	_, err := q.db.Exec(ctx, upsertSupervisorProgress,
		arg.WorkloadID,
		arg.Generation,
		arg.LastState,
		arg.LastHealth,
		arg.LastExit,
		arg.LastRestartCount,
		arg.StablePolls,
		arg.ExitOccurrence,
		arg.HealthOccurrence,
		arg.OomOccurrence,
		arg.PidsOccurrence,
		arg.FirstSeenAt,
		arg.UpdatedAt,
	)
	return err
}
