// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package reliabilitydb

import (
	"context"
)

type Querier interface {
	// The owner acknowledgement is a separate fact from mitigation and never
	// claims the fault is repaired; repeat acknowledges are no-ops.
	AcknowledgeIncident(ctx context.Context, arg AcknowledgeIncidentParams) (int64, error)
	GetIncident(ctx context.Context, id string) (WorkosReliabilityIncident, error)
	GetIncidentAction(ctx context.Context, arg GetIncidentActionParams) (WorkosReliabilityIncidentAction, error)
	GetSupervisorCheckpoint(ctx context.Context) (WorkosReliabilitySupervisorCheckpoint, error)
	// Reliability Incident persistence queries (reliability-host owned tables
	// only; the runtime schema is never queried).
	// The occurrence_digest unique key is the at-least-once arbiter: a replayed
	// episode inserts nothing and the caller reads the stored row instead.
	InsertIncident(ctx context.Context, arg InsertIncidentParams) (int64, error)
	// Owner-scoped, project-optional, keyed pagination on (created_at, id). The
	// caller probes limit+1 rows so a full final page never phantom-pages.
	ListIncidentsPage(ctx context.Context, arg ListIncidentsPageParams) ([]WorkosReliabilityIncident, error)
	ListOpenIncidentsForWorkload(ctx context.Context, arg ListOpenIncidentsForWorkloadParams) ([]WorkosReliabilityIncident, error)
	LoadSupervisorProgress(ctx context.Context, workloadID string) (WorkosReliabilitySupervisorWorkload, error)
	MarkIncidentResolved(ctx context.Context, arg MarkIncidentResolvedParams) (int64, error)
	UpdateIncidentOutcome(ctx context.Context, arg UpdateIncidentOutcomeParams) (int64, error)
	UpsertIncidentAction(ctx context.Context, arg UpsertIncidentActionParams) error
	UpsertSupervisorCheckpoint(ctx context.Context, arg UpsertSupervisorCheckpointParams) error
	UpsertSupervisorProgress(ctx context.Context, arg UpsertSupervisorProgressParams) error
}

var _ Querier = (*Queries)(nil)
