// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package appdb

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type WorkosCoreAppVersion struct {
	ID                string             `json:"id"`
	OwnerUserID       string             `json:"owner_user_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	RequestDigest     string             `json:"request_digest"`
	AppID             string             `json:"app_id"`
	Version           string             `json:"version"`
	Scope             string             `json:"scope"`
	Name              string             `json:"name"`
	Permissions       []string           `json:"permissions"`
	ManifestDigest    string             `json:"manifest_digest"`
	CanonicalManifest json.RawMessage    `json:"canonical_manifest"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
