// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package appdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WorkosCoreAppRegistrationRequest struct {
	OwnerUserID    string             `json:"owner_user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestDigest  string             `json:"request_digest"`
	AppVersionID   string             `json:"app_version_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WorkosCoreAppRepairCandidateVersion struct {
	TaskID         string             `json:"task_id"`
	OwnerUserID    string             `json:"owner_user_id"`
	ProjectID      string             `json:"project_id"`
	InstallationID string             `json:"installation_id"`
	IncidentID     string             `json:"incident_id"`
	BuildJobID     string             `json:"build_job_id"`
	SourceDigest   string             `json:"source_digest"`
	AppVersionID   string             `json:"app_version_id"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
