// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package appdb

import (
	"context"
)

type Querier interface {
	GetAppVersion(ctx context.Context, arg GetAppVersionParams) (WorkosCoreAppVersion, error)
	GetAppVersionByIdempotency(ctx context.Context, arg GetAppVersionByIdempotencyParams) (WorkosCoreAppVersion, error)
	GetAppVersions(ctx context.Context, arg GetAppVersionsParams) ([]WorkosCoreAppVersion, error)
	InsertAppVersion(ctx context.Context, arg InsertAppVersionParams) (int64, error)
	ListAppIDs(ctx context.Context, arg ListAppIDsParams) ([]string, error)
	ListAppVersionsForApps(ctx context.Context, arg ListAppVersionsForAppsParams) ([]WorkosCoreAppVersion, error)
}

var _ Querier = (*Queries)(nil)
