// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package previewdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WorkosRuntimeWorkspacePreview struct {
	PreviewID         string             `json:"preview_id"`
	OwnerUserID       string             `json:"owner_user_id"`
	ProjectID         string             `json:"project_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	WorkspaceSourceID string             `json:"workspace_source_id"`
	ReadOnly          bool               `json:"read_only"`
	State             string             `json:"state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Command           string             `json:"command"`
	Port              int32              `json:"port"`
	Generation        int64              `json:"generation"`
	AccessToken       string             `json:"access_token"`
	RequestDigest     string             `json:"request_digest"`
	BindingID         string             `json:"binding_id"`
	BindingRevision   int64              `json:"binding_revision"`
	LifecycleMode     int16              `json:"lifecycle_mode"`
}
