// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package previewdb

import (
	"context"
)

type Querier interface {
	ActivateWorkspacePreview(ctx context.Context, arg ActivateWorkspacePreviewParams) (int64, error)
	GetPreviewByOwnerKey(ctx context.Context, arg GetPreviewByOwnerKeyParams) (WorkosRuntimeWorkspacePreview, error)
	GetWorkspacePreview(ctx context.Context, previewID string) (WorkosRuntimeWorkspacePreview, error)
	GetWorkspacePreviewAction(ctx context.Context, arg GetWorkspacePreviewActionParams) (GetWorkspacePreviewActionRow, error)
	InsertWorkspacePreview(ctx context.Context, arg InsertWorkspacePreviewParams) (int64, error)
	ListActiveWorkspacePreviews(ctx context.Context) ([]WorkosRuntimeWorkspacePreview, error)
	ListProjectWorkspacePreviews(ctx context.Context, arg ListProjectWorkspacePreviewsParams) ([]WorkosRuntimeWorkspacePreview, error)
	LockWorkspacePreview(ctx context.Context, arg LockWorkspacePreviewParams) (WorkosRuntimeWorkspacePreview, error)
	RecordWorkspacePreviewAction(ctx context.Context, arg RecordWorkspacePreviewActionParams) error
	RestartWorkspacePreview(ctx context.Context, arg RestartWorkspacePreviewParams) (WorkosRuntimeWorkspacePreview, error)
	UpdateWorkspacePreviewState(ctx context.Context, arg UpdateWorkspacePreviewStateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
