// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package artifactdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WorkosCoreProjectReviewArtifact struct {
	ID           string             `json:"id"`
	OwnerUserID  string             `json:"owner_user_id"`
	Type         string             `json:"type"`
	Title        string             `json:"title"`
	MediaType    string             `json:"media_type"`
	Digest       string             `json:"digest"`
	ProjectID    string             `json:"project_id"`
	SourceTaskID string             `json:"source_task_id"`
	OutputKey    string             `json:"output_key"`
	ByteCount    int32              `json:"byte_count"`
	LineCount    int32              `json:"line_count"`
	Content      []byte             `json:"content"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type WorkosCoreProjectReviewArtifactOutput struct {
	TaskID          string             `json:"task_id"`
	OutputKey       string             `json:"output_key"`
	ArtifactType    string             `json:"artifact_type"`
	RequestDigest   string             `json:"request_digest"`
	OwnerUserID     string             `json:"owner_user_id"`
	ProjectID       string             `json:"project_id"`
	ArtifactID      string             `json:"artifact_id"`
	EventID         string             `json:"event_id"`
	EventSequence   int64              `json:"event_sequence"`
	EventOccurredAt pgtype.Timestamptz `json:"event_occurred_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type WorkosCoreWebBundleArtifact struct {
	ID             string             `json:"id"`
	OwnerUserID    string             `json:"owner_user_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	MediaType      string             `json:"media_type"`
	ContentRef     string             `json:"content_ref"`
	Digest         string             `json:"digest"`
	Entrypoint     string             `json:"entrypoint"`
	FileCount      int32              `json:"file_count"`
	TotalSizeBytes int64              `json:"total_size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WorkosCoreWebBundleArtifactRequest struct {
	OwnerUserID    string             `json:"owner_user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestDigest  string             `json:"request_digest"`
	ArtifactID     string             `json:"artifact_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
