// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package artifactdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArtifact = `-- name: GetArtifact :one
SELECT id, owner_user_id, type, title, media_type, content_ref, digest,
       entrypoint, file_count, total_size_bytes, created_at
FROM workos_core.web_bundle_artifacts
WHERE owner_user_id = $1 AND id = $2
`

type GetArtifactParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (WorkosCoreWebBundleArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.OwnerUserID, arg.ID)
	var i WorkosCoreWebBundleArtifact
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Type,
		&i.Title,
		&i.MediaType,
		&i.ContentRef,
		&i.Digest,
		&i.Entrypoint,
		&i.FileCount,
		&i.TotalSizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactRequest = `-- name: GetArtifactRequest :one
SELECT owner_user_id, idempotency_key, request_digest, artifact_id, created_at
FROM workos_core.web_bundle_artifact_requests
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetArtifactRequestParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetArtifactRequest(ctx context.Context, arg GetArtifactRequestParams) (WorkosCoreWebBundleArtifactRequest, error) {
	row := q.db.QueryRow(ctx, getArtifactRequest, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosCoreWebBundleArtifactRequest
	err := row.Scan(
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.ArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :exec
INSERT INTO workos_core.web_bundle_artifacts (
    id, owner_user_id, type, title, media_type, content_ref, digest,
    entrypoint, file_count, total_size_bytes, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertArtifactParams struct {
	ID             string             `json:"id"`
	OwnerUserID    string             `json:"owner_user_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	MediaType      string             `json:"media_type"`
	ContentRef     string             `json:"content_ref"`
	Digest         string             `json:"digest"`
	Entrypoint     string             `json:"entrypoint"`
	FileCount      int32              `json:"file_count"`
	TotalSizeBytes int64              `json:"total_size_bytes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) error {
	_, err := q.db.Exec(ctx, insertArtifact,
		arg.ID,
		arg.OwnerUserID,
		arg.Type,
		arg.Title,
		arg.MediaType,
		arg.ContentRef,
		arg.Digest,
		arg.Entrypoint,
		arg.FileCount,
		arg.TotalSizeBytes,
		arg.CreatedAt,
	)
	return err
}

const insertArtifactRequest = `-- name: InsertArtifactRequest :execrows
INSERT INTO workos_core.web_bundle_artifact_requests (
    owner_user_id, idempotency_key, request_digest, artifact_id, created_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertArtifactRequestParams struct {
	OwnerUserID    string             `json:"owner_user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestDigest  string             `json:"request_digest"`
	ArtifactID     string             `json:"artifact_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertArtifactRequest(ctx context.Context, arg InsertArtifactRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertArtifactRequest,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.ArtifactID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertBundleFile = `-- name: InsertBundleFile :exec
INSERT INTO workos_core.web_bundle_files (
    artifact_id, path, media_type, size_bytes, digest, content
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBundleFileParams struct {
	ArtifactID string `json:"artifact_id"`
	Path       string `json:"path"`
	MediaType  string `json:"media_type"`
	SizeBytes  int32  `json:"size_bytes"`
	Digest     string `json:"digest"`
	Content    []byte `json:"content"`
}

func (q *Queries) InsertBundleFile(ctx context.Context, arg InsertBundleFileParams) error {
	_, err := q.db.Exec(ctx, insertBundleFile,
		arg.ArtifactID,
		arg.Path,
		arg.MediaType,
		arg.SizeBytes,
		arg.Digest,
		arg.Content,
	)
	return err
}

const listArtifactIDPage = `-- name: ListArtifactIDPage :many
SELECT id
FROM workos_core.web_bundle_artifacts
WHERE owner_user_id = $1
  AND ($2 = '' OR id > $2::uuid)
ORDER BY id
LIMIT $3
`

type ListArtifactIDPageParams struct {
	OwnerUserID string      `json:"owner_user_id"`
	Cursor      interface{} `json:"cursor"`
	RowLimit    int32       `json:"row_limit"`
}

func (q *Queries) ListArtifactIDPage(ctx context.Context, arg ListArtifactIDPageParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listArtifactIDPage, arg.OwnerUserID, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactSummaries = `-- name: ListArtifactSummaries :many
SELECT id, owner_user_id, type, title, media_type, content_ref, digest,
       entrypoint, file_count, total_size_bytes, created_at
FROM workos_core.web_bundle_artifacts
WHERE owner_user_id = $1 AND id = ANY($2::uuid[])
ORDER BY id
`

type ListArtifactSummariesParams struct {
	OwnerUserID string   `json:"owner_user_id"`
	Ids         []string `json:"ids"`
}

func (q *Queries) ListArtifactSummaries(ctx context.Context, arg ListArtifactSummariesParams) ([]WorkosCoreWebBundleArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactSummaries, arg.OwnerUserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosCoreWebBundleArtifact
	for rows.Next() {
		var i WorkosCoreWebBundleArtifact
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Type,
			&i.Title,
			&i.MediaType,
			&i.ContentRef,
			&i.Digest,
			&i.Entrypoint,
			&i.FileCount,
			&i.TotalSizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readBundleAsset = `-- name: ReadBundleAsset :one
SELECT f.path, f.media_type, f.size_bytes, f.digest, f.content
FROM workos_core.web_bundle_files f
JOIN workos_core.web_bundle_artifacts a ON a.id = f.artifact_id
WHERE a.owner_user_id = $1 AND a.id = $2 AND f.path = $3
`

type ReadBundleAssetParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ID          string `json:"id"`
	Path        string `json:"path"`
}

type ReadBundleAssetRow struct {
	Path      string `json:"path"`
	MediaType string `json:"media_type"`
	SizeBytes int32  `json:"size_bytes"`
	Digest    string `json:"digest"`
	Content   []byte `json:"content"`
}

func (q *Queries) ReadBundleAsset(ctx context.Context, arg ReadBundleAssetParams) (ReadBundleAssetRow, error) {
	row := q.db.QueryRow(ctx, readBundleAsset, arg.OwnerUserID, arg.ID, arg.Path)
	var i ReadBundleAssetRow
	err := row.Scan(
		&i.Path,
		&i.MediaType,
		&i.SizeBytes,
		&i.Digest,
		&i.Content,
	)
	return i, err
}
