// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package artifactdb

import (
	"context"
)

type Querier interface {
	GetArtifact(ctx context.Context, arg GetArtifactParams) (WorkosCoreWebBundleArtifact, error)
	GetArtifactRequest(ctx context.Context, arg GetArtifactRequestParams) (WorkosCoreWebBundleArtifactRequest, error)
	InsertArtifact(ctx context.Context, arg InsertArtifactParams) error
	InsertArtifactRequest(ctx context.Context, arg InsertArtifactRequestParams) (int64, error)
	InsertBundleFile(ctx context.Context, arg InsertBundleFileParams) error
	ListArtifactIDPage(ctx context.Context, arg ListArtifactIDPageParams) ([]string, error)
	ListArtifactSummaries(ctx context.Context, arg ListArtifactSummariesParams) ([]WorkosCoreWebBundleArtifact, error)
	ReadBundleAsset(ctx context.Context, arg ReadBundleAssetParams) (ReadBundleAssetRow, error)
}

var _ Querier = (*Queries)(nil)
