// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package gatewayauthdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const authStoreReady = `-- name: AuthStoreReady :one

SELECT 1
`

// Gateway-owned device auth queries (owner: workos-gateway; ADR-0007).
// Every query targets the workos_gateway schema exclusively; no query in
// this package may touch Core, Runtime, or Reliability tables. State
// transitions are guarded UPDATEs: the caller treats 0 affected rows as a
// lost race or an expired object, never as silent success.
func (q *Queries) AuthStoreReady(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, authStoreReady)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const claimPairingTicket = `-- name: ClaimPairingTicket :one
UPDATE workos_gateway.pairing_tickets
SET state = 'claimed', claimed_at = $1::timestamptz,
    device_id = $2, public_key_hash = $3,
    claimed_name = $4, claimed_class = $5
WHERE id = $6 AND owner_user_id = $7
  AND state = 'pending' AND expires_at > $1::timestamptz
RETURNING id, owner_user_id, secret_hash, public_origin, tls_fingerprint,
          state, device_id, public_key_hash, claimed_name, claimed_class,
          attempts, expires_at, created_at, claimed_at, completed_at, revoked_at
`

type ClaimPairingTicketParams struct {
	Now           time.Time   `json:"now"`
	DeviceID      pgtype.UUID `json:"device_id"`
	PublicKeyHash pgtype.Text `json:"public_key_hash"`
	ClaimedName   pgtype.Text `json:"claimed_name"`
	ClaimedClass  pgtype.Text `json:"claimed_class"`
	ID            string      `json:"id"`
	OwnerUserID   string      `json:"owner_user_id"`
}

func (q *Queries) ClaimPairingTicket(ctx context.Context, arg ClaimPairingTicketParams) (WorkosGatewayPairingTicket, error) {
	row := q.db.QueryRow(ctx, claimPairingTicket,
		arg.Now,
		arg.DeviceID,
		arg.PublicKeyHash,
		arg.ClaimedName,
		arg.ClaimedClass,
		arg.ID,
		arg.OwnerUserID,
	)
	var i WorkosGatewayPairingTicket
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SecretHash,
		&i.PublicOrigin,
		&i.TlsFingerprint,
		&i.State,
		&i.DeviceID,
		&i.PublicKeyHash,
		&i.ClaimedName,
		&i.ClaimedClass,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.RevokedAt,
	)
	return i, err
}

const completePairingTicket = `-- name: CompletePairingTicket :execrows
UPDATE workos_gateway.pairing_tickets
SET state = 'completed', completed_at = $1::timestamptz
WHERE id = $2 AND state = 'claimed' AND expires_at > $1::timestamptz
`

type CompletePairingTicketParams struct {
	Now time.Time `json:"now"`
	ID  string    `json:"id"`
}

func (q *Queries) CompletePairingTicket(ctx context.Context, arg CompletePairingTicketParams) (int64, error) {
	result, err := q.db.Exec(ctx, completePairingTicket, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeChallenge = `-- name: ConsumeChallenge :execrows
UPDATE workos_gateway.device_auth_challenges
SET consumed_at = $1::timestamptz, consumed_by_device = $2,
    result = $3::text
WHERE id = $4 AND consumed_at IS NULL AND expires_at > $1::timestamptz
`

type ConsumeChallengeParams struct {
	Now      time.Time   `json:"now"`
	DeviceID pgtype.UUID `json:"device_id"`
	Result   string      `json:"result"`
	ID       string      `json:"id"`
}

func (q *Queries) ConsumeChallenge(ctx context.Context, arg ConsumeChallengeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeChallenge,
		arg.Now,
		arg.DeviceID,
		arg.Result,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failChallengeAttempt = `-- name: FailChallengeAttempt :execrows
UPDATE workos_gateway.device_auth_challenges
SET attempts = attempts + 1
WHERE id = $1 AND attempts < 10
`

func (q *Queries) FailChallengeAttempt(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, failChallengeAttempt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failTicketAttempt = `-- name: FailTicketAttempt :execrows
UPDATE workos_gateway.pairing_tickets
SET attempts = attempts + 1
WHERE id = $1 AND attempts < 10
`

func (q *Queries) FailTicketAttempt(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, failTicketAttempt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveDeviceByID = `-- name: GetActiveDeviceByID :one
SELECT id, owner_user_id, name, device_class, public_key_spki, public_key_hash,
       revision, created_at, last_authenticated_at, revoked_at
FROM workos_gateway.device_credentials
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveDeviceByID(ctx context.Context, id string) (WorkosGatewayDeviceCredential, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceByID, id)
	var i WorkosGatewayDeviceCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DeviceClass,
		&i.PublicKeySpki,
		&i.PublicKeyHash,
		&i.Revision,
		&i.CreatedAt,
		&i.LastAuthenticatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveDeviceByKeyHash = `-- name: GetActiveDeviceByKeyHash :one
SELECT id, owner_user_id, name, device_class, public_key_spki, public_key_hash,
       revision, created_at, last_authenticated_at, revoked_at
FROM workos_gateway.device_credentials
WHERE owner_user_id = $1 AND public_key_hash = $2
  AND revoked_at IS NULL
`

type GetActiveDeviceByKeyHashParams struct {
	OwnerUserID   string `json:"owner_user_id"`
	PublicKeyHash string `json:"public_key_hash"`
}

func (q *Queries) GetActiveDeviceByKeyHash(ctx context.Context, arg GetActiveDeviceByKeyHashParams) (WorkosGatewayDeviceCredential, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceByKeyHash, arg.OwnerUserID, arg.PublicKeyHash)
	var i WorkosGatewayDeviceCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DeviceClass,
		&i.PublicKeySpki,
		&i.PublicKeyHash,
		&i.Revision,
		&i.CreatedAt,
		&i.LastAuthenticatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getChallenge = `-- name: GetChallenge :one
SELECT id, purpose, device_id, ticket_id, public_key_hash, nonce, attempts,
       expires_at, created_at, consumed_at, consumed_by_device, result
FROM workos_gateway.device_auth_challenges
WHERE id = $1
`

func (q *Queries) GetChallenge(ctx context.Context, id string) (WorkosGatewayDeviceAuthChallenge, error) {
	row := q.db.QueryRow(ctx, getChallenge, id)
	var i WorkosGatewayDeviceAuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.DeviceID,
		&i.TicketID,
		&i.PublicKeyHash,
		&i.Nonce,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.ConsumedByDevice,
		&i.Result,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, owner_user_id, name, device_class, public_key_spki, public_key_hash,
       revision, created_at, last_authenticated_at, revoked_at
FROM workos_gateway.device_credentials
WHERE id = $1 AND owner_user_id = $2
`

type GetDeviceParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (WorkosGatewayDeviceCredential, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.ID, arg.OwnerUserID)
	var i WorkosGatewayDeviceCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DeviceClass,
		&i.PublicKeySpki,
		&i.PublicKeyHash,
		&i.Revision,
		&i.CreatedAt,
		&i.LastAuthenticatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPairingTicket = `-- name: GetPairingTicket :one
SELECT id, owner_user_id, secret_hash, public_origin, tls_fingerprint,
       state, device_id, public_key_hash, claimed_name, claimed_class,
       attempts, expires_at, created_at, claimed_at, completed_at, revoked_at
FROM workos_gateway.pairing_tickets
WHERE id = $1 AND owner_user_id = $2
`

type GetPairingTicketParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) GetPairingTicket(ctx context.Context, arg GetPairingTicketParams) (WorkosGatewayPairingTicket, error) {
	row := q.db.QueryRow(ctx, getPairingTicket, arg.ID, arg.OwnerUserID)
	var i WorkosGatewayPairingTicket
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SecretHash,
		&i.PublicOrigin,
		&i.TlsFingerprint,
		&i.State,
		&i.DeviceID,
		&i.PublicKeyHash,
		&i.ClaimedName,
		&i.ClaimedClass,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRevocationRequest = `-- name: GetRevocationRequest :one
SELECT owner_user_id, idempotency_key, request_digest, result, result_version, created_at
FROM workos_gateway.device_revocation_requests
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetRevocationRequestParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetRevocationRequest(ctx context.Context, arg GetRevocationRequestParams) (WorkosGatewayDeviceRevocationRequest, error) {
	row := q.db.QueryRow(ctx, getRevocationRequest, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosGatewayDeviceRevocationRequest
	err := row.Scan(
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.Result,
		&i.ResultVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, owner_user_id, device_id, token_hash, created_at, expires_at,
       last_seen_at, revoked_at
FROM workos_gateway.device_sessions
WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (WorkosGatewayDeviceSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i WorkosGatewayDeviceSession
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getTicketBySecretHash = `-- name: GetTicketBySecretHash :one
SELECT id, owner_user_id, secret_hash, public_origin, tls_fingerprint,
       state, device_id, public_key_hash, claimed_name, claimed_class,
       attempts, expires_at, created_at, claimed_at, completed_at, revoked_at
FROM workos_gateway.pairing_tickets
WHERE secret_hash = $1 AND expires_at > $2::timestamptz
`

type GetTicketBySecretHashParams struct {
	SecretHash string    `json:"secret_hash"`
	Now        time.Time `json:"now"`
}

func (q *Queries) GetTicketBySecretHash(ctx context.Context, arg GetTicketBySecretHashParams) (WorkosGatewayPairingTicket, error) {
	row := q.db.QueryRow(ctx, getTicketBySecretHash, arg.SecretHash, arg.Now)
	var i WorkosGatewayPairingTicket
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SecretHash,
		&i.PublicOrigin,
		&i.TlsFingerprint,
		&i.State,
		&i.DeviceID,
		&i.PublicKeyHash,
		&i.ClaimedName,
		&i.ClaimedClass,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertChallenge = `-- name: InsertChallenge :exec
INSERT INTO workos_gateway.device_auth_challenges (
    id, purpose, device_id, ticket_id, public_key_hash, nonce,
    attempts, expires_at, created_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, 0,
    $7::timestamptz, $8::timestamptz
)
`

type InsertChallengeParams struct {
	ID            string      `json:"id"`
	Purpose       string      `json:"purpose"`
	DeviceID      pgtype.UUID `json:"device_id"`
	TicketID      pgtype.UUID `json:"ticket_id"`
	PublicKeyHash string      `json:"public_key_hash"`
	Nonce         []byte      `json:"nonce"`
	ExpiresAt     time.Time   `json:"expires_at"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) InsertChallenge(ctx context.Context, arg InsertChallengeParams) error {
	_, err := q.db.Exec(ctx, insertChallenge,
		arg.ID,
		arg.Purpose,
		arg.DeviceID,
		arg.TicketID,
		arg.PublicKeyHash,
		arg.Nonce,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertDevice = `-- name: InsertDevice :exec
INSERT INTO workos_gateway.device_credentials (
    id, owner_user_id, name, device_class, public_key_spki, public_key_hash,
    revision, created_at, last_authenticated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, 1,
    $7::timestamptz, $7::timestamptz
)
`

type InsertDeviceParams struct {
	ID            string    `json:"id"`
	OwnerUserID   string    `json:"owner_user_id"`
	Name          string    `json:"name"`
	DeviceClass   string    `json:"device_class"`
	PublicKeySpki []byte    `json:"public_key_spki"`
	PublicKeyHash string    `json:"public_key_hash"`
	Now           time.Time `json:"now"`
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) error {
	_, err := q.db.Exec(ctx, insertDevice,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.DeviceClass,
		arg.PublicKeySpki,
		arg.PublicKeyHash,
		arg.Now,
	)
	return err
}

const insertPairingTicket = `-- name: InsertPairingTicket :exec
INSERT INTO workos_gateway.pairing_tickets (
    id, owner_user_id, secret_hash, public_origin, tls_fingerprint,
    state, attempts, expires_at, created_at
) VALUES (
    $1, $2, $3,
    $4, $5, 'pending', 0,
    $6::timestamptz, $7::timestamptz
)
`

type InsertPairingTicketParams struct {
	ID             string    `json:"id"`
	OwnerUserID    string    `json:"owner_user_id"`
	SecretHash     string    `json:"secret_hash"`
	PublicOrigin   string    `json:"public_origin"`
	TlsFingerprint string    `json:"tls_fingerprint"`
	ExpiresAt      time.Time `json:"expires_at"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertPairingTicket(ctx context.Context, arg InsertPairingTicketParams) error {
	_, err := q.db.Exec(ctx, insertPairingTicket,
		arg.ID,
		arg.OwnerUserID,
		arg.SecretHash,
		arg.PublicOrigin,
		arg.TlsFingerprint,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const insertRevocationRequest = `-- name: InsertRevocationRequest :exec
INSERT INTO workos_gateway.device_revocation_requests (
    owner_user_id, idempotency_key, request_digest, result, result_version, created_at
) VALUES (
    $1, $2, $3,
    $4::jsonb, 'v1', $5::timestamptz
)
`

type InsertRevocationRequestParams struct {
	OwnerUserID    string          `json:"owner_user_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	RequestDigest  string          `json:"request_digest"`
	Result         json.RawMessage `json:"result"`
	CreatedAt      time.Time       `json:"created_at"`
}

func (q *Queries) InsertRevocationRequest(ctx context.Context, arg InsertRevocationRequestParams) error {
	_, err := q.db.Exec(ctx, insertRevocationRequest,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO workos_gateway.device_sessions (
    id, owner_user_id, device_id, token_hash, created_at, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5::timestamptz, $6::timestamptz
)
`

type InsertSessionParams struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	DeviceID    string    `json:"device_id"`
	TokenHash   string    `json:"token_hash"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.OwnerUserID,
		arg.DeviceID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT id, owner_user_id, name, device_class, public_key_spki, public_key_hash,
       revision, created_at, last_authenticated_at, revoked_at
FROM workos_gateway.device_credentials
WHERE owner_user_id = $1 AND id < $2::uuid
ORDER BY id DESC
LIMIT $3
`

type ListDevicesParams struct {
	OwnerUserID string `json:"owner_user_id"`
	Cursor      string `json:"cursor"`
	RowLimit    int32  `json:"row_limit"`
}

func (q *Queries) ListDevices(ctx context.Context, arg ListDevicesParams) ([]WorkosGatewayDeviceCredential, error) {
	rows, err := q.db.Query(ctx, listDevices, arg.OwnerUserID, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosGatewayDeviceCredential
	for rows.Next() {
		var i WorkosGatewayDeviceCredential
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DeviceClass,
			&i.PublicKeySpki,
			&i.PublicKeyHash,
			&i.Revision,
			&i.CreatedAt,
			&i.LastAuthenticatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChallenge = `-- name: LockChallenge :one
SELECT id, purpose, device_id, ticket_id, public_key_hash, nonce, attempts,
       expires_at, created_at, consumed_at, consumed_by_device, result
FROM workos_gateway.device_auth_challenges
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockChallenge(ctx context.Context, id string) (WorkosGatewayDeviceAuthChallenge, error) {
	row := q.db.QueryRow(ctx, lockChallenge, id)
	var i WorkosGatewayDeviceAuthChallenge
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.DeviceID,
		&i.TicketID,
		&i.PublicKeyHash,
		&i.Nonce,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.ConsumedByDevice,
		&i.Result,
	)
	return i, err
}

const lockDeviceByID = `-- name: LockDeviceByID :one
SELECT id, owner_user_id, name, device_class, public_key_spki, public_key_hash,
       revision, created_at, last_authenticated_at, revoked_at
FROM workos_gateway.device_credentials
WHERE id = $1 AND revoked_at IS NULL
FOR UPDATE
`

func (q *Queries) LockDeviceByID(ctx context.Context, id string) (WorkosGatewayDeviceCredential, error) {
	row := q.db.QueryRow(ctx, lockDeviceByID, id)
	var i WorkosGatewayDeviceCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DeviceClass,
		&i.PublicKeySpki,
		&i.PublicKeyHash,
		&i.Revision,
		&i.CreatedAt,
		&i.LastAuthenticatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockDeviceForSession = `-- name: LockDeviceForSession :one
SELECT id, owner_user_id, name, device_class, public_key_spki, public_key_hash,
       revision, created_at, last_authenticated_at, revoked_at
FROM workos_gateway.device_credentials
WHERE id = $1 AND owner_user_id = $2 AND revoked_at IS NULL
FOR UPDATE
`

type LockDeviceForSessionParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) LockDeviceForSession(ctx context.Context, arg LockDeviceForSessionParams) (WorkosGatewayDeviceCredential, error) {
	row := q.db.QueryRow(ctx, lockDeviceForSession, arg.ID, arg.OwnerUserID)
	var i WorkosGatewayDeviceCredential
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DeviceClass,
		&i.PublicKeySpki,
		&i.PublicKeyHash,
		&i.Revision,
		&i.CreatedAt,
		&i.LastAuthenticatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockOwnerTicketRotation = `-- name: LockOwnerTicketRotation :exec
SELECT pg_advisory_xact_lock(2087990351, hashtext($1::text))
`

func (q *Queries) LockOwnerTicketRotation(ctx context.Context, ownerUserID string) error {
	_, err := q.db.Exec(ctx, lockOwnerTicketRotation, ownerUserID)
	return err
}

const lockTicketForComplete = `-- name: LockTicketForComplete :one
SELECT id, owner_user_id, secret_hash, public_origin, tls_fingerprint,
       state, device_id, public_key_hash, claimed_name, claimed_class,
       attempts, expires_at, created_at, claimed_at, completed_at, revoked_at
FROM workos_gateway.pairing_tickets
WHERE id = $1 AND state = 'claimed'
FOR UPDATE
`

func (q *Queries) LockTicketForComplete(ctx context.Context, id string) (WorkosGatewayPairingTicket, error) {
	row := q.db.QueryRow(ctx, lockTicketForComplete, id)
	var i WorkosGatewayPairingTicket
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.SecretHash,
		&i.PublicOrigin,
		&i.TlsFingerprint,
		&i.State,
		&i.DeviceID,
		&i.PublicKeyHash,
		&i.ClaimedName,
		&i.ClaimedClass,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.CompletedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeActiveSessions = `-- name: RevokeActiveSessions :execrows
UPDATE workos_gateway.device_sessions
SET revoked_at = now()
WHERE device_id = $1 AND owner_user_id = $2
  AND revoked_at IS NULL
`

type RevokeActiveSessionsParams struct {
	DeviceID    string `json:"device_id"`
	OwnerUserID string `json:"owner_user_id"`
}

// Database transaction time, for the same monotonicity reason as ticket
// rotation: a session a concurrent transaction just committed must never
// outlive its own creation timestamp.
func (q *Queries) RevokeActiveSessions(ctx context.Context, arg RevokeActiveSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveSessions, arg.DeviceID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDeviceCredential = `-- name: RevokeDeviceCredential :execrows
UPDATE workos_gateway.device_credentials
SET revoked_at = $1::timestamptz, revision = revision + 1
WHERE id = $2 AND owner_user_id = $3
  AND revision = $4 AND revoked_at IS NULL
`

type RevokeDeviceCredentialParams struct {
	Now              time.Time `json:"now"`
	ID               string    `json:"id"`
	OwnerUserID      string    `json:"owner_user_id"`
	ExpectedRevision int64     `json:"expected_revision"`
}

func (q *Queries) RevokeDeviceCredential(ctx context.Context, arg RevokeDeviceCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDeviceCredential,
		arg.Now,
		arg.ID,
		arg.OwnerUserID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokePendingTickets = `-- name: RevokePendingTickets :execrows
UPDATE workos_gateway.pairing_tickets
SET state = 'revoked', revoked_at = now()
WHERE owner_user_id = $1 AND state = 'pending'
`

// The revocation timestamp is the database transaction time: rotations
// serialized by the owner lock must never stamp a revocation earlier than a
// ticket a previous lock holder already committed.
func (q *Queries) RevokePendingTickets(ctx context.Context, ownerUserID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokePendingTickets, ownerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE workos_gateway.device_sessions
SET revoked_at = now()
WHERE id = $1 AND owner_user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDeviceAuthenticated = `-- name: TouchDeviceAuthenticated :execrows
UPDATE workos_gateway.device_credentials
SET last_authenticated_at = $1::timestamptz
WHERE id = $2 AND owner_user_id = $3 AND revoked_at IS NULL
`

type TouchDeviceAuthenticatedParams struct {
	Now         time.Time `json:"now"`
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
}

func (q *Queries) TouchDeviceAuthenticated(ctx context.Context, arg TouchDeviceAuthenticatedParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchDeviceAuthenticated, arg.Now, arg.ID, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSessionLastSeen = `-- name: TouchSessionLastSeen :execrows
UPDATE workos_gateway.device_sessions
SET last_seen_at = $1::timestamptz
WHERE id = $2 AND revoked_at IS NULL
  AND (last_seen_at IS NULL OR last_seen_at < $3::timestamptz)
`

type TouchSessionLastSeenParams struct {
	Now       time.Time `json:"now"`
	ID        string    `json:"id"`
	Threshold time.Time `json:"threshold"`
}

func (q *Queries) TouchSessionLastSeen(ctx context.Context, arg TouchSessionLastSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSessionLastSeen, arg.Now, arg.ID, arg.Threshold)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
