// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package nativehostdb

import (
	"time"
)

type WorkosRuntimeNativeSession struct {
	SessionID      string    `json:"session_id"`
	OwnerUserID    string    `json:"owner_user_id"`
	ProjectID      string    `json:"project_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	RequestDigest  string    `json:"request_digest"`
	State          string    `json:"state"`
	Width          int32     `json:"width"`
	Height         int32     `json:"height"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	ExpiresAt      time.Time `json:"expires_at"`
}
