// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package nativehostdb

import (
	"context"
	"time"
)

type Querier interface {
	CloseNativeSession(ctx context.Context, arg CloseNativeSessionParams) (int64, error)
	CountActiveNativeSessions(ctx context.Context, ownerUserID string) (int64, error)
	ExpireIdleNativeSessions(ctx context.Context, updatedAt time.Time) ([]string, error)
	GetNativeSession(ctx context.Context, arg GetNativeSessionParams) (WorkosRuntimeNativeSession, error)
	GetNativeSessionByKey(ctx context.Context, arg GetNativeSessionByKeyParams) (WorkosRuntimeNativeSession, error)
	InsertNativeSession(ctx context.Context, arg InsertNativeSessionParams) (int64, error)
	UpdateNativeSessionState(ctx context.Context, arg UpdateNativeSessionStateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
