// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package nativehostdb

import (
	"context"
	"time"
)

const closeNativeSession = `-- name: CloseNativeSession :execrows
UPDATE workos_runtime.native_sessions
SET state = $3, updated_at = $4, expires_at = $4
WHERE owner_user_id = $1 AND session_id = $2 AND state IN ('queued', 'running')
`

type CloseNativeSessionParams struct {
	OwnerUserID string    `json:"owner_user_id"`
	SessionID   string    `json:"session_id"`
	State       string    `json:"state"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CloseNativeSession(ctx context.Context, arg CloseNativeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeNativeSession,
		arg.OwnerUserID,
		arg.SessionID,
		arg.State,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveNativeSessions = `-- name: CountActiveNativeSessions :one
SELECT count(*) AS active
FROM workos_runtime.native_sessions
WHERE owner_user_id = $1 AND state IN ('queued', 'running')
`

func (q *Queries) CountActiveNativeSessions(ctx context.Context, ownerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveNativeSessions, ownerUserID)
	var active int64
	err := row.Scan(&active)
	return active, err
}

const expireIdleNativeSessions = `-- name: ExpireIdleNativeSessions :many
UPDATE workos_runtime.native_sessions
SET state = 'closed', updated_at = $1, expires_at = $1
WHERE state IN ('queued', 'running') AND expires_at < $1
RETURNING session_id::text AS session_id
`

func (q *Queries) ExpireIdleNativeSessions(ctx context.Context, updatedAt time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, expireIdleNativeSessions, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNativeSession = `-- name: GetNativeSession :one
SELECT session_id, owner_user_id, project_id, idempotency_key, request_digest,
       state, width, height, created_at, updated_at, expires_at
FROM workos_runtime.native_sessions
WHERE owner_user_id = $1 AND session_id = $2
`

type GetNativeSessionParams struct {
	OwnerUserID string `json:"owner_user_id"`
	SessionID   string `json:"session_id"`
}

func (q *Queries) GetNativeSession(ctx context.Context, arg GetNativeSessionParams) (WorkosRuntimeNativeSession, error) {
	row := q.db.QueryRow(ctx, getNativeSession, arg.OwnerUserID, arg.SessionID)
	var i WorkosRuntimeNativeSession
	err := row.Scan(
		&i.SessionID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.State,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getNativeSessionByKey = `-- name: GetNativeSessionByKey :one
SELECT session_id, owner_user_id, project_id, idempotency_key, request_digest,
       state, width, height, created_at, updated_at, expires_at
FROM workos_runtime.native_sessions
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetNativeSessionByKeyParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetNativeSessionByKey(ctx context.Context, arg GetNativeSessionByKeyParams) (WorkosRuntimeNativeSession, error) {
	row := q.db.QueryRow(ctx, getNativeSessionByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosRuntimeNativeSession
	err := row.Scan(
		&i.SessionID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.State,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertNativeSession = `-- name: InsertNativeSession :execrows
INSERT INTO workos_runtime.native_sessions (
    session_id, owner_user_id, project_id, idempotency_key, request_digest,
    state, width, height, created_at, updated_at, expires_at
) VALUES ($1, $2, $3, $4, $5, 'queued', $6, $7, $8, $8, $9)
ON CONFLICT (owner_user_id, idempotency_key) DO NOTHING
`

type InsertNativeSessionParams struct {
	SessionID      string    `json:"session_id"`
	OwnerUserID    string    `json:"owner_user_id"`
	ProjectID      string    `json:"project_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	RequestDigest  string    `json:"request_digest"`
	Width          int32     `json:"width"`
	Height         int32     `json:"height"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) InsertNativeSession(ctx context.Context, arg InsertNativeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNativeSession,
		arg.SessionID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.Width,
		arg.Height,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveNativeSessions = `-- name: ListActiveNativeSessions :many
SELECT session_id, owner_user_id, project_id, idempotency_key, request_digest,
       state, width, height, created_at, updated_at, expires_at
FROM workos_runtime.native_sessions
WHERE state IN ('queued', 'running')
`

func (q *Queries) ListActiveNativeSessions(ctx context.Context) ([]WorkosRuntimeNativeSession, error) {
	rows, err := q.db.Query(ctx, listActiveNativeSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosRuntimeNativeSession
	for rows.Next() {
		var i WorkosRuntimeNativeSession
		if err := rows.Scan(
			&i.SessionID,
			&i.OwnerUserID,
			&i.ProjectID,
			&i.IdempotencyKey,
			&i.RequestDigest,
			&i.State,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNativeSessionState = `-- name: UpdateNativeSessionState :execrows
UPDATE workos_runtime.native_sessions
SET state = $3, updated_at = $4
WHERE owner_user_id = $1 AND session_id = $2 AND state IN ('queued', 'running')
`

type UpdateNativeSessionStateParams struct {
	OwnerUserID string    `json:"owner_user_id"`
	SessionID   string    `json:"session_id"`
	State       string    `json:"state"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateNativeSessionState(ctx context.Context, arg UpdateNativeSessionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNativeSessionState,
		arg.OwnerUserID,
		arg.SessionID,
		arg.State,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
