// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package credentialdb

import (
	"context"
	"time"
)

type Querier interface {
	ExpireStaleTaskCredentialLeases(ctx context.Context, expiresAt time.Time) (int64, error)
	ExtendTaskCredentialLease(ctx context.Context, arg ExtendTaskCredentialLeaseParams) (int64, error)
	FinalizeCredentialRequest(ctx context.Context, arg FinalizeCredentialRequestParams) error
	GetActiveCredential(ctx context.Context, arg GetActiveCredentialParams) (GetActiveCredentialRow, error)
	GetCredentialByID(ctx context.Context, arg GetCredentialByIDParams) (GetCredentialByIDRow, error)
	GetCredentialRequest(ctx context.Context, arg GetCredentialRequestParams) (GetCredentialRequestRow, error)
	GetTaskCredentialLease(ctx context.Context, taskLeaseID string) (GetTaskCredentialLeaseRow, error)
	GetTaskCredentialLeaseByLeaseID(ctx context.Context, id string) (GetTaskCredentialLeaseByLeaseIDRow, error)
	InsertCredentialRequest(ctx context.Context, arg InsertCredentialRequestParams) (int64, error)
	// Credential Vault owned queries (ADR-0009). Everything here touches only
	// Credential-owned tables. Plaintext secrets never appear in any statement:
	// the adapter seals before insert and opens after read, inside its own
	// transaction.
	InsertProviderCredential(ctx context.Context, arg InsertProviderCredentialParams) (int64, error)
	InsertTaskCredentialLease(ctx context.Context, arg InsertTaskCredentialLeaseParams) (int64, error)
	ListOwnerCredentials(ctx context.Context, ownerUserID string) ([]ListOwnerCredentialsRow, error)
	LockActiveTaskCredentialLease(ctx context.Context, arg LockActiveTaskCredentialLeaseParams) (LockActiveTaskCredentialLeaseRow, error)
	LockProviderCredential(ctx context.Context, id string) (WorkosCoreProviderCredential, error)
	// Sealed read for lease issuance inside the coordinator transaction: the
	// exact credential identity must still be active at the exact snapshot
	// revision, or the lease fails closed.
	LockSealedCredentialForTask(ctx context.Context, arg LockSealedCredentialForTaskParams) (WorkosCoreProviderCredential, error)
	ReleaseTaskCredentialLease(ctx context.Context, arg ReleaseTaskCredentialLeaseParams) (int64, error)
	RenewTaskCredentialLease(ctx context.Context, arg RenewTaskCredentialLeaseParams) (RenewTaskCredentialLeaseRow, error)
	RevokeProviderCredential(ctx context.Context, arg RevokeProviderCredentialParams) (int64, error)
	UpdateCredentialMaterial(ctx context.Context, arg UpdateCredentialMaterialParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
