// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package credentialdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireStaleTaskCredentialLeases = `-- name: ExpireStaleTaskCredentialLeases :execrows
UPDATE workos_core.task_credential_leases
SET status = 'expired'
WHERE status = 'active' AND expires_at < $1
`

func (q *Queries) ExpireStaleTaskCredentialLeases(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleTaskCredentialLeases, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendTaskCredentialLease = `-- name: ExtendTaskCredentialLease :execrows
UPDATE workos_core.task_credential_leases
SET expires_at = $1
WHERE id = $2
`

type ExtendTaskCredentialLeaseParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        string    `json:"id"`
}

func (q *Queries) ExtendTaskCredentialLease(ctx context.Context, arg ExtendTaskCredentialLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendTaskCredentialLease, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeCredentialRequest = `-- name: FinalizeCredentialRequest :exec
UPDATE workos_core.credential_admin_requests
SET result = $1
WHERE owner_user_id = $2 AND idempotency_key = $3
`

type FinalizeCredentialRequestParams struct {
	Result         json.RawMessage `json:"result"`
	OwnerUserID    string          `json:"owner_user_id"`
	IdempotencyKey string          `json:"idempotency_key"`
}

func (q *Queries) FinalizeCredentialRequest(ctx context.Context, arg FinalizeCredentialRequestParams) error {
	_, err := q.db.Exec(ctx, finalizeCredentialRequest, arg.Result, arg.OwnerUserID, arg.IdempotencyKey)
	return err
}

const getActiveCredential = `-- name: GetActiveCredential :one
SELECT id, owner_user_id, consumer_id, purpose, label, revision, status, created_at, updated_at
FROM workos_core.provider_credentials
WHERE owner_user_id = $1 AND consumer_id = $2 AND purpose = $3 AND status = 'active'
`

type GetActiveCredentialParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ConsumerID  string `json:"consumer_id"`
	Purpose     string `json:"purpose"`
}

type GetActiveCredentialRow struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetActiveCredential(ctx context.Context, arg GetActiveCredentialParams) (GetActiveCredentialRow, error) {
	row := q.db.QueryRow(ctx, getActiveCredential, arg.OwnerUserID, arg.ConsumerID, arg.Purpose)
	var i GetActiveCredentialRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.Label,
		&i.Revision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, owner_user_id, consumer_id, purpose, label, revision, status, created_at, updated_at
FROM workos_core.provider_credentials
WHERE id = $1 AND owner_user_id = $2
`

type GetCredentialByIDParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

type GetCredentialByIDRow struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetCredentialByID(ctx context.Context, arg GetCredentialByIDParams) (GetCredentialByIDRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByID, arg.ID, arg.OwnerUserID)
	var i GetCredentialByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.Label,
		&i.Revision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialRequest = `-- name: GetCredentialRequest :one
SELECT request_digest, result, created_at
FROM workos_core.credential_admin_requests
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetCredentialRequestParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type GetCredentialRequestRow struct {
	RequestDigest string          `json:"request_digest"`
	Result        json.RawMessage `json:"result"`
	CreatedAt     time.Time       `json:"created_at"`
}

func (q *Queries) GetCredentialRequest(ctx context.Context, arg GetCredentialRequestParams) (GetCredentialRequestRow, error) {
	row := q.db.QueryRow(ctx, getCredentialRequest, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetCredentialRequestRow
	err := row.Scan(&i.RequestDigest, &i.Result, &i.CreatedAt)
	return i, err
}

const getTaskCredentialLease = `-- name: GetTaskCredentialLease :one
SELECT id, task_lease_id, task_id, worker_id, owner_user_id, consumer_id, purpose,
       credential_id, credential_revision, status, expires_at
FROM workos_core.task_credential_leases
WHERE task_lease_id = $1
`

type GetTaskCredentialLeaseRow struct {
	ID                 string    `json:"id"`
	TaskLeaseID        string    `json:"task_lease_id"`
	TaskID             string    `json:"task_id"`
	WorkerID           string    `json:"worker_id"`
	OwnerUserID        string    `json:"owner_user_id"`
	ConsumerID         string    `json:"consumer_id"`
	Purpose            string    `json:"purpose"`
	CredentialID       string    `json:"credential_id"`
	CredentialRevision int64     `json:"credential_revision"`
	Status             string    `json:"status"`
	ExpiresAt          time.Time `json:"expires_at"`
}

func (q *Queries) GetTaskCredentialLease(ctx context.Context, taskLeaseID string) (GetTaskCredentialLeaseRow, error) {
	row := q.db.QueryRow(ctx, getTaskCredentialLease, taskLeaseID)
	var i GetTaskCredentialLeaseRow
	err := row.Scan(
		&i.ID,
		&i.TaskLeaseID,
		&i.TaskID,
		&i.WorkerID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.CredentialID,
		&i.CredentialRevision,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const getTaskCredentialLeaseByLeaseID = `-- name: GetTaskCredentialLeaseByLeaseID :one
SELECT id, task_lease_id, task_id, worker_id, owner_user_id, consumer_id, purpose,
       credential_id, credential_revision, status, expires_at
FROM workos_core.task_credential_leases
WHERE id = $1
`

type GetTaskCredentialLeaseByLeaseIDRow struct {
	ID                 string    `json:"id"`
	TaskLeaseID        string    `json:"task_lease_id"`
	TaskID             string    `json:"task_id"`
	WorkerID           string    `json:"worker_id"`
	OwnerUserID        string    `json:"owner_user_id"`
	ConsumerID         string    `json:"consumer_id"`
	Purpose            string    `json:"purpose"`
	CredentialID       string    `json:"credential_id"`
	CredentialRevision int64     `json:"credential_revision"`
	Status             string    `json:"status"`
	ExpiresAt          time.Time `json:"expires_at"`
}

func (q *Queries) GetTaskCredentialLeaseByLeaseID(ctx context.Context, id string) (GetTaskCredentialLeaseByLeaseIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskCredentialLeaseByLeaseID, id)
	var i GetTaskCredentialLeaseByLeaseIDRow
	err := row.Scan(
		&i.ID,
		&i.TaskLeaseID,
		&i.TaskID,
		&i.WorkerID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.CredentialID,
		&i.CredentialRevision,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const getVaultState = `-- name: GetVaultState :one

SELECT singleton, current_epoch, updated_at
FROM workos_core.credential_vault_state
WHERE singleton
`

// ADR-0015 expansion: master-key epoch state, online rotation, audited
// reveal, and the append-only admin audit trail.
func (q *Queries) GetVaultState(ctx context.Context) (WorkosCoreCredentialVaultState, error) {
	row := q.db.QueryRow(ctx, getVaultState)
	var i WorkosCoreCredentialVaultState
	err := row.Scan(&i.Singleton, &i.CurrentEpoch, &i.UpdatedAt)
	return i, err
}

const insertCredentialAudit = `-- name: InsertCredentialAudit :exec
INSERT INTO workos_core.credential_admin_audit (
    id, occurred_at, action, owner_user_id, credential_id, consumer_id, purpose, revision, key_epoch, result
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertCredentialAuditParams struct {
	ID           string      `json:"id"`
	OccurredAt   time.Time   `json:"occurred_at"`
	Action       string      `json:"action"`
	OwnerUserID  pgtype.UUID `json:"owner_user_id"`
	CredentialID pgtype.UUID `json:"credential_id"`
	ConsumerID   pgtype.Text `json:"consumer_id"`
	Purpose      pgtype.Text `json:"purpose"`
	Revision     pgtype.Int8 `json:"revision"`
	KeyEpoch     pgtype.Int8 `json:"key_epoch"`
	Result       string      `json:"result"`
}

func (q *Queries) InsertCredentialAudit(ctx context.Context, arg InsertCredentialAuditParams) error {
	_, err := q.db.Exec(ctx, insertCredentialAudit,
		arg.ID,
		arg.OccurredAt,
		arg.Action,
		arg.OwnerUserID,
		arg.CredentialID,
		arg.ConsumerID,
		arg.Purpose,
		arg.Revision,
		arg.KeyEpoch,
		arg.Result,
	)
	return err
}

const insertCredentialRequest = `-- name: InsertCredentialRequest :execrows
INSERT INTO workos_core.credential_admin_requests (
    owner_user_id, idempotency_key, request_digest, result_version, result, created_at
) VALUES ($1, $2, $3, 1, $4, $5)
ON CONFLICT (owner_user_id, idempotency_key) DO NOTHING
`

type InsertCredentialRequestParams struct {
	OwnerUserID    string          `json:"owner_user_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	RequestDigest  string          `json:"request_digest"`
	Result         json.RawMessage `json:"result"`
	CreatedAt      time.Time       `json:"created_at"`
}

func (q *Queries) InsertCredentialRequest(ctx context.Context, arg InsertCredentialRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCredentialRequest,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.Result,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProviderCredential = `-- name: InsertProviderCredential :execrows

INSERT INTO workos_core.provider_credentials (
    id, owner_user_id, consumer_id, purpose, label, revision, status, nonce, ciphertext, key_epoch, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT DO NOTHING
`

type InsertProviderCredentialParams struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	Nonce       []byte    `json:"nonce"`
	Ciphertext  []byte    `json:"ciphertext"`
	KeyEpoch    int64     `json:"key_epoch"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Credential Vault owned queries (ADR-0009). Everything here touches only
// Credential-owned tables. Plaintext secrets never appear in any statement:
// the adapter seals before insert and opens after read, inside its own
// transaction.
func (q *Queries) InsertProviderCredential(ctx context.Context, arg InsertProviderCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertProviderCredential,
		arg.ID,
		arg.OwnerUserID,
		arg.ConsumerID,
		arg.Purpose,
		arg.Label,
		arg.Revision,
		arg.Status,
		arg.Nonce,
		arg.Ciphertext,
		arg.KeyEpoch,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTaskCredentialLease = `-- name: InsertTaskCredentialLease :execrows
INSERT INTO workos_core.task_credential_leases (
    id, task_lease_id, task_id, worker_id, owner_user_id, consumer_id, purpose,
    credential_id, credential_revision, status, expires_at, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'active', $10, $11)
ON CONFLICT (task_lease_id) DO NOTHING
`

type InsertTaskCredentialLeaseParams struct {
	ID                 string    `json:"id"`
	TaskLeaseID        string    `json:"task_lease_id"`
	TaskID             string    `json:"task_id"`
	WorkerID           string    `json:"worker_id"`
	OwnerUserID        string    `json:"owner_user_id"`
	ConsumerID         string    `json:"consumer_id"`
	Purpose            string    `json:"purpose"`
	CredentialID       string    `json:"credential_id"`
	CredentialRevision int64     `json:"credential_revision"`
	ExpiresAt          time.Time `json:"expires_at"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) InsertTaskCredentialLease(ctx context.Context, arg InsertTaskCredentialLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTaskCredentialLease,
		arg.ID,
		arg.TaskLeaseID,
		arg.TaskID,
		arg.WorkerID,
		arg.OwnerUserID,
		arg.ConsumerID,
		arg.Purpose,
		arg.CredentialID,
		arg.CredentialRevision,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOwnerCredentials = `-- name: ListOwnerCredentials :many
SELECT id, owner_user_id, consumer_id, purpose, label, revision, status, created_at, updated_at
FROM workos_core.provider_credentials
WHERE owner_user_id = $1
ORDER BY consumer_id, purpose, id
`

type ListOwnerCredentialsRow struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListOwnerCredentials(ctx context.Context, ownerUserID string) ([]ListOwnerCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerCredentials, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnerCredentialsRow
	for rows.Next() {
		var i ListOwnerCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.ConsumerID,
			&i.Purpose,
			&i.Label,
			&i.Revision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveTaskCredentialLease = `-- name: LockActiveTaskCredentialLease :one
SELECT id, task_lease_id, task_id, worker_id, owner_user_id, consumer_id, purpose,
       credential_id, credential_revision, status, expires_at
FROM workos_core.task_credential_leases
WHERE id = $1 AND task_lease_id = $2 AND worker_id = $3
  AND status = 'active' AND expires_at >= $4
FOR UPDATE
`

type LockActiveTaskCredentialLeaseParams struct {
	ID          string    `json:"id"`
	TaskLeaseID string    `json:"task_lease_id"`
	WorkerID    string    `json:"worker_id"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type LockActiveTaskCredentialLeaseRow struct {
	ID                 string    `json:"id"`
	TaskLeaseID        string    `json:"task_lease_id"`
	TaskID             string    `json:"task_id"`
	WorkerID           string    `json:"worker_id"`
	OwnerUserID        string    `json:"owner_user_id"`
	ConsumerID         string    `json:"consumer_id"`
	Purpose            string    `json:"purpose"`
	CredentialID       string    `json:"credential_id"`
	CredentialRevision int64     `json:"credential_revision"`
	Status             string    `json:"status"`
	ExpiresAt          time.Time `json:"expires_at"`
}

func (q *Queries) LockActiveTaskCredentialLease(ctx context.Context, arg LockActiveTaskCredentialLeaseParams) (LockActiveTaskCredentialLeaseRow, error) {
	row := q.db.QueryRow(ctx, lockActiveTaskCredentialLease,
		arg.ID,
		arg.TaskLeaseID,
		arg.WorkerID,
		arg.ExpiresAt,
	)
	var i LockActiveTaskCredentialLeaseRow
	err := row.Scan(
		&i.ID,
		&i.TaskLeaseID,
		&i.TaskID,
		&i.WorkerID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.CredentialID,
		&i.CredentialRevision,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const lockAllCredentialRows = `-- name: LockAllCredentialRows :many
SELECT id, owner_user_id, consumer_id, purpose, label, revision, status, nonce, ciphertext, key_epoch, created_at, updated_at
FROM workos_core.provider_credentials
ORDER BY id
FOR UPDATE
`

type LockAllCredentialRowsRow struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	Nonce       []byte    `json:"nonce"`
	Ciphertext  []byte    `json:"ciphertext"`
	KeyEpoch    int64     `json:"key_epoch"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) LockAllCredentialRows(ctx context.Context) ([]LockAllCredentialRowsRow, error) {
	rows, err := q.db.Query(ctx, lockAllCredentialRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAllCredentialRowsRow
	for rows.Next() {
		var i LockAllCredentialRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.ConsumerID,
			&i.Purpose,
			&i.Label,
			&i.Revision,
			&i.Status,
			&i.Nonce,
			&i.Ciphertext,
			&i.KeyEpoch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAllProviderCredentials = `-- name: LockAllProviderCredentials :many
SELECT id, owner_user_id, consumer_id, purpose, label, revision, status, nonce, ciphertext, key_epoch, created_at, updated_at
FROM workos_core.provider_credentials
FOR UPDATE
`

type LockAllProviderCredentialsRow struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	Nonce       []byte    `json:"nonce"`
	Ciphertext  []byte    `json:"ciphertext"`
	KeyEpoch    int64     `json:"key_epoch"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) LockAllProviderCredentials(ctx context.Context) ([]LockAllProviderCredentialsRow, error) {
	rows, err := q.db.Query(ctx, lockAllProviderCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAllProviderCredentialsRow
	for rows.Next() {
		var i LockAllProviderCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.ConsumerID,
			&i.Purpose,
			&i.Label,
			&i.Revision,
			&i.Status,
			&i.Nonce,
			&i.Ciphertext,
			&i.KeyEpoch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnerCredential = `-- name: LockOwnerCredential :one
SELECT id, owner_user_id, consumer_id, purpose, label, revision, status, nonce, ciphertext, key_epoch, created_at, updated_at
FROM workos_core.provider_credentials
WHERE id = $1 AND owner_user_id = $2
FOR UPDATE
`

type LockOwnerCredentialParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

type LockOwnerCredentialRow struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	Nonce       []byte    `json:"nonce"`
	Ciphertext  []byte    `json:"ciphertext"`
	KeyEpoch    int64     `json:"key_epoch"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) LockOwnerCredential(ctx context.Context, arg LockOwnerCredentialParams) (LockOwnerCredentialRow, error) {
	row := q.db.QueryRow(ctx, lockOwnerCredential, arg.ID, arg.OwnerUserID)
	var i LockOwnerCredentialRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.Label,
		&i.Revision,
		&i.Status,
		&i.Nonce,
		&i.Ciphertext,
		&i.KeyEpoch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockProviderCredential = `-- name: LockProviderCredential :one
SELECT id, owner_user_id, consumer_id, purpose, label, revision, status, nonce, ciphertext, key_epoch, created_at, updated_at
FROM workos_core.provider_credentials
WHERE id = $1
FOR UPDATE
`

type LockProviderCredentialRow struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	Nonce       []byte    `json:"nonce"`
	Ciphertext  []byte    `json:"ciphertext"`
	KeyEpoch    int64     `json:"key_epoch"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) LockProviderCredential(ctx context.Context, id string) (LockProviderCredentialRow, error) {
	row := q.db.QueryRow(ctx, lockProviderCredential, id)
	var i LockProviderCredentialRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.Label,
		&i.Revision,
		&i.Status,
		&i.Nonce,
		&i.Ciphertext,
		&i.KeyEpoch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSealedCredentialForTask = `-- name: LockSealedCredentialForTask :one
SELECT id, owner_user_id, consumer_id, purpose, label, revision, status, nonce, ciphertext, key_epoch, created_at, updated_at
FROM workos_core.provider_credentials
WHERE id = $1 AND owner_user_id = $2
FOR UPDATE
`

type LockSealedCredentialForTaskParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

type LockSealedCredentialForTaskRow struct {
	ID          string    `json:"id"`
	OwnerUserID string    `json:"owner_user_id"`
	ConsumerID  string    `json:"consumer_id"`
	Purpose     string    `json:"purpose"`
	Label       string    `json:"label"`
	Revision    int64     `json:"revision"`
	Status      string    `json:"status"`
	Nonce       []byte    `json:"nonce"`
	Ciphertext  []byte    `json:"ciphertext"`
	KeyEpoch    int64     `json:"key_epoch"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// Sealed read for lease issuance inside the coordinator transaction: the
// exact credential identity must still be active at the exact snapshot
// revision, or the lease fails closed.
func (q *Queries) LockSealedCredentialForTask(ctx context.Context, arg LockSealedCredentialForTaskParams) (LockSealedCredentialForTaskRow, error) {
	row := q.db.QueryRow(ctx, lockSealedCredentialForTask, arg.ID, arg.OwnerUserID)
	var i LockSealedCredentialForTaskRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.Label,
		&i.Revision,
		&i.Status,
		&i.Nonce,
		&i.Ciphertext,
		&i.KeyEpoch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseTaskCredentialLease = `-- name: ReleaseTaskCredentialLease :execrows
UPDATE workos_core.task_credential_leases
SET status = 'released', released_at = $1
WHERE id = $2 AND task_lease_id = $3 AND worker_id = $4 AND status = 'active'
`

type ReleaseTaskCredentialLeaseParams struct {
	ReleasedAt  *time.Time `json:"released_at"`
	ID          string     `json:"id"`
	TaskLeaseID string     `json:"task_lease_id"`
	WorkerID    string     `json:"worker_id"`
}

func (q *Queries) ReleaseTaskCredentialLease(ctx context.Context, arg ReleaseTaskCredentialLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseTaskCredentialLease,
		arg.ReleasedAt,
		arg.ID,
		arg.TaskLeaseID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewTaskCredentialLease = `-- name: RenewTaskCredentialLease :one
UPDATE workos_core.task_credential_leases
SET expires_at = $1
WHERE id = $2 AND task_lease_id = $3 AND worker_id = $4
  AND status = 'active' AND expires_at >= $5
RETURNING id, task_lease_id, task_id, worker_id, owner_user_id, consumer_id, purpose,
          credential_id, credential_revision, status, expires_at
`

type RenewTaskCredentialLeaseParams struct {
	ExpiresAt   time.Time `json:"expires_at"`
	ID          string    `json:"id"`
	TaskLeaseID string    `json:"task_lease_id"`
	WorkerID    string    `json:"worker_id"`
	ExpiresAt_2 time.Time `json:"expires_at_2"`
}

type RenewTaskCredentialLeaseRow struct {
	ID                 string    `json:"id"`
	TaskLeaseID        string    `json:"task_lease_id"`
	TaskID             string    `json:"task_id"`
	WorkerID           string    `json:"worker_id"`
	OwnerUserID        string    `json:"owner_user_id"`
	ConsumerID         string    `json:"consumer_id"`
	Purpose            string    `json:"purpose"`
	CredentialID       string    `json:"credential_id"`
	CredentialRevision int64     `json:"credential_revision"`
	Status             string    `json:"status"`
	ExpiresAt          time.Time `json:"expires_at"`
}

func (q *Queries) RenewTaskCredentialLease(ctx context.Context, arg RenewTaskCredentialLeaseParams) (RenewTaskCredentialLeaseRow, error) {
	row := q.db.QueryRow(ctx, renewTaskCredentialLease,
		arg.ExpiresAt,
		arg.ID,
		arg.TaskLeaseID,
		arg.WorkerID,
		arg.ExpiresAt_2,
	)
	var i RenewTaskCredentialLeaseRow
	err := row.Scan(
		&i.ID,
		&i.TaskLeaseID,
		&i.TaskID,
		&i.WorkerID,
		&i.OwnerUserID,
		&i.ConsumerID,
		&i.Purpose,
		&i.CredentialID,
		&i.CredentialRevision,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeProviderCredential = `-- name: RevokeProviderCredential :execrows
UPDATE workos_core.provider_credentials
SET status = 'revoked', revision = $1, updated_at = $2
WHERE id = $3
`

type RevokeProviderCredentialParams struct {
	Revision  int64     `json:"revision"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) RevokeProviderCredential(ctx context.Context, arg RevokeProviderCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeProviderCredential, arg.Revision, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateVaultState = `-- name: RotateVaultState :execrows
UPDATE workos_core.credential_vault_state
SET current_epoch = $1, updated_at = $2
WHERE singleton AND current_epoch = $3
`

type RotateVaultStateParams struct {
	CurrentEpoch   int64     `json:"current_epoch"`
	UpdatedAt      time.Time `json:"updated_at"`
	CurrentEpoch_2 int64     `json:"current_epoch_2"`
}

func (q *Queries) RotateVaultState(ctx context.Context, arg RotateVaultStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateVaultState, arg.CurrentEpoch, arg.UpdatedAt, arg.CurrentEpoch_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCredentialMaterial = `-- name: UpdateCredentialMaterial :execrows
UPDATE workos_core.provider_credentials
SET label = $1, revision = $2, nonce = $3, ciphertext = $4, key_epoch = $5, updated_at = $6
WHERE id = $7
`

type UpdateCredentialMaterialParams struct {
	Label      string    `json:"label"`
	Revision   int64     `json:"revision"`
	Nonce      []byte    `json:"nonce"`
	Ciphertext []byte    `json:"ciphertext"`
	KeyEpoch   int64     `json:"key_epoch"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         string    `json:"id"`
}

func (q *Queries) UpdateCredentialMaterial(ctx context.Context, arg UpdateCredentialMaterialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCredentialMaterial,
		arg.Label,
		arg.Revision,
		arg.Nonce,
		arg.Ciphertext,
		arg.KeyEpoch,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCredentialSeal = `-- name: UpdateCredentialSeal :execrows
UPDATE workos_core.provider_credentials
SET nonce = $1, ciphertext = $2, key_epoch = $3, updated_at = $4
WHERE id = $5
`

type UpdateCredentialSealParams struct {
	Nonce      []byte    `json:"nonce"`
	Ciphertext []byte    `json:"ciphertext"`
	KeyEpoch   int64     `json:"key_epoch"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         string    `json:"id"`
}

func (q *Queries) UpdateCredentialSeal(ctx context.Context, arg UpdateCredentialSealParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCredentialSeal,
		arg.Nonce,
		arg.Ciphertext,
		arg.KeyEpoch,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
