// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package artifactdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArtifactById = `-- name: GetArtifactById :one
SELECT id, owner_user_id, digest, format, size_bytes, file_count, state, origin, idempotency_key, app_id, task_id, job_id, incident_id, project_id, installation_id, source_bundle_id, source_digest, manifest_digest, base_image, build_command, test_command, output_directory, created_at, ready_at, updated_at FROM workos_runtime.artifacts
WHERE id = $1
`

func (q *Queries) GetArtifactById(ctx context.Context, id string) (WorkosRuntimeArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactById, id)
	var i WorkosRuntimeArtifact
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Digest,
		&i.Format,
		&i.SizeBytes,
		&i.FileCount,
		&i.State,
		&i.Origin,
		&i.IdempotencyKey,
		&i.AppID,
		&i.TaskID,
		&i.JobID,
		&i.IncidentID,
		&i.ProjectID,
		&i.InstallationID,
		&i.SourceBundleID,
		&i.SourceDigest,
		&i.ManifestDigest,
		&i.BaseImage,
		&i.BuildCommand,
		&i.TestCommand,
		&i.OutputDirectory,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByImportKey = `-- name: GetArtifactByImportKey :one
SELECT id, owner_user_id, digest, format, size_bytes, file_count, state, origin, idempotency_key, app_id, task_id, job_id, incident_id, project_id, installation_id, source_bundle_id, source_digest, manifest_digest, base_image, build_command, test_command, output_directory, created_at, ready_at, updated_at FROM workos_runtime.artifacts
WHERE owner_user_id = $1 AND origin = 'operator_import' AND idempotency_key = $2
`

type GetArtifactByImportKeyParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetArtifactByImportKey(ctx context.Context, arg GetArtifactByImportKeyParams) (WorkosRuntimeArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByImportKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosRuntimeArtifact
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Digest,
		&i.Format,
		&i.SizeBytes,
		&i.FileCount,
		&i.State,
		&i.Origin,
		&i.IdempotencyKey,
		&i.AppID,
		&i.TaskID,
		&i.JobID,
		&i.IncidentID,
		&i.ProjectID,
		&i.InstallationID,
		&i.SourceBundleID,
		&i.SourceDigest,
		&i.ManifestDigest,
		&i.BaseImage,
		&i.BuildCommand,
		&i.TestCommand,
		&i.OutputDirectory,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByOwnerDigest = `-- name: GetArtifactByOwnerDigest :one
SELECT id, owner_user_id, digest, format, size_bytes, file_count, state, origin, idempotency_key, app_id, task_id, job_id, incident_id, project_id, installation_id, source_bundle_id, source_digest, manifest_digest, base_image, build_command, test_command, output_directory, created_at, ready_at, updated_at FROM workos_runtime.artifacts
WHERE owner_user_id = $1 AND digest = $2
`

type GetArtifactByOwnerDigestParams struct {
	OwnerUserID string `json:"owner_user_id"`
	Digest      string `json:"digest"`
}

func (q *Queries) GetArtifactByOwnerDigest(ctx context.Context, arg GetArtifactByOwnerDigestParams) (WorkosRuntimeArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByOwnerDigest, arg.OwnerUserID, arg.Digest)
	var i WorkosRuntimeArtifact
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Digest,
		&i.Format,
		&i.SizeBytes,
		&i.FileCount,
		&i.State,
		&i.Origin,
		&i.IdempotencyKey,
		&i.AppID,
		&i.TaskID,
		&i.JobID,
		&i.IncidentID,
		&i.ProjectID,
		&i.InstallationID,
		&i.SourceBundleID,
		&i.SourceDigest,
		&i.ManifestDigest,
		&i.BaseImage,
		&i.BuildCommand,
		&i.TestCommand,
		&i.OutputDirectory,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactByTask = `-- name: GetArtifactByTask :one
SELECT id, owner_user_id, digest, format, size_bytes, file_count, state, origin, idempotency_key, app_id, task_id, job_id, incident_id, project_id, installation_id, source_bundle_id, source_digest, manifest_digest, base_image, build_command, test_command, output_directory, created_at, ready_at, updated_at FROM workos_runtime.artifacts
WHERE task_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetArtifactByTask(ctx context.Context, taskID pgtype.UUID) (WorkosRuntimeArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByTask, taskID)
	var i WorkosRuntimeArtifact
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Digest,
		&i.Format,
		&i.SizeBytes,
		&i.FileCount,
		&i.State,
		&i.Origin,
		&i.IdempotencyKey,
		&i.AppID,
		&i.TaskID,
		&i.JobID,
		&i.IncidentID,
		&i.ProjectID,
		&i.InstallationID,
		&i.SourceBundleID,
		&i.SourceDigest,
		&i.ManifestDigest,
		&i.BaseImage,
		&i.BuildCommand,
		&i.TestCommand,
		&i.OutputDirectory,
		&i.CreatedAt,
		&i.ReadyAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertArtifactReady = `-- name: InsertArtifactReady :one
INSERT INTO workos_runtime.artifacts (
    id, owner_user_id, digest, format, size_bytes, file_count, state, origin,
    idempotency_key, app_id, task_id, job_id, incident_id, project_id,
    installation_id, source_bundle_id, source_digest, manifest_digest,
    base_image, build_command, test_command, output_directory,
    created_at, ready_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, 'ready', $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20, $21,
    $22, $22, $22
)
ON CONFLICT (owner_user_id, digest) DO NOTHING
RETURNING id
`

type InsertArtifactReadyParams struct {
	ID              string      `json:"id"`
	OwnerUserID     string      `json:"owner_user_id"`
	Digest          string      `json:"digest"`
	Format          string      `json:"format"`
	SizeBytes       int64       `json:"size_bytes"`
	FileCount       int32       `json:"file_count"`
	Origin          string      `json:"origin"`
	IdempotencyKey  string      `json:"idempotency_key"`
	AppID           pgtype.Text `json:"app_id"`
	TaskID          pgtype.UUID `json:"task_id"`
	JobID           pgtype.UUID `json:"job_id"`
	IncidentID      pgtype.UUID `json:"incident_id"`
	ProjectID       pgtype.UUID `json:"project_id"`
	InstallationID  pgtype.UUID `json:"installation_id"`
	SourceBundleID  pgtype.UUID `json:"source_bundle_id"`
	SourceDigest    pgtype.Text `json:"source_digest"`
	ManifestDigest  pgtype.Text `json:"manifest_digest"`
	BaseImage       pgtype.Text `json:"base_image"`
	BuildCommand    []string    `json:"build_command"`
	TestCommand     []string    `json:"test_command"`
	OutputDirectory pgtype.Text `json:"output_directory"`
	CreatedAt       time.Time   `json:"created_at"`
}

func (q *Queries) InsertArtifactReady(ctx context.Context, arg InsertArtifactReadyParams) (string, error) {
	row := q.db.QueryRow(ctx, insertArtifactReady,
		arg.ID,
		arg.OwnerUserID,
		arg.Digest,
		arg.Format,
		arg.SizeBytes,
		arg.FileCount,
		arg.Origin,
		arg.IdempotencyKey,
		arg.AppID,
		arg.TaskID,
		arg.JobID,
		arg.IncidentID,
		arg.ProjectID,
		arg.InstallationID,
		arg.SourceBundleID,
		arg.SourceDigest,
		arg.ManifestDigest,
		arg.BaseImage,
		arg.BuildCommand,
		arg.TestCommand,
		arg.OutputDirectory,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listArtifactsByState = `-- name: ListArtifactsByState :many
SELECT id, owner_user_id, digest, format, size_bytes, file_count, state, origin, idempotency_key, app_id, task_id, job_id, incident_id, project_id, installation_id, source_bundle_id, source_digest, manifest_digest, base_image, build_command, test_command, output_directory, created_at, ready_at, updated_at FROM workos_runtime.artifacts
WHERE state = $1
ORDER BY created_at
`

func (q *Queries) ListArtifactsByState(ctx context.Context, state string) ([]WorkosRuntimeArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosRuntimeArtifact
	for rows.Next() {
		var i WorkosRuntimeArtifact
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Digest,
			&i.Format,
			&i.SizeBytes,
			&i.FileCount,
			&i.State,
			&i.Origin,
			&i.IdempotencyKey,
			&i.AppID,
			&i.TaskID,
			&i.JobID,
			&i.IncidentID,
			&i.ProjectID,
			&i.InstallationID,
			&i.SourceBundleID,
			&i.SourceDigest,
			&i.ManifestDigest,
			&i.BaseImage,
			&i.BuildCommand,
			&i.TestCommand,
			&i.OutputDirectory,
			&i.CreatedAt,
			&i.ReadyAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArtifactState = `-- name: MarkArtifactState :execrows
UPDATE workos_runtime.artifacts
SET state = $2, updated_at = $3
WHERE id = $1
`

type MarkArtifactStateParams struct {
	ID        string    `json:"id"`
	State     string    `json:"state"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) MarkArtifactState(ctx context.Context, arg MarkArtifactStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, markArtifactState, arg.ID, arg.State, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumOwnerArtifactBytes = `-- name: SumOwnerArtifactBytes :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint AS usage_bytes
FROM workos_runtime.artifacts
WHERE owner_user_id = $1
  AND state IN ('preparing', 'ready')
`

func (q *Queries) SumOwnerArtifactBytes(ctx context.Context, ownerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, sumOwnerArtifactBytes, ownerUserID)
	var usage_bytes int64
	err := row.Scan(&usage_bytes)
	return usage_bytes, err
}
