// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workspacedb

import (
	"context"
)

type Querier interface {
	BeginWorkspaceOperation(ctx context.Context, arg BeginWorkspaceOperationParams) (int64, error)
	CompleteWorkspaceOperation(ctx context.Context, arg CompleteWorkspaceOperationParams) (int64, error)
	GetWorkspaceOperation(ctx context.Context, operationID string) (GetWorkspaceOperationRow, error)
}

var _ Querier = (*Queries)(nil)
