// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package workspacedb

import (
	"context"
)

const beginWorkspaceOperation = `-- name: BeginWorkspaceOperation :execrows
INSERT INTO workos_runtime.workspace_operations(operation_id,owner_user_id,project_id,request_digest,state)
VALUES($1,$2,$3,$4,'pending') ON CONFLICT(operation_id) DO NOTHING
`

type BeginWorkspaceOperationParams struct {
	OperationID   string `json:"operation_id"`
	OwnerUserID   string `json:"owner_user_id"`
	ProjectID     string `json:"project_id"`
	RequestDigest string `json:"request_digest"`
}

func (q *Queries) BeginWorkspaceOperation(ctx context.Context, arg BeginWorkspaceOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginWorkspaceOperation,
		arg.OperationID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.RequestDigest,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeWorkspaceOperation = `-- name: CompleteWorkspaceOperation :execrows
UPDATE workos_runtime.workspace_operations SET state='completed',result=$4,completed_at=now()
WHERE operation_id=$1 AND owner_user_id=$2 AND request_digest=$3 AND state='pending'
`

type CompleteWorkspaceOperationParams struct {
	OperationID   string `json:"operation_id"`
	OwnerUserID   string `json:"owner_user_id"`
	RequestDigest string `json:"request_digest"`
	Result        []byte `json:"result"`
}

func (q *Queries) CompleteWorkspaceOperation(ctx context.Context, arg CompleteWorkspaceOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeWorkspaceOperation,
		arg.OperationID,
		arg.OwnerUserID,
		arg.RequestDigest,
		arg.Result,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceOperation = `-- name: GetWorkspaceOperation :one
SELECT owner_user_id,project_id,request_digest,state,result FROM workos_runtime.workspace_operations WHERE operation_id=$1
`

type GetWorkspaceOperationRow struct {
	OwnerUserID   string `json:"owner_user_id"`
	ProjectID     string `json:"project_id"`
	RequestDigest string `json:"request_digest"`
	State         string `json:"state"`
	Result        []byte `json:"result"`
}

func (q *Queries) GetWorkspaceOperation(ctx context.Context, operationID string) (GetWorkspaceOperationRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceOperation, operationID)
	var i GetWorkspaceOperationRow
	err := row.Scan(
		&i.OwnerUserID,
		&i.ProjectID,
		&i.RequestDigest,
		&i.State,
		&i.Result,
	)
	return i, err
}
