// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package surfacedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSurfaceAttachmentControl = `-- name: ClearSurfaceAttachmentControl :execrows
UPDATE workos_runtime.surface_attachments
SET controls = false
WHERE owner_user_id = $1
  AND attachment_id = $2
  AND control_generation <= $3
`

type ClearSurfaceAttachmentControlParams struct {
	OwnerUserID       string `json:"owner_user_id"`
	AttachmentID      string `json:"attachment_id"`
	ControlGeneration int64  `json:"control_generation"`
}

func (q *Queries) ClearSurfaceAttachmentControl(ctx context.Context, arg ClearSurfaceAttachmentControlParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearSurfaceAttachmentControl, arg.OwnerUserID, arg.AttachmentID, arg.ControlGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeSession = `-- name: CloseSession :execrows
UPDATE workos_runtime.surface_sessions
SET closed_at = $4,
    bridge_token_hash = NULL
WHERE owner_user_id = $1 AND device_id = $2 AND id = $3 AND closed_at IS NULL
`

type CloseSessionParams struct {
	OwnerUserID string             `json:"owner_user_id"`
	DeviceID    string             `json:"device_id"`
	ID          string             `json:"id"`
	Now         pgtype.Timestamptz `json:"now"`
}

func (q *Queries) CloseSession(ctx context.Context, arg CloseSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeSession,
		arg.OwnerUserID,
		arg.DeviceID,
		arg.ID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countLiveSurfaceAttachments = `-- name: CountLiveSurfaceAttachments :many
SELECT workload_id::text AS workload_id, count(*)::int AS live_attachments
FROM workos_runtime.surface_attachments
WHERE owner_user_id = $1 AND project_id = $2 AND state = 'attached'
GROUP BY workload_id
`

type CountLiveSurfaceAttachmentsParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ProjectID   string `json:"project_id"`
}

type CountLiveSurfaceAttachmentsRow struct {
	WorkloadID      string `json:"workload_id"`
	LiveAttachments int32  `json:"live_attachments"`
}

func (q *Queries) CountLiveSurfaceAttachments(ctx context.Context, arg CountLiveSurfaceAttachmentsParams) ([]CountLiveSurfaceAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, countLiveSurfaceAttachments, arg.OwnerUserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountLiveSurfaceAttachmentsRow
	for rows.Next() {
		var i CountLiveSurfaceAttachmentsRow
		if err := rows.Scan(&i.WorkloadID, &i.LiveAttachments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const detachSurfaceAttachment = `-- name: DetachSurfaceAttachment :execrows
UPDATE workos_runtime.surface_attachments
SET state = 'detached', controls = false, detached_at = $1
WHERE owner_user_id = $2
  AND attachment_id = $3
  AND state = 'attached'
`

type DetachSurfaceAttachmentParams struct {
	Now          pgtype.Timestamptz `json:"now"`
	OwnerUserID  string             `json:"owner_user_id"`
	AttachmentID string             `json:"attachment_id"`
}

func (q *Queries) DetachSurfaceAttachment(ctx context.Context, arg DetachSurfaceAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachSurfaceAttachment, arg.Now, arg.OwnerUserID, arg.AttachmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireElapsedSurfaceAttachments = `-- name: ExpireElapsedSurfaceAttachments :many
UPDATE workos_runtime.surface_attachments
SET state = 'expired', controls = false, detached_at = $1
WHERE state = 'attached'
  AND control_expires_at IS NOT NULL
  AND control_expires_at < $1
RETURNING attachment_id::text AS attachment_id
`

func (q *Queries) ExpireElapsedSurfaceAttachments(ctx context.Context, now pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, expireElapsedSurfaceAttachments, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var attachment_id string
		if err := rows.Scan(&attachment_id); err != nil {
			return nil, err
		}
		items = append(items, attachment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireSurfaceAttachmentsForWorkloads = `-- name: ExpireSurfaceAttachmentsForWorkloads :execrows
UPDATE workos_runtime.surface_attachments
SET state = 'expired', controls = false, detached_at = $1
WHERE state = 'attached'
  AND workload_id = ANY($2::uuid[])
`

type ExpireSurfaceAttachmentsForWorkloadsParams struct {
	Now         pgtype.Timestamptz `json:"now"`
	WorkloadIds []string           `json:"workload_ids"`
}

func (q *Queries) ExpireSurfaceAttachmentsForWorkloads(ctx context.Context, arg ExpireSurfaceAttachmentsForWorkloadsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireSurfaceAttachmentsForWorkloads, arg.Now, arg.WorkloadIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, owner_user_id, device_id, idempotency_key, request_digest,
       project_id, app_instance_id, renderer, app_id, app_version,
       manifest_digest, artifact_id, artifact_digest, entrypoint, path,
       workload_id, workload_generation,
       bridge_token_hash, bridge_capabilities, installation_grant_revision,
       created_at, expires_at, closed_at
FROM workos_runtime.surface_sessions
WHERE owner_user_id = $1 AND device_id = $2 AND id = $3
  AND closed_at IS NULL AND expires_at > $4
`

type GetActiveSessionParams struct {
	OwnerUserID string             `json:"owner_user_id"`
	DeviceID    string             `json:"device_id"`
	ID          string             `json:"id"`
	Now         pgtype.Timestamptz `json:"now"`
}

type GetActiveSessionRow struct {
	ID                        string             `json:"id"`
	OwnerUserID               string             `json:"owner_user_id"`
	DeviceID                  string             `json:"device_id"`
	IdempotencyKey            string             `json:"idempotency_key"`
	RequestDigest             string             `json:"request_digest"`
	ProjectID                 string             `json:"project_id"`
	AppInstanceID             string             `json:"app_instance_id"`
	Renderer                  string             `json:"renderer"`
	AppID                     string             `json:"app_id"`
	AppVersion                string             `json:"app_version"`
	ManifestDigest            string             `json:"manifest_digest"`
	ArtifactID                pgtype.UUID        `json:"artifact_id"`
	ArtifactDigest            pgtype.Text        `json:"artifact_digest"`
	Entrypoint                pgtype.Text        `json:"entrypoint"`
	Path                      string             `json:"path"`
	WorkloadID                pgtype.UUID        `json:"workload_id"`
	WorkloadGeneration        pgtype.Int8        `json:"workload_generation"`
	BridgeTokenHash           pgtype.Text        `json:"bridge_token_hash"`
	BridgeCapabilities        []string           `json:"bridge_capabilities"`
	InstallationGrantRevision int64              `json:"installation_grant_revision"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	ClosedAt                  pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession,
		arg.OwnerUserID,
		arg.DeviceID,
		arg.ID,
		arg.Now,
	)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.ProjectID,
		&i.AppInstanceID,
		&i.Renderer,
		&i.AppID,
		&i.AppVersion,
		&i.ManifestDigest,
		&i.ArtifactID,
		&i.ArtifactDigest,
		&i.Entrypoint,
		&i.Path,
		&i.WorkloadID,
		&i.WorkloadGeneration,
		&i.BridgeTokenHash,
		&i.BridgeCapabilities,
		&i.InstallationGrantRevision,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
	)
	return i, err
}

const getActiveSessionByBridgeToken = `-- name: GetActiveSessionByBridgeToken :one
SELECT id, owner_user_id, device_id, idempotency_key, request_digest,
       project_id, app_instance_id, renderer, app_id, app_version,
       manifest_digest, artifact_id, artifact_digest, entrypoint, path,
       workload_id, workload_generation,
       bridge_token_hash, bridge_capabilities, installation_grant_revision,
       created_at, expires_at, closed_at
FROM workos_runtime.surface_sessions
WHERE owner_user_id = $1
  AND bridge_token_hash = $2
  AND closed_at IS NULL
  AND expires_at > $3
`

type GetActiveSessionByBridgeTokenParams struct {
	OwnerUserID string             `json:"owner_user_id"`
	TokenHash   pgtype.Text        `json:"token_hash"`
	Now         pgtype.Timestamptz `json:"now"`
}

type GetActiveSessionByBridgeTokenRow struct {
	ID                        string             `json:"id"`
	OwnerUserID               string             `json:"owner_user_id"`
	DeviceID                  string             `json:"device_id"`
	IdempotencyKey            string             `json:"idempotency_key"`
	RequestDigest             string             `json:"request_digest"`
	ProjectID                 string             `json:"project_id"`
	AppInstanceID             string             `json:"app_instance_id"`
	Renderer                  string             `json:"renderer"`
	AppID                     string             `json:"app_id"`
	AppVersion                string             `json:"app_version"`
	ManifestDigest            string             `json:"manifest_digest"`
	ArtifactID                pgtype.UUID        `json:"artifact_id"`
	ArtifactDigest            pgtype.Text        `json:"artifact_digest"`
	Entrypoint                pgtype.Text        `json:"entrypoint"`
	Path                      string             `json:"path"`
	WorkloadID                pgtype.UUID        `json:"workload_id"`
	WorkloadGeneration        pgtype.Int8        `json:"workload_generation"`
	BridgeTokenHash           pgtype.Text        `json:"bridge_token_hash"`
	BridgeCapabilities        []string           `json:"bridge_capabilities"`
	InstallationGrantRevision int64              `json:"installation_grant_revision"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	ClosedAt                  pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) GetActiveSessionByBridgeToken(ctx context.Context, arg GetActiveSessionByBridgeTokenParams) (GetActiveSessionByBridgeTokenRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByBridgeToken, arg.OwnerUserID, arg.TokenHash, arg.Now)
	var i GetActiveSessionByBridgeTokenRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.ProjectID,
		&i.AppInstanceID,
		&i.Renderer,
		&i.AppID,
		&i.AppVersion,
		&i.ManifestDigest,
		&i.ArtifactID,
		&i.ArtifactDigest,
		&i.Entrypoint,
		&i.Path,
		&i.WorkloadID,
		&i.WorkloadGeneration,
		&i.BridgeTokenHash,
		&i.BridgeCapabilities,
		&i.InstallationGrantRevision,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
	)
	return i, err
}

const getControllerAttachment = `-- name: GetControllerAttachment :one
SELECT attachment_id, workload_id, surface_session_id, owner_user_id, project_id,
       device_id, idempotency_key, controls, control_generation, state,
       attached_at, control_expires_at, detached_at
FROM workos_runtime.surface_attachments
WHERE owner_user_id = $1 AND attachment_id = $2 AND device_id = $3
`

type GetControllerAttachmentParams struct {
	OwnerUserID  string `json:"owner_user_id"`
	AttachmentID string `json:"attachment_id"`
	DeviceID     string `json:"device_id"`
}

func (q *Queries) GetControllerAttachment(ctx context.Context, arg GetControllerAttachmentParams) (WorkosRuntimeSurfaceAttachment, error) {
	row := q.db.QueryRow(ctx, getControllerAttachment, arg.OwnerUserID, arg.AttachmentID, arg.DeviceID)
	var i WorkosRuntimeSurfaceAttachment
	err := row.Scan(
		&i.AttachmentID,
		&i.WorkloadID,
		&i.SurfaceSessionID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.Controls,
		&i.ControlGeneration,
		&i.State,
		&i.AttachedAt,
		&i.ControlExpiresAt,
		&i.DetachedAt,
	)
	return i, err
}

const getLiveAttachmentBySurfaceSession = `-- name: GetLiveAttachmentBySurfaceSession :one
SELECT attachment_id, workload_id, surface_session_id, owner_user_id, project_id,
       device_id, idempotency_key, controls, control_generation, state,
       attached_at, control_expires_at, detached_at
FROM workos_runtime.surface_attachments
WHERE owner_user_id = $1 AND surface_session_id = $2 AND device_id = $3
  AND state = 'attached'
ORDER BY attached_at DESC
LIMIT 1
`

type GetLiveAttachmentBySurfaceSessionParams struct {
	OwnerUserID      string `json:"owner_user_id"`
	SurfaceSessionID string `json:"surface_session_id"`
	DeviceID         string `json:"device_id"`
}

func (q *Queries) GetLiveAttachmentBySurfaceSession(ctx context.Context, arg GetLiveAttachmentBySurfaceSessionParams) (WorkosRuntimeSurfaceAttachment, error) {
	row := q.db.QueryRow(ctx, getLiveAttachmentBySurfaceSession, arg.OwnerUserID, arg.SurfaceSessionID, arg.DeviceID)
	var i WorkosRuntimeSurfaceAttachment
	err := row.Scan(
		&i.AttachmentID,
		&i.WorkloadID,
		&i.SurfaceSessionID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.Controls,
		&i.ControlGeneration,
		&i.State,
		&i.AttachedAt,
		&i.ControlExpiresAt,
		&i.DetachedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, owner_user_id, device_id, idempotency_key, request_digest,
       project_id, app_instance_id, renderer, app_id, app_version,
       manifest_digest, artifact_id, artifact_digest, entrypoint, path,
       workload_id, workload_generation,
       bridge_token_hash, bridge_capabilities, installation_grant_revision,
       created_at, expires_at, closed_at
FROM workos_runtime.surface_sessions
WHERE owner_user_id = $1 AND device_id = $2 AND id = $3
`

type GetSessionParams struct {
	OwnerUserID string `json:"owner_user_id"`
	DeviceID    string `json:"device_id"`
	ID          string `json:"id"`
}

type GetSessionRow struct {
	ID                        string             `json:"id"`
	OwnerUserID               string             `json:"owner_user_id"`
	DeviceID                  string             `json:"device_id"`
	IdempotencyKey            string             `json:"idempotency_key"`
	RequestDigest             string             `json:"request_digest"`
	ProjectID                 string             `json:"project_id"`
	AppInstanceID             string             `json:"app_instance_id"`
	Renderer                  string             `json:"renderer"`
	AppID                     string             `json:"app_id"`
	AppVersion                string             `json:"app_version"`
	ManifestDigest            string             `json:"manifest_digest"`
	ArtifactID                pgtype.UUID        `json:"artifact_id"`
	ArtifactDigest            pgtype.Text        `json:"artifact_digest"`
	Entrypoint                pgtype.Text        `json:"entrypoint"`
	Path                      string             `json:"path"`
	WorkloadID                pgtype.UUID        `json:"workload_id"`
	WorkloadGeneration        pgtype.Int8        `json:"workload_generation"`
	BridgeTokenHash           pgtype.Text        `json:"bridge_token_hash"`
	BridgeCapabilities        []string           `json:"bridge_capabilities"`
	InstallationGrantRevision int64              `json:"installation_grant_revision"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	ClosedAt                  pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.OwnerUserID, arg.DeviceID, arg.ID)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.ProjectID,
		&i.AppInstanceID,
		&i.Renderer,
		&i.AppID,
		&i.AppVersion,
		&i.ManifestDigest,
		&i.ArtifactID,
		&i.ArtifactDigest,
		&i.Entrypoint,
		&i.Path,
		&i.WorkloadID,
		&i.WorkloadGeneration,
		&i.BridgeTokenHash,
		&i.BridgeCapabilities,
		&i.InstallationGrantRevision,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
	)
	return i, err
}

const getSessionRequest = `-- name: GetSessionRequest :one
SELECT owner_user_id, idempotency_key, request_digest, session_id, created_at
FROM workos_runtime.surface_session_requests
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetSessionRequestParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetSessionRequest(ctx context.Context, arg GetSessionRequestParams) (WorkosRuntimeSurfaceSessionRequest, error) {
	row := q.db.QueryRow(ctx, getSessionRequest, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosRuntimeSurfaceSessionRequest
	err := row.Scan(
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getSurfaceAttachment = `-- name: GetSurfaceAttachment :one
SELECT attachment_id, workload_id, surface_session_id, owner_user_id, project_id,
       device_id, idempotency_key, controls, control_generation, state,
       attached_at, control_expires_at, detached_at
FROM workos_runtime.surface_attachments
WHERE owner_user_id = $1 AND attachment_id = $2
`

type GetSurfaceAttachmentParams struct {
	OwnerUserID  string `json:"owner_user_id"`
	AttachmentID string `json:"attachment_id"`
}

func (q *Queries) GetSurfaceAttachment(ctx context.Context, arg GetSurfaceAttachmentParams) (WorkosRuntimeSurfaceAttachment, error) {
	row := q.db.QueryRow(ctx, getSurfaceAttachment, arg.OwnerUserID, arg.AttachmentID)
	var i WorkosRuntimeSurfaceAttachment
	err := row.Scan(
		&i.AttachmentID,
		&i.WorkloadID,
		&i.SurfaceSessionID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.Controls,
		&i.ControlGeneration,
		&i.State,
		&i.AttachedAt,
		&i.ControlExpiresAt,
		&i.DetachedAt,
	)
	return i, err
}

const getSurfaceAttachmentByKey = `-- name: GetSurfaceAttachmentByKey :one
SELECT attachment_id, workload_id, surface_session_id, owner_user_id, project_id,
       device_id, idempotency_key, controls, control_generation, state,
       attached_at, control_expires_at, detached_at
FROM workos_runtime.surface_attachments
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetSurfaceAttachmentByKeyParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetSurfaceAttachmentByKey(ctx context.Context, arg GetSurfaceAttachmentByKeyParams) (WorkosRuntimeSurfaceAttachment, error) {
	row := q.db.QueryRow(ctx, getSurfaceAttachmentByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosRuntimeSurfaceAttachment
	err := row.Scan(
		&i.AttachmentID,
		&i.WorkloadID,
		&i.SurfaceSessionID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.Controls,
		&i.ControlGeneration,
		&i.State,
		&i.AttachedAt,
		&i.ControlExpiresAt,
		&i.DetachedAt,
	)
	return i, err
}

const getSurfaceControlLease = `-- name: GetSurfaceControlLease :one
SELECT workload_id, owner_user_id, control_generation, controller_attachment_id,
       controller_device_id, granted_at, expires_at
FROM workos_runtime.surface_control_leases
WHERE workload_id = $1
`

func (q *Queries) GetSurfaceControlLease(ctx context.Context, workloadID string) (WorkosRuntimeSurfaceControlLease, error) {
	row := q.db.QueryRow(ctx, getSurfaceControlLease, workloadID)
	var i WorkosRuntimeSurfaceControlLease
	err := row.Scan(
		&i.WorkloadID,
		&i.OwnerUserID,
		&i.ControlGeneration,
		&i.ControllerAttachmentID,
		&i.ControllerDeviceID,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const hasActiveSessionForInstance = `-- name: HasActiveSessionForInstance :one
SELECT EXISTS (
    SELECT 1 FROM workos_runtime.surface_sessions
    WHERE owner_user_id = $1
      AND app_instance_id = $2
      AND closed_at IS NULL
      AND expires_at > $3
) AS has_active
`

type HasActiveSessionForInstanceParams struct {
	OwnerUserID   string             `json:"owner_user_id"`
	AppInstanceID string             `json:"app_instance_id"`
	Now           pgtype.Timestamptz `json:"now"`
}

// The idle-TTL source for the Workload Manager: whether any open, unexpired
// session still references the installed instance.
func (q *Queries) HasActiveSessionForInstance(ctx context.Context, arg HasActiveSessionForInstanceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSessionForInstance, arg.OwnerUserID, arg.AppInstanceID, arg.Now)
	var has_active bool
	err := row.Scan(&has_active)
	return has_active, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO workos_runtime.surface_sessions (
    id, owner_user_id, device_id, idempotency_key, request_digest,
    project_id, app_instance_id, renderer, app_id, app_version,
    manifest_digest, artifact_id, artifact_digest, entrypoint, path,
    workload_id, workload_generation,
    bridge_token_hash, bridge_capabilities, installation_grant_revision,
    created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
`

type InsertSessionParams struct {
	ID                        string             `json:"id"`
	OwnerUserID               string             `json:"owner_user_id"`
	DeviceID                  string             `json:"device_id"`
	IdempotencyKey            string             `json:"idempotency_key"`
	RequestDigest             string             `json:"request_digest"`
	ProjectID                 string             `json:"project_id"`
	AppInstanceID             string             `json:"app_instance_id"`
	Renderer                  string             `json:"renderer"`
	AppID                     string             `json:"app_id"`
	AppVersion                string             `json:"app_version"`
	ManifestDigest            string             `json:"manifest_digest"`
	ArtifactID                pgtype.UUID        `json:"artifact_id"`
	ArtifactDigest            pgtype.Text        `json:"artifact_digest"`
	Entrypoint                pgtype.Text        `json:"entrypoint"`
	Path                      string             `json:"path"`
	WorkloadID                pgtype.UUID        `json:"workload_id"`
	WorkloadGeneration        pgtype.Int8        `json:"workload_generation"`
	BridgeTokenHash           pgtype.Text        `json:"bridge_token_hash"`
	BridgeCapabilities        []string           `json:"bridge_capabilities"`
	InstallationGrantRevision int64              `json:"installation_grant_revision"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
}

// installation_grant_revision is the create-time grant epoch Core's private
// resolver returned for this session; the application must always pass the
// resolved value, never a constant, so a session created after a SetAppGrants
// mutation pins the epoch the user re-opened under.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.OwnerUserID,
		arg.DeviceID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.ProjectID,
		arg.AppInstanceID,
		arg.Renderer,
		arg.AppID,
		arg.AppVersion,
		arg.ManifestDigest,
		arg.ArtifactID,
		arg.ArtifactDigest,
		arg.Entrypoint,
		arg.Path,
		arg.WorkloadID,
		arg.WorkloadGeneration,
		arg.BridgeTokenHash,
		arg.BridgeCapabilities,
		arg.InstallationGrantRevision,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertSessionRequest = `-- name: InsertSessionRequest :execrows
INSERT INTO workos_runtime.surface_session_requests (
    owner_user_id, idempotency_key, request_digest, session_id, created_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertSessionRequestParams struct {
	OwnerUserID    string             `json:"owner_user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestDigest  string             `json:"request_digest"`
	SessionID      string             `json:"session_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertSessionRequest(ctx context.Context, arg InsertSessionRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSessionRequest,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.SessionID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSurfaceAttachment = `-- name: InsertSurfaceAttachment :execrows

INSERT INTO workos_runtime.surface_attachments (
    attachment_id, workload_id, surface_session_id, owner_user_id, project_id,
    device_id, idempotency_key, controls, control_generation, state,
    attached_at, control_expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (owner_user_id, idempotency_key) DO NOTHING
`

type InsertSurfaceAttachmentParams struct {
	AttachmentID      string             `json:"attachment_id"`
	WorkloadID        string             `json:"workload_id"`
	SurfaceSessionID  string             `json:"surface_session_id"`
	OwnerUserID       string             `json:"owner_user_id"`
	ProjectID         string             `json:"project_id"`
	DeviceID          string             `json:"device_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	Controls          bool               `json:"controls"`
	ControlGeneration int64              `json:"control_generation"`
	State             string             `json:"state"`
	AttachedAt        pgtype.Timestamptz `json:"attached_at"`
	ControlExpiresAt  pgtype.Timestamptz `json:"control_expires_at"`
}

// Surface continuity facts (ADR-0031, migration 059): attachments are
// per-device access relations to supervised interactive workloads; control is
// a single-controller epoch advanced only by the explicit takeover RPC.
func (q *Queries) InsertSurfaceAttachment(ctx context.Context, arg InsertSurfaceAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSurfaceAttachment,
		arg.AttachmentID,
		arg.WorkloadID,
		arg.SurfaceSessionID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.DeviceID,
		arg.IdempotencyKey,
		arg.Controls,
		arg.ControlGeneration,
		arg.State,
		arg.AttachedAt,
		arg.ControlExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSurfaceControlLease = `-- name: InsertSurfaceControlLease :exec
INSERT INTO workos_runtime.surface_control_leases (
    workload_id, owner_user_id, control_generation, controller_attachment_id,
    controller_device_id, granted_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSurfaceControlLeaseParams struct {
	WorkloadID             string             `json:"workload_id"`
	OwnerUserID            string             `json:"owner_user_id"`
	ControlGeneration      int64              `json:"control_generation"`
	ControllerAttachmentID string             `json:"controller_attachment_id"`
	ControllerDeviceID     string             `json:"controller_device_id"`
	GrantedAt              pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertSurfaceControlLease(ctx context.Context, arg InsertSurfaceControlLeaseParams) error {
	_, err := q.db.Exec(ctx, insertSurfaceControlLease,
		arg.WorkloadID,
		arg.OwnerUserID,
		arg.ControlGeneration,
		arg.ControllerAttachmentID,
		arg.ControllerDeviceID,
		arg.GrantedAt,
		arg.ExpiresAt,
	)
	return err
}

const listLiveSurfaceAttachmentWorkloads = `-- name: ListLiveSurfaceAttachmentWorkloads :many
SELECT DISTINCT workload_id::text AS workload_id, owner_user_id::text AS owner_user_id
FROM workos_runtime.surface_attachments
WHERE state = 'attached'
`

type ListLiveSurfaceAttachmentWorkloadsRow struct {
	WorkloadID  string `json:"workload_id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) ListLiveSurfaceAttachmentWorkloads(ctx context.Context) ([]ListLiveSurfaceAttachmentWorkloadsRow, error) {
	rows, err := q.db.Query(ctx, listLiveSurfaceAttachmentWorkloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveSurfaceAttachmentWorkloadsRow
	for rows.Next() {
		var i ListLiveSurfaceAttachmentWorkloadsRow
		if err := rows.Scan(&i.WorkloadID, &i.OwnerUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSurfaceControlLease = `-- name: LockSurfaceControlLease :one
SELECT workload_id, owner_user_id, control_generation, controller_attachment_id,
       controller_device_id, granted_at, expires_at
FROM workos_runtime.surface_control_leases
WHERE workload_id = $1
FOR UPDATE
`

func (q *Queries) LockSurfaceControlLease(ctx context.Context, workloadID string) (WorkosRuntimeSurfaceControlLease, error) {
	row := q.db.QueryRow(ctx, lockSurfaceControlLease, workloadID)
	var i WorkosRuntimeSurfaceControlLease
	err := row.Scan(
		&i.WorkloadID,
		&i.OwnerUserID,
		&i.ControlGeneration,
		&i.ControllerAttachmentID,
		&i.ControllerDeviceID,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markSurfaceAttachmentControl = `-- name: MarkSurfaceAttachmentControl :execrows
UPDATE workos_runtime.surface_attachments
SET controls = $1,
    control_generation = $2,
    control_expires_at = $3
WHERE owner_user_id = $4
  AND attachment_id = $5
`

type MarkSurfaceAttachmentControlParams struct {
	Controls          bool               `json:"controls"`
	ControlGeneration int64              `json:"control_generation"`
	ControlExpiresAt  pgtype.Timestamptz `json:"control_expires_at"`
	OwnerUserID       string             `json:"owner_user_id"`
	AttachmentID      string             `json:"attachment_id"`
}

func (q *Queries) MarkSurfaceAttachmentControl(ctx context.Context, arg MarkSurfaceAttachmentControlParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSurfaceAttachmentControl,
		arg.Controls,
		arg.ControlGeneration,
		arg.ControlExpiresAt,
		arg.OwnerUserID,
		arg.AttachmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionBridgeToken = `-- name: RotateSessionBridgeToken :one
UPDATE workos_runtime.surface_sessions
SET bridge_token_hash = $1
WHERE owner_user_id = $2
  AND device_id = $3
  AND id = $4
  AND closed_at IS NULL
  AND expires_at > $5
RETURNING id, owner_user_id, device_id, idempotency_key, request_digest,
          project_id, app_instance_id, renderer, app_id, app_version,
          manifest_digest, artifact_id, artifact_digest, entrypoint, path,
          workload_id, workload_generation,
          bridge_token_hash, bridge_capabilities, installation_grant_revision,
          created_at, expires_at, closed_at
`

type RotateSessionBridgeTokenParams struct {
	TokenHash   pgtype.Text        `json:"token_hash"`
	OwnerUserID string             `json:"owner_user_id"`
	DeviceID    string             `json:"device_id"`
	SessionID   string             `json:"session_id"`
	Now         pgtype.Timestamptz `json:"now"`
}

type RotateSessionBridgeTokenRow struct {
	ID                        string             `json:"id"`
	OwnerUserID               string             `json:"owner_user_id"`
	DeviceID                  string             `json:"device_id"`
	IdempotencyKey            string             `json:"idempotency_key"`
	RequestDigest             string             `json:"request_digest"`
	ProjectID                 string             `json:"project_id"`
	AppInstanceID             string             `json:"app_instance_id"`
	Renderer                  string             `json:"renderer"`
	AppID                     string             `json:"app_id"`
	AppVersion                string             `json:"app_version"`
	ManifestDigest            string             `json:"manifest_digest"`
	ArtifactID                pgtype.UUID        `json:"artifact_id"`
	ArtifactDigest            pgtype.Text        `json:"artifact_digest"`
	Entrypoint                pgtype.Text        `json:"entrypoint"`
	Path                      string             `json:"path"`
	WorkloadID                pgtype.UUID        `json:"workload_id"`
	WorkloadGeneration        pgtype.Int8        `json:"workload_generation"`
	BridgeTokenHash           pgtype.Text        `json:"bridge_token_hash"`
	BridgeCapabilities        []string           `json:"bridge_capabilities"`
	InstallationGrantRevision int64              `json:"installation_grant_revision"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	ExpiresAt                 pgtype.Timestamptz `json:"expires_at"`
	ClosedAt                  pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) RotateSessionBridgeToken(ctx context.Context, arg RotateSessionBridgeTokenParams) (RotateSessionBridgeTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateSessionBridgeToken,
		arg.TokenHash,
		arg.OwnerUserID,
		arg.DeviceID,
		arg.SessionID,
		arg.Now,
	)
	var i RotateSessionBridgeTokenRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.DeviceID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.ProjectID,
		&i.AppInstanceID,
		&i.Renderer,
		&i.AppID,
		&i.AppVersion,
		&i.ManifestDigest,
		&i.ArtifactID,
		&i.ArtifactDigest,
		&i.Entrypoint,
		&i.Path,
		&i.WorkloadID,
		&i.WorkloadGeneration,
		&i.BridgeTokenHash,
		&i.BridgeCapabilities,
		&i.InstallationGrantRevision,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateSurfaceControlLease = `-- name: UpdateSurfaceControlLease :exec
UPDATE workos_runtime.surface_control_leases
SET control_generation = $2,
    controller_attachment_id = $3,
    controller_device_id = $4,
    granted_at = $5,
    expires_at = $6
WHERE workload_id = $1
`

type UpdateSurfaceControlLeaseParams struct {
	WorkloadID             string             `json:"workload_id"`
	ControlGeneration      int64              `json:"control_generation"`
	ControllerAttachmentID string             `json:"controller_attachment_id"`
	ControllerDeviceID     string             `json:"controller_device_id"`
	GrantedAt              pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateSurfaceControlLease(ctx context.Context, arg UpdateSurfaceControlLeaseParams) error {
	_, err := q.db.Exec(ctx, updateSurfaceControlLease,
		arg.WorkloadID,
		arg.ControlGeneration,
		arg.ControllerAttachmentID,
		arg.ControllerDeviceID,
		arg.GrantedAt,
		arg.ExpiresAt,
	)
	return err
}
