// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package surfacedb

import (
	"context"
)

type Querier interface {
	CloseSession(ctx context.Context, arg CloseSessionParams) (int64, error)
	GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (WorkosRuntimeSurfaceSession, error)
	GetSession(ctx context.Context, arg GetSessionParams) (WorkosRuntimeSurfaceSession, error)
	GetSessionRequest(ctx context.Context, arg GetSessionRequestParams) (WorkosRuntimeSurfaceSessionRequest, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	InsertSessionRequest(ctx context.Context, arg InsertSessionRequestParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
