// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package notificationdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// owner: workos-core Notification; durable owner-scoped notification facts
type WorkosCoreNotification struct {
	ID                 string
	OwnerUserID        string
	ProjectID          pgtype.UUID
	Kind               string
	Severity           string
	Origin             string
	Title              string
	Body               string
	TargetKind         string
	TargetID           string
	AppID              pgtype.Text
	AppInstallationID  pgtype.UUID
	SourceProcess      string
	SourceID           string
	SourceDigest       string
	CreatedAt          time.Time
	ReadAt             *time.Time
	ReadChangeSequence int64
	// owner: workos-core Notification; immutable CREATED revision for snapshots
	CreatedChangeSequence int64
}

// owner: core; owner-level quiet hours evaluated server-side before dispatch
type WorkosCorePushPreference struct {
	OwnerUserID   string
	QuietEnabled  bool
	QuietStartUtc string
	QuietEndUtc   string
	UpdatedAt     time.Time
}

// owner: core; device push wake registrations; relay sees notification ids only (ADR-0018)
type WorkosCorePushSubscription struct {
	OwnerUserID string
	DeviceID    string
	Platform    string
	Endpoint    string
	P256dh      string
	AuthSecret  string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
