// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package notificationdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceOwnerSweptThrough = `-- name: AdvanceOwnerSweptThrough :execrows
UPDATE workos_core.notification_owner_sequences
SET swept_through = GREATEST(swept_through, $1), updated_at = $2
WHERE owner_user_id = $3
`

type AdvanceOwnerSweptThroughParams struct {
	SweptThrough int64
	UpdatedAt    time.Time
	OwnerUserID  string
}

func (q *Queries) AdvanceOwnerSweptThrough(ctx context.Context, arg AdvanceOwnerSweptThroughParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceOwnerSweptThrough, arg.SweptThrough, arg.UpdatedAt, arg.OwnerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const allocateNotificationChangeSequence = `-- name: AllocateNotificationChangeSequence :one

INSERT INTO workos_core.notification_owner_sequences (
    owner_user_id, last_sequence, swept_through, updated_at
) VALUES (
    $1, 1, 0, $2
)
ON CONFLICT (owner_user_id) DO UPDATE
SET last_sequence = workos_core.notification_owner_sequences.last_sequence + 1,
    updated_at = EXCLUDED.updated_at
RETURNING last_sequence
`

type AllocateNotificationChangeSequenceParams struct {
	OwnerUserID string
	UpdatedAt   time.Time
}

// Core notification facts (ADR-0014, migration 029). Every statement here
// touches only the workos_core notification tables; other modules are
// reached through their owning modules' ports.
func (q *Queries) AllocateNotificationChangeSequence(ctx context.Context, arg AllocateNotificationChangeSequenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateNotificationChangeSequence, arg.OwnerUserID, arg.UpdatedAt)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const countOwnerUnread = `-- name: CountOwnerUnread :one
SELECT count(*) FROM workos_core.notifications
WHERE owner_user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountOwnerUnread(ctx context.Context, ownerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerUnread, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNotificationChangesFor = `-- name: DeleteNotificationChangesFor :execrows
DELETE FROM workos_core.notification_changes
WHERE notification_id = ANY ($1::uuid[])
`

func (q *Queries) DeleteNotificationChangesFor(ctx context.Context, ids []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationChangesFor, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteNotifications = `-- name: DeleteNotifications :execrows
DELETE FROM workos_core.notifications
WHERE id = ANY ($1::uuid[])
`

func (q *Queries) DeleteNotifications(ctx context.Context, ids []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotifications, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldSourceReceipts = `-- name: DeleteOldSourceReceipts :execrows
DELETE FROM workos_core.notification_source_receipts
WHERE recorded_at < $1
`

// Receipts outlive notifications (longer horizon, same bounded sweep) so a
// pathological late replay can never project a second notification.
func (q *Queries) DeleteOldSourceReceipts(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldSourceReceipts, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChangesAfter = `-- name: GetChangesAfter :many
SELECT c.change_sequence, c.notification_id, c.change_type, c.revision,
       n.project_id, n.kind, n.severity, n.origin, n.title, n.body,
       n.target_kind, n.target_id, n.app_id, n.app_installation_id,
       n.source_process, n.source_id, n.source_digest, n.created_at,
       n.created_change_sequence, n.read_at,
       n.read_change_sequence
FROM workos_core.notification_changes AS c
JOIN workos_core.notifications AS n
  ON n.id = c.notification_id AND n.owner_user_id = c.owner_user_id
WHERE c.owner_user_id = $1
  AND c.change_sequence > $2
ORDER BY c.change_sequence
LIMIT $3
`

type GetChangesAfterParams struct {
	OwnerUserID   string
	AfterSequence int64
	RowLimit      int32
}

type GetChangesAfterRow struct {
	ChangeSequence        int64
	NotificationID        string
	ChangeType            string
	Revision              int64
	ProjectID             pgtype.UUID
	Kind                  string
	Severity              string
	Origin                string
	Title                 string
	Body                  string
	TargetKind            string
	TargetID              string
	AppID                 pgtype.Text
	AppInstallationID     pgtype.UUID
	SourceProcess         string
	SourceID              string
	SourceDigest          string
	CreatedAt             time.Time
	CreatedChangeSequence int64
	ReadAt                *time.Time
	ReadChangeSequence    int64
}

func (q *Queries) GetChangesAfter(ctx context.Context, arg GetChangesAfterParams) ([]GetChangesAfterRow, error) {
	rows, err := q.db.Query(ctx, getChangesAfter, arg.OwnerUserID, arg.AfterSequence, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChangesAfterRow
	for rows.Next() {
		var i GetChangesAfterRow
		if err := rows.Scan(
			&i.ChangeSequence,
			&i.NotificationID,
			&i.ChangeType,
			&i.Revision,
			&i.ProjectID,
			&i.Kind,
			&i.Severity,
			&i.Origin,
			&i.Title,
			&i.Body,
			&i.TargetKind,
			&i.TargetID,
			&i.AppID,
			&i.AppInstallationID,
			&i.SourceProcess,
			&i.SourceID,
			&i.SourceDigest,
			&i.CreatedAt,
			&i.CreatedChangeSequence,
			&i.ReadAt,
			&i.ReadChangeSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationAppQuotaForUpdate = `-- name: GetNotificationAppQuotaForUpdate :one
SELECT utc_date, daily_count, burst_window_start, burst_count
FROM workos_core.notification_app_quotas
WHERE owner_user_id = $1
  AND app_installation_id = $2
FOR UPDATE
`

type GetNotificationAppQuotaForUpdateParams struct {
	OwnerUserID       string
	AppInstallationID string
}

type GetNotificationAppQuotaForUpdateRow struct {
	UtcDate          pgtype.Date
	DailyCount       int32
	BurstWindowStart time.Time
	BurstCount       int32
}

func (q *Queries) GetNotificationAppQuotaForUpdate(ctx context.Context, arg GetNotificationAppQuotaForUpdateParams) (GetNotificationAppQuotaForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getNotificationAppQuotaForUpdate, arg.OwnerUserID, arg.AppInstallationID)
	var i GetNotificationAppQuotaForUpdateRow
	err := row.Scan(
		&i.UtcDate,
		&i.DailyCount,
		&i.BurstWindowStart,
		&i.BurstCount,
	)
	return i, err
}

const getNotificationAppRequest = `-- name: GetNotificationAppRequest :one
SELECT request_digest, result_version, result
FROM workos_core.notification_app_requests
WHERE owner_user_id = $1
  AND app_installation_id = $2
  AND idempotency_key = $3
`

type GetNotificationAppRequestParams struct {
	OwnerUserID       string
	AppInstallationID string
	IdempotencyKey    string
}

type GetNotificationAppRequestRow struct {
	RequestDigest string
	ResultVersion int32
	Result        []byte
}

func (q *Queries) GetNotificationAppRequest(ctx context.Context, arg GetNotificationAppRequestParams) (GetNotificationAppRequestRow, error) {
	row := q.db.QueryRow(ctx, getNotificationAppRequest, arg.OwnerUserID, arg.AppInstallationID, arg.IdempotencyKey)
	var i GetNotificationAppRequestRow
	err := row.Scan(&i.RequestDigest, &i.ResultVersion, &i.Result)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, owner_user_id, project_id, kind, severity, origin, title, body,
       target_kind, target_id, app_id, app_installation_id, source_process,
       source_id, source_digest, created_at, read_at, read_change_sequence, created_change_sequence
FROM workos_core.notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id string) (WorkosCoreNotification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i WorkosCoreNotification
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.Kind,
		&i.Severity,
		&i.Origin,
		&i.Title,
		&i.Body,
		&i.TargetKind,
		&i.TargetID,
		&i.AppID,
		&i.AppInstallationID,
		&i.SourceProcess,
		&i.SourceID,
		&i.SourceDigest,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ReadChangeSequence,
		&i.CreatedChangeSequence,
	)
	return i, err
}

const getNotificationReadRequest = `-- name: GetNotificationReadRequest :one
SELECT request_digest, result_version, result
FROM workos_core.notification_read_requests
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetNotificationReadRequestParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

type GetNotificationReadRequestRow struct {
	RequestDigest string
	ResultVersion int32
	Result        []byte
}

func (q *Queries) GetNotificationReadRequest(ctx context.Context, arg GetNotificationReadRequestParams) (GetNotificationReadRequestRow, error) {
	row := q.db.QueryRow(ctx, getNotificationReadRequest, arg.OwnerUserID, arg.IdempotencyKey)
	var i GetNotificationReadRequestRow
	err := row.Scan(&i.RequestDigest, &i.ResultVersion, &i.Result)
	return i, err
}

const getNotificationSourceReceipt = `-- name: GetNotificationSourceReceipt :one
SELECT source_digest, notification_id FROM workos_core.notification_source_receipts
WHERE source_process = $1 AND source_id = $2
`

type GetNotificationSourceReceiptParams struct {
	SourceProcess string
	SourceID      string
}

type GetNotificationSourceReceiptRow struct {
	SourceDigest   string
	NotificationID string
}

func (q *Queries) GetNotificationSourceReceipt(ctx context.Context, arg GetNotificationSourceReceiptParams) (GetNotificationSourceReceiptRow, error) {
	row := q.db.QueryRow(ctx, getNotificationSourceReceipt, arg.SourceProcess, arg.SourceID)
	var i GetNotificationSourceReceiptRow
	err := row.Scan(&i.SourceDigest, &i.NotificationID)
	return i, err
}

const getOwnerChangeWatermark = `-- name: GetOwnerChangeWatermark :one
SELECT COALESCE((
    SELECT last_sequence
    FROM workos_core.notification_owner_sequences
    WHERE owner_user_id = $1
), 0)::bigint AS watermark
`

func (q *Queries) GetOwnerChangeWatermark(ctx context.Context, ownerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, getOwnerChangeWatermark, ownerUserID)
	var watermark int64
	err := row.Scan(&watermark)
	return watermark, err
}

const getOwnerLastSequence = `-- name: GetOwnerLastSequence :one
SELECT last_sequence FROM workos_core.notification_owner_sequences
WHERE owner_user_id = $1
`

func (q *Queries) GetOwnerLastSequence(ctx context.Context, ownerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, getOwnerLastSequence, ownerUserID)
	var last_sequence int64
	err := row.Scan(&last_sequence)
	return last_sequence, err
}

const getOwnerNotification = `-- name: GetOwnerNotification :one
SELECT id, owner_user_id, project_id, kind, severity, origin, title, body,
       target_kind, target_id, app_id, app_installation_id, source_process,
       source_id, source_digest, created_at, read_at, read_change_sequence, created_change_sequence
FROM workos_core.notifications
WHERE id = $1 AND owner_user_id = $2
`

type GetOwnerNotificationParams struct {
	ID          string
	OwnerUserID string
}

func (q *Queries) GetOwnerNotification(ctx context.Context, arg GetOwnerNotificationParams) (WorkosCoreNotification, error) {
	row := q.db.QueryRow(ctx, getOwnerNotification, arg.ID, arg.OwnerUserID)
	var i WorkosCoreNotification
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.Kind,
		&i.Severity,
		&i.Origin,
		&i.Title,
		&i.Body,
		&i.TargetKind,
		&i.TargetID,
		&i.AppID,
		&i.AppInstallationID,
		&i.SourceProcess,
		&i.SourceID,
		&i.SourceDigest,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ReadChangeSequence,
		&i.CreatedChangeSequence,
	)
	return i, err
}

const getOwnerSweptThrough = `-- name: GetOwnerSweptThrough :one
SELECT swept_through FROM workos_core.notification_owner_sequences
WHERE owner_user_id = $1
`

func (q *Queries) GetOwnerSweptThrough(ctx context.Context, ownerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, getOwnerSweptThrough, ownerUserID)
	var swept_through int64
	err := row.Scan(&swept_through)
	return swept_through, err
}

const insertNotification = `-- name: InsertNotification :execrows
INSERT INTO workos_core.notifications (
    id, owner_user_id, project_id, kind, severity, origin, title, body,
    target_kind, target_id, app_id, app_installation_id,
    source_process, source_id, source_digest, created_at, created_change_sequence
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17
)
`

type InsertNotificationParams struct {
	ID                    string
	OwnerUserID           string
	ProjectID             pgtype.UUID
	Kind                  string
	Severity              string
	Origin                string
	Title                 string
	Body                  string
	TargetKind            string
	TargetID              string
	AppID                 pgtype.Text
	AppInstallationID     pgtype.UUID
	SourceProcess         string
	SourceID              string
	SourceDigest          string
	CreatedAt             time.Time
	CreatedChangeSequence int64
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.Kind,
		arg.Severity,
		arg.Origin,
		arg.Title,
		arg.Body,
		arg.TargetKind,
		arg.TargetID,
		arg.AppID,
		arg.AppInstallationID,
		arg.SourceProcess,
		arg.SourceID,
		arg.SourceDigest,
		arg.CreatedAt,
		arg.CreatedChangeSequence,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotificationAppQuota = `-- name: InsertNotificationAppQuota :execrows
INSERT INTO workos_core.notification_app_quotas (
    owner_user_id, app_installation_id, utc_date, daily_count,
    burst_window_start, burst_count, updated_at
) VALUES (
    $1, $2, $3,
    0, $4, 0, $5
)
ON CONFLICT (owner_user_id, app_installation_id) DO NOTHING
`

type InsertNotificationAppQuotaParams struct {
	OwnerUserID       string
	AppInstallationID string
	UtcDate           pgtype.Date
	BurstWindowStart  time.Time
	UpdatedAt         time.Time
}

func (q *Queries) InsertNotificationAppQuota(ctx context.Context, arg InsertNotificationAppQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotificationAppQuota,
		arg.OwnerUserID,
		arg.AppInstallationID,
		arg.UtcDate,
		arg.BurstWindowStart,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotificationAppRequest = `-- name: InsertNotificationAppRequest :execrows
INSERT INTO workos_core.notification_app_requests (
    owner_user_id, app_installation_id, idempotency_key, request_digest,
    result_version, result, created_at
) VALUES (
    $1, $2, $3,
    $4, 1, $5, $6
)
`

type InsertNotificationAppRequestParams struct {
	OwnerUserID       string
	AppInstallationID string
	IdempotencyKey    string
	RequestDigest     string
	Result            []byte
	CreatedAt         time.Time
}

func (q *Queries) InsertNotificationAppRequest(ctx context.Context, arg InsertNotificationAppRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotificationAppRequest,
		arg.OwnerUserID,
		arg.AppInstallationID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.Result,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotificationChange = `-- name: InsertNotificationChange :execrows
INSERT INTO workos_core.notification_changes (
    owner_user_id, change_sequence, notification_id, change_type, revision, occurred_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type InsertNotificationChangeParams struct {
	OwnerUserID    string
	ChangeSequence int64
	NotificationID string
	ChangeType     string
	Revision       int64
	OccurredAt     time.Time
}

func (q *Queries) InsertNotificationChange(ctx context.Context, arg InsertNotificationChangeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotificationChange,
		arg.OwnerUserID,
		arg.ChangeSequence,
		arg.NotificationID,
		arg.ChangeType,
		arg.Revision,
		arg.OccurredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotificationReadRequest = `-- name: InsertNotificationReadRequest :execrows
INSERT INTO workos_core.notification_read_requests (
    owner_user_id, idempotency_key, request_digest, result_version, result, created_at
) VALUES (
    $1, $2, $3,
    1, $4, $5
)
`

type InsertNotificationReadRequestParams struct {
	OwnerUserID    string
	IdempotencyKey string
	RequestDigest  string
	Result         []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertNotificationReadRequest(ctx context.Context, arg InsertNotificationReadRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotificationReadRequest,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.Result,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotificationSourceReceipt = `-- name: InsertNotificationSourceReceipt :execrows
INSERT INTO workos_core.notification_source_receipts (
    source_process, source_id, source_digest, notification_id, recorded_at
) VALUES (
    $1, $2, $3,
    $4, $5
)
`

type InsertNotificationSourceReceiptParams struct {
	SourceProcess  string
	SourceID       string
	SourceDigest   string
	NotificationID string
	RecordedAt     time.Time
}

func (q *Queries) InsertNotificationSourceReceipt(ctx context.Context, arg InsertNotificationSourceReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotificationSourceReceipt,
		arg.SourceProcess,
		arg.SourceID,
		arg.SourceDigest,
		arg.NotificationID,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotificationsPage = `-- name: ListNotificationsPage :many
SELECT id, owner_user_id, project_id, kind, severity, origin, title, body,
       target_kind, target_id, app_id, app_installation_id, source_process,
       source_id, source_digest, created_at, read_at, read_change_sequence, created_change_sequence
FROM workos_core.notifications
WHERE owner_user_id = $1
  AND ($2 ::uuid IS NULL OR project_id = $2 ::uuid)
  AND (NOT $3 OR read_at IS NULL)
  AND ($4 ::text IS NULL OR kind = $4 ::text)
  AND ($5 ::timestamptz IS NULL
       OR (created_at, id) < ($5 ::timestamptz, $6 ::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListNotificationsPageParams struct {
	OwnerUserID   string
	ProjectID     pgtype.UUID
	UnreadOnly    interface{}
	Kind          pgtype.Text
	CursorCreated *time.Time
	CursorID      pgtype.UUID
	RowLimit      int32
}

func (q *Queries) ListNotificationsPage(ctx context.Context, arg ListNotificationsPageParams) ([]WorkosCoreNotification, error) {
	rows, err := q.db.Query(ctx, listNotificationsPage,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.UnreadOnly,
		arg.Kind,
		arg.CursorCreated,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosCoreNotification
	for rows.Next() {
		var i WorkosCoreNotification
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.ProjectID,
			&i.Kind,
			&i.Severity,
			&i.Origin,
			&i.Title,
			&i.Body,
			&i.TargetKind,
			&i.TargetID,
			&i.AppID,
			&i.AppInstallationID,
			&i.SourceProcess,
			&i.SourceID,
			&i.SourceDigest,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ReadChangeSequence,
			&i.CreatedChangeSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnerNotifications = `-- name: LockOwnerNotifications :many
SELECT id, owner_user_id, project_id, kind, severity, origin, title, body,
       target_kind, target_id, app_id, app_installation_id, source_process,
       source_id, source_digest, created_at, read_at, read_change_sequence, created_change_sequence
FROM workos_core.notifications
WHERE owner_user_id = $1 AND id = ANY ($2::uuid[])
ORDER BY created_at DESC, id DESC
FOR UPDATE
`

type LockOwnerNotificationsParams struct {
	OwnerUserID string
	Ids         []string
}

func (q *Queries) LockOwnerNotifications(ctx context.Context, arg LockOwnerNotificationsParams) ([]WorkosCoreNotification, error) {
	rows, err := q.db.Query(ctx, lockOwnerNotifications, arg.OwnerUserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosCoreNotification
	for rows.Next() {
		var i WorkosCoreNotification
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.ProjectID,
			&i.Kind,
			&i.Severity,
			&i.Origin,
			&i.Title,
			&i.Body,
			&i.TargetKind,
			&i.TargetID,
			&i.AppID,
			&i.AppInstallationID,
			&i.SourceProcess,
			&i.SourceID,
			&i.SourceDigest,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ReadChangeSequence,
			&i.CreatedChangeSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE workos_core.notifications
SET read_at = $1, read_change_sequence = $2
WHERE id = $3 AND owner_user_id = $4 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ReadAt             *time.Time
	ReadChangeSequence int64
	ID                 string
	OwnerUserID        string
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead,
		arg.ReadAt,
		arg.ReadChangeSequence,
		arg.ID,
		arg.OwnerUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const maxChangeSequenceForNotifications = `-- name: MaxChangeSequenceForNotifications :many
SELECT owner_user_id, max(change_sequence)::bigint AS max_seq
FROM workos_core.notification_changes
WHERE notification_id = ANY ($1::uuid[])
GROUP BY owner_user_id
`

type MaxChangeSequenceForNotificationsRow struct {
	OwnerUserID string
	MaxSeq      int64
}

func (q *Queries) MaxChangeSequenceForNotifications(ctx context.Context, ids []string) ([]MaxChangeSequenceForNotificationsRow, error) {
	rows, err := q.db.Query(ctx, maxChangeSequenceForNotifications, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaxChangeSequenceForNotificationsRow
	for rows.Next() {
		var i MaxChangeSequenceForNotificationsRow
		if err := rows.Scan(&i.OwnerUserID, &i.MaxSeq); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectSweepableNotifications = `-- name: SelectSweepableNotifications :many
SELECT id, owner_user_id FROM workos_core.notifications
WHERE read_at IS NOT NULL AND read_at < $1
ORDER BY read_at, id
LIMIT $2
`

type SelectSweepableNotificationsParams struct {
	Cutoff   *time.Time
	MaxBatch int32
}

type SelectSweepableNotificationsRow struct {
	ID          string
	OwnerUserID string
}

// Bounded sweep: only already-read notifications older than the cutoff are
// candidates. Recent unread facts are never swept.
func (q *Queries) SelectSweepableNotifications(ctx context.Context, arg SelectSweepableNotificationsParams) ([]SelectSweepableNotificationsRow, error) {
	rows, err := q.db.Query(ctx, selectSweepableNotifications, arg.Cutoff, arg.MaxBatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectSweepableNotificationsRow
	for rows.Next() {
		var i SelectSweepableNotificationsRow
		if err := rows.Scan(&i.ID, &i.OwnerUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serializeNotificationRequest = `-- name: SerializeNotificationRequest :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) SerializeNotificationRequest(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, serializeNotificationRequest, lockKey)
	return err
}

const updateNotificationAppQuota = `-- name: UpdateNotificationAppQuota :execrows
UPDATE workos_core.notification_app_quotas
SET utc_date = $1, daily_count = $2,
    burst_window_start = $3, burst_count = $4,
    updated_at = $5
WHERE owner_user_id = $6
  AND app_installation_id = $7
`

type UpdateNotificationAppQuotaParams struct {
	UtcDate           pgtype.Date
	DailyCount        int32
	BurstWindowStart  time.Time
	BurstCount        int32
	UpdatedAt         time.Time
	OwnerUserID       string
	AppInstallationID string
}

func (q *Queries) UpdateNotificationAppQuota(ctx context.Context, arg UpdateNotificationAppQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotificationAppQuota,
		arg.UtcDate,
		arg.DailyCount,
		arg.BurstWindowStart,
		arg.BurstCount,
		arg.UpdatedAt,
		arg.OwnerUserID,
		arg.AppInstallationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
