// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package notificationdb

import (
	"context"
	"time"
)

type Querier interface {
	AdvanceOwnerSweptThrough(ctx context.Context, arg AdvanceOwnerSweptThroughParams) (int64, error)
	// Core notification facts (ADR-0014, migration 029). Every statement here
	// touches only the workos_core notification tables; other modules are
	// reached through their owning modules' ports.
	AllocateNotificationChangeSequence(ctx context.Context, arg AllocateNotificationChangeSequenceParams) (int64, error)
	CountOwnerUnread(ctx context.Context, ownerUserID string) (int64, error)
	DeleteNotificationChangesFor(ctx context.Context, ids []string) (int64, error)
	DeleteNotifications(ctx context.Context, ids []string) (int64, error)
	// Receipts outlive notifications (longer horizon, same bounded sweep) so a
	// pathological late replay can never project a second notification.
	DeleteOldSourceReceipts(ctx context.Context, cutoff time.Time) (int64, error)
	GetChangesAfter(ctx context.Context, arg GetChangesAfterParams) ([]GetChangesAfterRow, error)
	GetNotificationAppQuotaForUpdate(ctx context.Context, arg GetNotificationAppQuotaForUpdateParams) (GetNotificationAppQuotaForUpdateRow, error)
	GetNotificationAppRequest(ctx context.Context, arg GetNotificationAppRequestParams) (GetNotificationAppRequestRow, error)
	GetNotificationByID(ctx context.Context, id string) (WorkosCoreNotification, error)
	GetNotificationReadRequest(ctx context.Context, arg GetNotificationReadRequestParams) (GetNotificationReadRequestRow, error)
	GetNotificationSourceReceipt(ctx context.Context, arg GetNotificationSourceReceiptParams) (GetNotificationSourceReceiptRow, error)
	GetOwnerChangeWatermark(ctx context.Context, ownerUserID string) (int64, error)
	GetOwnerLastSequence(ctx context.Context, ownerUserID string) (int64, error)
	GetOwnerNotification(ctx context.Context, arg GetOwnerNotificationParams) (WorkosCoreNotification, error)
	GetOwnerSweptThrough(ctx context.Context, ownerUserID string) (int64, error)
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error)
	InsertNotificationAppQuota(ctx context.Context, arg InsertNotificationAppQuotaParams) (int64, error)
	InsertNotificationAppRequest(ctx context.Context, arg InsertNotificationAppRequestParams) (int64, error)
	InsertNotificationChange(ctx context.Context, arg InsertNotificationChangeParams) (int64, error)
	InsertNotificationReadRequest(ctx context.Context, arg InsertNotificationReadRequestParams) (int64, error)
	InsertNotificationSourceReceipt(ctx context.Context, arg InsertNotificationSourceReceiptParams) (int64, error)
	ListNotificationsPage(ctx context.Context, arg ListNotificationsPageParams) ([]WorkosCoreNotification, error)
	LockOwnerNotifications(ctx context.Context, arg LockOwnerNotificationsParams) ([]WorkosCoreNotification, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error)
	MaxChangeSequenceForNotifications(ctx context.Context, ids []string) ([]MaxChangeSequenceForNotificationsRow, error)
	// Bounded sweep: only already-read notifications older than the cutoff are
	// candidates. Recent unread facts are never swept.
	SelectSweepableNotifications(ctx context.Context, arg SelectSweepableNotificationsParams) ([]SelectSweepableNotificationsRow, error)
	SerializeNotificationRequest(ctx context.Context, lockKey string) error
	UpdateNotificationAppQuota(ctx context.Context, arg UpdateNotificationAppQuotaParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
