// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workloaddb

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type WorkosRuntimeWorkload struct {
	ID                       string          `json:"id"`
	OwnerUserID              string          `json:"owner_user_id"`
	ProjectID                string          `json:"project_id"`
	AppInstanceID            string          `json:"app_instance_id"`
	AppID                    string          `json:"app_id"`
	AppVersion               string          `json:"app_version"`
	ManifestDigest           string          `json:"manifest_digest"`
	Image                    string          `json:"image"`
	Command                  json.RawMessage `json:"command"`
	Port                     int32           `json:"port"`
	RequestedPolicy          json.RawMessage `json:"requested_policy"`
	PolicyVersion            string          `json:"policy_version"`
	EffectiveCpuQuotaUs      int64           `json:"effective_cpu_quota_us"`
	EffectiveMemoryHighBytes int64           `json:"effective_memory_high_bytes"`
	EffectiveMemoryMaxBytes  int64           `json:"effective_memory_max_bytes"`
	EffectivePidsMax         int32           `json:"effective_pids_max"`
	EffectiveStartupSeconds  int32           `json:"effective_startup_seconds"`
	EffectiveRestartLimit    int32           `json:"effective_restart_limit"`
	Generation               int64           `json:"generation"`
	State                    string          `json:"state"`
	RestartCount             int32           `json:"restart_count"`
	ContainerID              pgtype.Text     `json:"container_id"`
	ContainerName            string          `json:"container_name"`
	Endpoint                 pgtype.Text     `json:"endpoint"`
	CgroupPath               pgtype.Text     `json:"cgroup_path"`
	HealthVerdict            string          `json:"health_verdict"`
	LastExitCategory         string          `json:"last_exit_category"`
	BaselineMemoryEventsOom  int64           `json:"baseline_memory_events_oom"`
	BaselinePidsEventsPeak   int64           `json:"baseline_pids_events_peak"`
	LastVerifiedAt           *time.Time      `json:"last_verified_at"`
	LeaseOwner               pgtype.Text     `json:"lease_owner"`
	LeaseExpiresAt           *time.Time      `json:"lease_expires_at"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
	StartedAt                *time.Time      `json:"started_at"`
	StoppedAt                *time.Time      `json:"stopped_at"`
}

type WorkosRuntimeWorkloadOperation struct {
	WorkloadID       string      `json:"workload_id"`
	OperationKey     string      `json:"operation_key"`
	Operation        string      `json:"operation"`
	RequestDigest    string      `json:"request_digest"`
	ResultState      pgtype.Text `json:"result_state"`
	ResultGeneration pgtype.Int8 `json:"result_generation"`
	ErrorKind        pgtype.Text `json:"error_kind"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}
