// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workloaddb

import (
	"context"
)

type Querier interface {
	ClaimWorkloadLease(ctx context.Context, arg ClaimWorkloadLeaseParams) (int64, error)
	GetActiveWorkloadByInstance(ctx context.Context, arg GetActiveWorkloadByInstanceParams) (WorkosRuntimeWorkload, error)
	GetWorkload(ctx context.Context, id string) (WorkosRuntimeWorkload, error)
	GetWorkloadOperation(ctx context.Context, arg GetWorkloadOperationParams) (WorkosRuntimeWorkloadOperation, error)
	// Workload Manager persistence queries (runtime-host owned tables only).
	InsertWorkload(ctx context.Context, arg InsertWorkloadParams) error
	// The primary key is the same-key race arbiter: a concurrent reserve of the
	// same (workload, key) inserts nothing and the caller re-reads instead.
	InsertWorkloadOperation(ctx context.Context, arg InsertWorkloadOperationParams) (int64, error)
	ListWorkloads(ctx context.Context, rowLimit int32) ([]WorkosRuntimeWorkload, error)
	// The guarded restart transition: re-open a running or failed workload under
	// generation+1, clear the engine facts, and restart the count.
	RestartWorkloadFrom(ctx context.Context, arg RestartWorkloadFromParams) (int64, error)
	// The generation guard keeps a stale launch from landing on top of a newer
	// restart: only the exact starting generation may become running.
	SetWorkloadRunning(ctx context.Context, arg SetWorkloadRunningParams) (int64, error)
	// Generic guarded transition for stopping/failed/stopped landings; the
	// caller supplies the bounded fact bundle explicitly.
	SetWorkloadState(ctx context.Context, arg SetWorkloadStateParams) (int64, error)
	StampWorkloadVerified(ctx context.Context, arg StampWorkloadVerifiedParams) (int64, error)
	// Records or finalizes one operation verdict; the request_digest never
	// changes after the first reserve.
	UpsertWorkloadOperation(ctx context.Context, arg UpsertWorkloadOperationParams) error
}

var _ Querier = (*Queries)(nil)
