// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package workloaddb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWorkloadLease = `-- name: ClaimWorkloadLease :execrows
UPDATE workos_runtime.workloads SET
    lease_owner = $1,
    lease_expires_at = $2,
    updated_at = $3
WHERE id = $4
  AND (lease_owner = $1
       OR lease_expires_at IS NULL
       OR lease_expires_at < $5)
`

type ClaimWorkloadLeaseParams struct {
	LeaseOwner     pgtype.Text `json:"lease_owner"`
	LeaseExpiresAt *time.Time  `json:"lease_expires_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	ID             string      `json:"id"`
	Now            *time.Time  `json:"now"`
}

func (q *Queries) ClaimWorkloadLease(ctx context.Context, arg ClaimWorkloadLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimWorkloadLease,
		arg.LeaseOwner,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveWorkloadByInstance = `-- name: GetActiveWorkloadByInstance :one
SELECT id, owner_user_id, project_id, app_instance_id, app_id, app_version,
       manifest_digest, image, command, port, requested_policy, policy_version,
       effective_cpu_quota_us, effective_memory_high_bytes, effective_memory_max_bytes,
       effective_pids_max, effective_startup_seconds, effective_restart_limit,
       generation, state, restart_count, container_id, container_name, endpoint,
       cgroup_path, health_verdict, last_exit_category,
       baseline_memory_events_oom, baseline_pids_events_peak,
       last_verified_at, lease_owner, lease_expires_at,
       created_at, updated_at, started_at, stopped_at
FROM workos_runtime.workloads
WHERE owner_user_id = $1
  AND app_instance_id = $2
  AND state NOT IN ('stopped', 'failed')
ORDER BY created_at, id
LIMIT 1
`

type GetActiveWorkloadByInstanceParams struct {
	OwnerUserID   string `json:"owner_user_id"`
	AppInstanceID string `json:"app_instance_id"`
}

func (q *Queries) GetActiveWorkloadByInstance(ctx context.Context, arg GetActiveWorkloadByInstanceParams) (WorkosRuntimeWorkload, error) {
	row := q.db.QueryRow(ctx, getActiveWorkloadByInstance, arg.OwnerUserID, arg.AppInstanceID)
	var i WorkosRuntimeWorkload
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.AppInstanceID,
		&i.AppID,
		&i.AppVersion,
		&i.ManifestDigest,
		&i.Image,
		&i.Command,
		&i.Port,
		&i.RequestedPolicy,
		&i.PolicyVersion,
		&i.EffectiveCpuQuotaUs,
		&i.EffectiveMemoryHighBytes,
		&i.EffectiveMemoryMaxBytes,
		&i.EffectivePidsMax,
		&i.EffectiveStartupSeconds,
		&i.EffectiveRestartLimit,
		&i.Generation,
		&i.State,
		&i.RestartCount,
		&i.ContainerID,
		&i.ContainerName,
		&i.Endpoint,
		&i.CgroupPath,
		&i.HealthVerdict,
		&i.LastExitCategory,
		&i.BaselineMemoryEventsOom,
		&i.BaselinePidsEventsPeak,
		&i.LastVerifiedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.StoppedAt,
	)
	return i, err
}

const getWorkload = `-- name: GetWorkload :one
SELECT id, owner_user_id, project_id, app_instance_id, app_id, app_version,
       manifest_digest, image, command, port, requested_policy, policy_version,
       effective_cpu_quota_us, effective_memory_high_bytes, effective_memory_max_bytes,
       effective_pids_max, effective_startup_seconds, effective_restart_limit,
       generation, state, restart_count, container_id, container_name, endpoint,
       cgroup_path, health_verdict, last_exit_category,
       baseline_memory_events_oom, baseline_pids_events_peak,
       last_verified_at, lease_owner, lease_expires_at,
       created_at, updated_at, started_at, stopped_at
FROM workos_runtime.workloads
WHERE id = $1
`

func (q *Queries) GetWorkload(ctx context.Context, id string) (WorkosRuntimeWorkload, error) {
	row := q.db.QueryRow(ctx, getWorkload, id)
	var i WorkosRuntimeWorkload
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.AppInstanceID,
		&i.AppID,
		&i.AppVersion,
		&i.ManifestDigest,
		&i.Image,
		&i.Command,
		&i.Port,
		&i.RequestedPolicy,
		&i.PolicyVersion,
		&i.EffectiveCpuQuotaUs,
		&i.EffectiveMemoryHighBytes,
		&i.EffectiveMemoryMaxBytes,
		&i.EffectivePidsMax,
		&i.EffectiveStartupSeconds,
		&i.EffectiveRestartLimit,
		&i.Generation,
		&i.State,
		&i.RestartCount,
		&i.ContainerID,
		&i.ContainerName,
		&i.Endpoint,
		&i.CgroupPath,
		&i.HealthVerdict,
		&i.LastExitCategory,
		&i.BaselineMemoryEventsOom,
		&i.BaselinePidsEventsPeak,
		&i.LastVerifiedAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.StoppedAt,
	)
	return i, err
}

const getWorkloadOperation = `-- name: GetWorkloadOperation :one
SELECT workload_id, operation_key, operation, request_digest,
       result_state, result_generation, error_kind, created_at, updated_at
FROM workos_runtime.workload_operations
WHERE workload_id = $1 AND operation_key = $2
`

type GetWorkloadOperationParams struct {
	WorkloadID   string `json:"workload_id"`
	OperationKey string `json:"operation_key"`
}

func (q *Queries) GetWorkloadOperation(ctx context.Context, arg GetWorkloadOperationParams) (WorkosRuntimeWorkloadOperation, error) {
	row := q.db.QueryRow(ctx, getWorkloadOperation, arg.WorkloadID, arg.OperationKey)
	var i WorkosRuntimeWorkloadOperation
	err := row.Scan(
		&i.WorkloadID,
		&i.OperationKey,
		&i.Operation,
		&i.RequestDigest,
		&i.ResultState,
		&i.ResultGeneration,
		&i.ErrorKind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkload = `-- name: InsertWorkload :exec

INSERT INTO workos_runtime.workloads (
    id, owner_user_id, project_id, app_instance_id, app_id, app_version,
    manifest_digest, image, command, port, requested_policy, policy_version,
    effective_cpu_quota_us, effective_memory_high_bytes, effective_memory_max_bytes,
    effective_pids_max, effective_startup_seconds, effective_restart_limit,
    generation, state, container_name, health_verdict, last_exit_category,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14,
    $15, $16,
    $17, $18,
    $19, $20, $21,
    $22, $23,
    $24, $25
)
`

type InsertWorkloadParams struct {
	ID                       string          `json:"id"`
	OwnerUserID              string          `json:"owner_user_id"`
	ProjectID                string          `json:"project_id"`
	AppInstanceID            string          `json:"app_instance_id"`
	AppID                    string          `json:"app_id"`
	AppVersion               string          `json:"app_version"`
	ManifestDigest           string          `json:"manifest_digest"`
	Image                    string          `json:"image"`
	Command                  json.RawMessage `json:"command"`
	Port                     int32           `json:"port"`
	RequestedPolicy          json.RawMessage `json:"requested_policy"`
	PolicyVersion            string          `json:"policy_version"`
	EffectiveCpuQuotaUs      int64           `json:"effective_cpu_quota_us"`
	EffectiveMemoryHighBytes int64           `json:"effective_memory_high_bytes"`
	EffectiveMemoryMaxBytes  int64           `json:"effective_memory_max_bytes"`
	EffectivePidsMax         int32           `json:"effective_pids_max"`
	EffectiveStartupSeconds  int32           `json:"effective_startup_seconds"`
	EffectiveRestartLimit    int32           `json:"effective_restart_limit"`
	Generation               int64           `json:"generation"`
	State                    string          `json:"state"`
	ContainerName            string          `json:"container_name"`
	HealthVerdict            string          `json:"health_verdict"`
	LastExitCategory         string          `json:"last_exit_category"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
}

// Workload Manager persistence queries (runtime-host owned tables only).
func (q *Queries) InsertWorkload(ctx context.Context, arg InsertWorkloadParams) error {
	_, err := q.db.Exec(ctx, insertWorkload,
		arg.ID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.AppInstanceID,
		arg.AppID,
		arg.AppVersion,
		arg.ManifestDigest,
		arg.Image,
		arg.Command,
		arg.Port,
		arg.RequestedPolicy,
		arg.PolicyVersion,
		arg.EffectiveCpuQuotaUs,
		arg.EffectiveMemoryHighBytes,
		arg.EffectiveMemoryMaxBytes,
		arg.EffectivePidsMax,
		arg.EffectiveStartupSeconds,
		arg.EffectiveRestartLimit,
		arg.Generation,
		arg.State,
		arg.ContainerName,
		arg.HealthVerdict,
		arg.LastExitCategory,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertWorkloadOperation = `-- name: InsertWorkloadOperation :execrows
INSERT INTO workos_runtime.workload_operations (
    workload_id, operation_key, operation, request_digest, created_at, updated_at
) VALUES ($1, $2, $3,
          $4, $5, $6)
ON CONFLICT (workload_id, operation_key) DO NOTHING
`

type InsertWorkloadOperationParams struct {
	WorkloadID    string    `json:"workload_id"`
	OperationKey  string    `json:"operation_key"`
	Operation     string    `json:"operation"`
	RequestDigest string    `json:"request_digest"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// The primary key is the same-key race arbiter: a concurrent reserve of the
// same (workload, key) inserts nothing and the caller re-reads instead.
func (q *Queries) InsertWorkloadOperation(ctx context.Context, arg InsertWorkloadOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWorkloadOperation,
		arg.WorkloadID,
		arg.OperationKey,
		arg.Operation,
		arg.RequestDigest,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listWorkloads = `-- name: ListWorkloads :many
SELECT id, owner_user_id, project_id, app_instance_id, app_id, app_version,
       manifest_digest, image, command, port, requested_policy, policy_version,
       effective_cpu_quota_us, effective_memory_high_bytes, effective_memory_max_bytes,
       effective_pids_max, effective_startup_seconds, effective_restart_limit,
       generation, state, restart_count, container_id, container_name, endpoint,
       cgroup_path, health_verdict, last_exit_category,
       baseline_memory_events_oom, baseline_pids_events_peak,
       last_verified_at, lease_owner, lease_expires_at,
       created_at, updated_at, started_at, stopped_at
FROM workos_runtime.workloads
ORDER BY created_at, id
LIMIT $1
`

func (q *Queries) ListWorkloads(ctx context.Context, rowLimit int32) ([]WorkosRuntimeWorkload, error) {
	rows, err := q.db.Query(ctx, listWorkloads, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosRuntimeWorkload
	for rows.Next() {
		var i WorkosRuntimeWorkload
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.ProjectID,
			&i.AppInstanceID,
			&i.AppID,
			&i.AppVersion,
			&i.ManifestDigest,
			&i.Image,
			&i.Command,
			&i.Port,
			&i.RequestedPolicy,
			&i.PolicyVersion,
			&i.EffectiveCpuQuotaUs,
			&i.EffectiveMemoryHighBytes,
			&i.EffectiveMemoryMaxBytes,
			&i.EffectivePidsMax,
			&i.EffectiveStartupSeconds,
			&i.EffectiveRestartLimit,
			&i.Generation,
			&i.State,
			&i.RestartCount,
			&i.ContainerID,
			&i.ContainerName,
			&i.Endpoint,
			&i.CgroupPath,
			&i.HealthVerdict,
			&i.LastExitCategory,
			&i.BaselineMemoryEventsOom,
			&i.BaselinePidsEventsPeak,
			&i.LastVerifiedAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.StoppedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restartWorkloadFrom = `-- name: RestartWorkloadFrom :execrows
UPDATE workos_runtime.workloads SET
    state = 'starting',
    generation = generation + 1,
    restart_count = restart_count + 1,
    container_id = NULL,
    endpoint = NULL,
    cgroup_path = NULL,
    health_verdict = 'unknown',
    last_exit_category = 'none',
    stopped_at = NULL,
    updated_at = $1
WHERE id = $2
  AND state = $3
  AND state IN ('running', 'failed')
`

type RestartWorkloadFromParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
	FromState string    `json:"from_state"`
}

// The guarded restart transition: re-open a running or failed workload under
// generation+1, clear the engine facts, and restart the count.
func (q *Queries) RestartWorkloadFrom(ctx context.Context, arg RestartWorkloadFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, restartWorkloadFrom, arg.UpdatedAt, arg.ID, arg.FromState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkloadRunning = `-- name: SetWorkloadRunning :execrows
UPDATE workos_runtime.workloads SET
    state = 'running',
    container_id = $1,
    endpoint = $2,
    cgroup_path = $3,
    health_verdict = $4,
    last_exit_category = $5,
    baseline_memory_events_oom = $6,
    baseline_pids_events_peak = $7,
    started_at = $8,
    stopped_at = NULL,
    updated_at = $9
WHERE id = $10 AND state = 'starting' AND generation = $11
`

type SetWorkloadRunningParams struct {
	ContainerID             pgtype.Text `json:"container_id"`
	Endpoint                pgtype.Text `json:"endpoint"`
	CgroupPath              pgtype.Text `json:"cgroup_path"`
	HealthVerdict           string      `json:"health_verdict"`
	LastExitCategory        string      `json:"last_exit_category"`
	BaselineMemoryEventsOom int64       `json:"baseline_memory_events_oom"`
	BaselinePidsEventsPeak  int64       `json:"baseline_pids_events_peak"`
	StartedAt               *time.Time  `json:"started_at"`
	UpdatedAt               time.Time   `json:"updated_at"`
	ID                      string      `json:"id"`
	Generation              int64       `json:"generation"`
}

// The generation guard keeps a stale launch from landing on top of a newer
// restart: only the exact starting generation may become running.
func (q *Queries) SetWorkloadRunning(ctx context.Context, arg SetWorkloadRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkloadRunning,
		arg.ContainerID,
		arg.Endpoint,
		arg.CgroupPath,
		arg.HealthVerdict,
		arg.LastExitCategory,
		arg.BaselineMemoryEventsOom,
		arg.BaselinePidsEventsPeak,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWorkloadState = `-- name: SetWorkloadState :execrows
UPDATE workos_runtime.workloads SET
    state = $1,
    container_id = $2,
    endpoint = $3,
    cgroup_path = $4,
    health_verdict = $5,
    last_exit_category = $6,
    stopped_at = $7,
    updated_at = $8
WHERE id = $9
  AND state = $10
  AND state NOT IN ('stopped', 'failed')
`

type SetWorkloadStateParams struct {
	ToState          string      `json:"to_state"`
	ContainerID      pgtype.Text `json:"container_id"`
	Endpoint         pgtype.Text `json:"endpoint"`
	CgroupPath       pgtype.Text `json:"cgroup_path"`
	HealthVerdict    string      `json:"health_verdict"`
	LastExitCategory string      `json:"last_exit_category"`
	StoppedAt        *time.Time  `json:"stopped_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	ID               string      `json:"id"`
	FromState        string      `json:"from_state"`
}

// Generic guarded transition for stopping/failed/stopped landings; the
// caller supplies the bounded fact bundle explicitly.
func (q *Queries) SetWorkloadState(ctx context.Context, arg SetWorkloadStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkloadState,
		arg.ToState,
		arg.ContainerID,
		arg.Endpoint,
		arg.CgroupPath,
		arg.HealthVerdict,
		arg.LastExitCategory,
		arg.StoppedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.FromState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stampWorkloadVerified = `-- name: StampWorkloadVerified :execrows
UPDATE workos_runtime.workloads SET
    last_verified_at = $1,
    updated_at = $2
WHERE id = $3 AND state = 'running'
`

type StampWorkloadVerifiedParams struct {
	VerifiedAt *time.Time `json:"verified_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
	ID         string     `json:"id"`
}

func (q *Queries) StampWorkloadVerified(ctx context.Context, arg StampWorkloadVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, stampWorkloadVerified, arg.VerifiedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWorkloadOperation = `-- name: UpsertWorkloadOperation :exec
INSERT INTO workos_runtime.workload_operations (
    workload_id, operation_key, operation, request_digest,
    result_state, result_generation, error_kind, created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
ON CONFLICT (workload_id, operation_key) DO UPDATE
SET result_state = $5,
    result_generation = $6,
    error_kind = $7,
    updated_at = $9
`

type UpsertWorkloadOperationParams struct {
	WorkloadID       string      `json:"workload_id"`
	OperationKey     string      `json:"operation_key"`
	Operation        string      `json:"operation"`
	RequestDigest    string      `json:"request_digest"`
	ResultState      pgtype.Text `json:"result_state"`
	ResultGeneration pgtype.Int8 `json:"result_generation"`
	ErrorKind        pgtype.Text `json:"error_kind"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

// Records or finalizes one operation verdict; the request_digest never
// changes after the first reserve.
func (q *Queries) UpsertWorkloadOperation(ctx context.Context, arg UpsertWorkloadOperationParams) error {
	_, err := q.db.Exec(ctx, upsertWorkloadOperation,
		arg.WorkloadID,
		arg.OperationKey,
		arg.Operation,
		arg.RequestDigest,
		arg.ResultState,
		arg.ResultGeneration,
		arg.ErrorKind,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
