// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package agentdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceTaskState = `-- name: AdvanceTaskState :exec
UPDATE workos_core.agent_tasks
SET state = $1,
    provider_id = COALESCE(NULLIF($2::text, ''), provider_id),
    run_id = COALESCE(NULLIF($3::text, ''), run_id),
    last_event_sequence = $4, updated_at = $5
WHERE id = $6
`

type AdvanceTaskStateParams struct {
	State      string             `json:"state"`
	ProviderID string             `json:"provider_id"`
	RunID      string             `json:"run_id"`
	Sequence   int64              `json:"sequence"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	TaskID     string             `json:"task_id"`
}

func (q *Queries) AdvanceTaskState(ctx context.Context, arg AdvanceTaskStateParams) error {
	_, err := q.db.Exec(ctx, advanceTaskState,
		arg.State,
		arg.ProviderID,
		arg.RunID,
		arg.Sequence,
		arg.UpdatedAt,
		arg.TaskID,
	)
	return err
}

const finishPendingTaskRequest = `-- name: FinishPendingTaskRequest :exec
UPDATE workos_events.outbox
SET processed_at = $1
WHERE aggregate_type = 'agent-task' AND aggregate_id = $2 AND processed_at IS NULL
`

type FinishPendingTaskRequestParams struct {
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	AggregateID string             `json:"aggregate_id"`
}

func (q *Queries) FinishPendingTaskRequest(ctx context.Context, arg FinishPendingTaskRequestParams) error {
	_, err := q.db.Exec(ctx, finishPendingTaskRequest, arg.ProcessedAt, arg.AggregateID)
	return err
}

const finishTaskLease = `-- name: FinishTaskLease :execrows
UPDATE workos_events.outbox AS o
SET processed_at = $1, lease_id = NULL, locked_by = NULL, locked_until = NULL
FROM workos_core.agent_tasks AS t
WHERE o.lease_id = $2 AND o.locked_by = $3 AND t.id = o.aggregate_id
  AND t.state IN ('completed', 'failed', 'cancelled')
`

type FinishTaskLeaseParams struct {
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LeaseID     pgtype.UUID        `json:"lease_id"`
	LockedBy    pgtype.Text        `json:"locked_by"`
}

func (q *Queries) FinishTaskLease(ctx context.Context, arg FinishTaskLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishTaskLease, arg.ProcessedAt, arg.LeaseID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentTask = `-- name: GetAgentTask :one
SELECT id, owner_user_id, idempotency_key, project_id, input, state, provider_id,
       harness_instance_id, run_id, last_event_sequence, cancellation_requested, created_at, updated_at
FROM workos_core.agent_tasks
WHERE owner_user_id = $1 AND id = $2
`

type GetAgentTaskParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetAgentTask(ctx context.Context, arg GetAgentTaskParams) (WorkosCoreAgentTask, error) {
	row := q.db.QueryRow(ctx, getAgentTask, arg.OwnerUserID, arg.ID)
	var i WorkosCoreAgentTask
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.ProjectID,
		&i.Input,
		&i.State,
		&i.ProviderID,
		&i.HarnessInstanceID,
		&i.RunID,
		&i.LastEventSequence,
		&i.CancellationRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTaskByIdempotency = `-- name: GetAgentTaskByIdempotency :one
SELECT id, owner_user_id, idempotency_key, project_id, input, state, provider_id,
       harness_instance_id, run_id, last_event_sequence, cancellation_requested, created_at, updated_at
FROM workos_core.agent_tasks
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetAgentTaskByIdempotencyParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetAgentTaskByIdempotency(ctx context.Context, arg GetAgentTaskByIdempotencyParams) (WorkosCoreAgentTask, error) {
	row := q.db.QueryRow(ctx, getAgentTaskByIdempotency, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosCoreAgentTask
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.ProjectID,
		&i.Input,
		&i.State,
		&i.ProviderID,
		&i.HarnessInstanceID,
		&i.RunID,
		&i.LastEventSequence,
		&i.CancellationRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTaskForUpdate = `-- name: GetAgentTaskForUpdate :one
SELECT id, owner_user_id, idempotency_key, project_id, input, state, provider_id,
       harness_instance_id, run_id, last_event_sequence, cancellation_requested, created_at, updated_at
FROM workos_core.agent_tasks
WHERE owner_user_id = $1 AND id = $2
FOR UPDATE
`

type GetAgentTaskForUpdateParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetAgentTaskForUpdate(ctx context.Context, arg GetAgentTaskForUpdateParams) (WorkosCoreAgentTask, error) {
	row := q.db.QueryRow(ctx, getAgentTaskForUpdate, arg.OwnerUserID, arg.ID)
	var i WorkosCoreAgentTask
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.ProjectID,
		&i.Input,
		&i.State,
		&i.ProviderID,
		&i.HarnessInstanceID,
		&i.RunID,
		&i.LastEventSequence,
		&i.CancellationRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTaskUnscoped = `-- name: GetAgentTaskUnscoped :one
SELECT id, owner_user_id, idempotency_key, project_id, input, state, provider_id,
       harness_instance_id, run_id, last_event_sequence, cancellation_requested, created_at, updated_at
FROM workos_core.agent_tasks
WHERE id = $1
`

func (q *Queries) GetAgentTaskUnscoped(ctx context.Context, id string) (WorkosCoreAgentTask, error) {
	row := q.db.QueryRow(ctx, getAgentTaskUnscoped, id)
	var i WorkosCoreAgentTask
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.ProjectID,
		&i.Input,
		&i.State,
		&i.ProviderID,
		&i.HarnessInstanceID,
		&i.RunID,
		&i.LastEventSequence,
		&i.CancellationRequested,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectHarnessBinding = `-- name: GetProjectHarnessBinding :one
SELECT harness_binding
FROM workos_core.projects
WHERE id = $1 AND owner_user_id = $2 AND archived_at IS NULL
`

type GetProjectHarnessBindingParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) GetProjectHarnessBinding(ctx context.Context, arg GetProjectHarnessBindingParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProjectHarnessBinding, arg.ID, arg.OwnerUserID)
	var harness_binding []byte
	err := row.Scan(&harness_binding)
	return harness_binding, err
}

const insertAgentTask = `-- name: InsertAgentTask :execrows
INSERT INTO workos_core.agent_tasks (
    id, owner_user_id, idempotency_key, project_id, input, state, provider_id, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (owner_user_id, idempotency_key) DO NOTHING
`

type InsertAgentTaskParams struct {
	ID             string             `json:"id"`
	OwnerUserID    string             `json:"owner_user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Input          json.RawMessage    `json:"input"`
	State          string             `json:"state"`
	ProviderID     string             `json:"provider_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertAgentTask(ctx context.Context, arg InsertAgentTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAgentTask,
		arg.ID,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.ProjectID,
		arg.Input,
		arg.State,
		arg.ProviderID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTaskEvent = `-- name: InsertTaskEvent :exec
INSERT INTO workos_events.events (
    id, stream_type, stream_id, sequence, event_type, payload, occurred_at
) VALUES ($1, 'agent-task', $2, $3, $4, $5, $6)
`

type InsertTaskEventParams struct {
	ID         string             `json:"id"`
	StreamID   string             `json:"stream_id"`
	Sequence   int64              `json:"sequence"`
	EventType  string             `json:"event_type"`
	Payload    json.RawMessage    `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertTaskEvent(ctx context.Context, arg InsertTaskEventParams) error {
	_, err := q.db.Exec(ctx, insertTaskEvent,
		arg.ID,
		arg.StreamID,
		arg.Sequence,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertTaskOutbox = `-- name: InsertTaskOutbox :exec
INSERT INTO workos_events.outbox (
    id, aggregate_type, aggregate_id, event_type, payload, occurred_at
) VALUES ($1, 'agent-task', $2, 'agent.task.requested.v1', $3, $4)
`

type InsertTaskOutboxParams struct {
	ID          string             `json:"id"`
	AggregateID string             `json:"aggregate_id"`
	Payload     json.RawMessage    `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertTaskOutbox(ctx context.Context, arg InsertTaskOutboxParams) error {
	_, err := q.db.Exec(ctx, insertTaskOutbox,
		arg.ID,
		arg.AggregateID,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const leaseTask = `-- name: LeaseTask :exec
UPDATE workos_events.outbox
SET lease_id = $1, locked_by = $2, locked_until = $3, attempts = attempts + 1
WHERE event_type = 'agent.task.requested.v1' AND aggregate_id = $4 AND processed_at IS NULL
`

type LeaseTaskParams struct {
	LeaseID     pgtype.UUID        `json:"lease_id"`
	LockedBy    pgtype.Text        `json:"locked_by"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	AggregateID string             `json:"aggregate_id"`
}

func (q *Queries) LeaseTask(ctx context.Context, arg LeaseTaskParams) error {
	_, err := q.db.Exec(ctx, leaseTask,
		arg.LeaseID,
		arg.LockedBy,
		arg.LockedUntil,
		arg.AggregateID,
	)
	return err
}

const listAgentTasks = `-- name: ListAgentTasks :many
SELECT id, owner_user_id, idempotency_key, project_id, input, state, provider_id,
       harness_instance_id, run_id, last_event_sequence, cancellation_requested, created_at, updated_at
FROM workos_core.agent_tasks
WHERE owner_user_id = $1
  AND ($2::text = '' OR project_id = $2::uuid)
  AND id > $3
ORDER BY id
LIMIT $4
`

type ListAgentTasksParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ProjectID   string `json:"project_id"`
	Cursor      string `json:"cursor"`
	RowLimit    int32  `json:"row_limit"`
}

func (q *Queries) ListAgentTasks(ctx context.Context, arg ListAgentTasksParams) ([]WorkosCoreAgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasks,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.Cursor,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosCoreAgentTask
	for rows.Next() {
		var i WorkosCoreAgentTask
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.IdempotencyKey,
			&i.ProjectID,
			&i.Input,
			&i.State,
			&i.ProviderID,
			&i.HarnessInstanceID,
			&i.RunID,
			&i.LastEventSequence,
			&i.CancellationRequested,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskEvents = `-- name: ListTaskEvents :many
SELECT id, stream_id, sequence, event_type, payload, occurred_at
FROM workos_events.events
WHERE stream_type = 'agent-task' AND stream_id = $1 AND sequence > $2
ORDER BY sequence
LIMIT $3
`

type ListTaskEventsParams struct {
	StreamID string `json:"stream_id"`
	Sequence int64  `json:"sequence"`
	Limit    int32  `json:"limit"`
}

type ListTaskEventsRow struct {
	ID         string             `json:"id"`
	StreamID   string             `json:"stream_id"`
	Sequence   int64              `json:"sequence"`
	EventType  string             `json:"event_type"`
	Payload    json.RawMessage    `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListTaskEvents(ctx context.Context, arg ListTaskEventsParams) ([]ListTaskEventsRow, error) {
	rows, err := q.db.Query(ctx, listTaskEvents, arg.StreamID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskEventsRow
	for rows.Next() {
		var i ListTaskEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.StreamID,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskEventStream = `-- name: LockTaskEventStream :one
SELECT t.id, t.last_event_sequence, t.state
FROM workos_events.outbox AS o
JOIN workos_core.agent_tasks AS t ON t.id = o.aggregate_id
WHERE o.lease_id = $1 AND o.locked_by = $2 AND o.processed_at IS NULL AND o.locked_until >= $3
FOR UPDATE OF o, t
`

type LockTaskEventStreamParams struct {
	LeaseID     pgtype.UUID        `json:"lease_id"`
	LockedBy    pgtype.Text        `json:"locked_by"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

type LockTaskEventStreamRow struct {
	ID                string `json:"id"`
	LastEventSequence int64  `json:"last_event_sequence"`
	State             string `json:"state"`
}

func (q *Queries) LockTaskEventStream(ctx context.Context, arg LockTaskEventStreamParams) (LockTaskEventStreamRow, error) {
	row := q.db.QueryRow(ctx, lockTaskEventStream, arg.LeaseID, arg.LockedBy, arg.LockedUntil)
	var i LockTaskEventStreamRow
	err := row.Scan(&i.ID, &i.LastEventSequence, &i.State)
	return i, err
}

const markTaskCancelled = `-- name: MarkTaskCancelled :exec
UPDATE workos_core.agent_tasks
SET state = 'cancelled', cancellation_requested = true, last_event_sequence = $1, updated_at = $2
WHERE id = $3
`

type MarkTaskCancelledParams struct {
	LastEventSequence int64              `json:"last_event_sequence"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID                string             `json:"id"`
}

func (q *Queries) MarkTaskCancelled(ctx context.Context, arg MarkTaskCancelledParams) error {
	_, err := q.db.Exec(ctx, markTaskCancelled, arg.LastEventSequence, arg.UpdatedAt, arg.ID)
	return err
}

const markTaskRunning = `-- name: MarkTaskRunning :exec
UPDATE workos_core.agent_tasks SET state = 'running', updated_at = $1 WHERE id = $2
`

type MarkTaskRunningParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

func (q *Queries) MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) error {
	_, err := q.db.Exec(ctx, markTaskRunning, arg.UpdatedAt, arg.ID)
	return err
}

const renewTaskLease = `-- name: RenewTaskLease :one
UPDATE workos_events.outbox AS o
SET locked_until = $1
FROM workos_core.agent_tasks AS t
WHERE o.lease_id = $2 AND o.locked_by = $3
  AND o.processed_at IS NULL AND o.locked_until >= $4
  AND t.id = o.aggregate_id
RETURNING t.cancellation_requested
`

type RenewTaskLeaseParams struct {
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LeaseID    pgtype.UUID        `json:"lease_id"`
	WorkerID   pgtype.Text        `json:"worker_id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
}

func (q *Queries) RenewTaskLease(ctx context.Context, arg RenewTaskLeaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, renewTaskLease,
		arg.ExpiresAt,
		arg.LeaseID,
		arg.WorkerID,
		arg.ObservedAt,
	)
	var cancellation_requested bool
	err := row.Scan(&cancellation_requested)
	return cancellation_requested, err
}

const selectTaskClaim = `-- name: SelectTaskClaim :one
SELECT o.aggregate_id
FROM workos_events.outbox AS o
JOIN workos_core.agent_tasks AS t ON t.id = o.aggregate_id
WHERE o.event_type = 'agent.task.requested.v1' AND o.processed_at IS NULL
  AND (o.locked_until IS NULL OR o.locked_until < $1)
  AND t.state IN ('queued', 'running', 'waiting')
ORDER BY o.occurred_at
FOR UPDATE OF o SKIP LOCKED
LIMIT 1
`

func (q *Queries) SelectTaskClaim(ctx context.Context, lockedUntil pgtype.Timestamptz) (string, error) {
	row := q.db.QueryRow(ctx, selectTaskClaim, lockedUntil)
	var aggregate_id string
	err := row.Scan(&aggregate_id)
	return aggregate_id, err
}

const taskBelongsToOwner = `-- name: TaskBelongsToOwner :one
SELECT EXISTS(
    SELECT 1 FROM workos_core.agent_tasks WHERE id = $1 AND owner_user_id = $2
) AS allowed
`

type TaskBelongsToOwnerParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) TaskBelongsToOwner(ctx context.Context, arg TaskBelongsToOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, taskBelongsToOwner, arg.ID, arg.OwnerUserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}
