// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package indexerdb

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// owner: indexer; bounded content-addressed archive objects (ADR-0017 §5); never indexed into search
type WorkosIndexArchiveObject struct {
	ID          string
	OwnerUserID string
	Sha256      string
	MediaType   string
	ByteCount   int64
	Bytes       []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WorkosIndexConsumerState struct {
	WorkerID            string
	CursorPublicationID pgtype.UUID
	CursorOccurredAt    *time.Time
	ObservedWatermark   string
	UpdatedAt           time.Time
}

type WorkosIndexIndexJob struct {
	ID              string
	OwnerUserID     string
	ProjectID       string
	State           string
	FailureCategory pgtype.Text
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type WorkosIndexIndexJobRequest struct {
	OwnerUserID    string
	IdempotencyKey string
	RequestDigest  string
	Result         []byte
	CreatedAt      time.Time
}

type WorkosIndexIndexJobSource struct {
	JobID          string
	ArtifactID     string
	ExpectedDigest string
	State          string
	Outcome        pgtype.Text
	UpdatedAt      time.Time
}

type WorkosIndexProjectTombstone struct {
	OwnerUserID       string
	ProjectID         string
	LastPublicationID string
	ArchivedAt        time.Time
}

type WorkosIndexProjectionGeneration struct {
	ID               string
	Scope            string
	OwnerUserID      pgtype.UUID
	ProjectID        pgtype.UUID
	Status           string
	SnapshotBoundary string
	DocumentCount    int64
	TombstoneCount   int64
	CreatedAt        time.Time
	PromotedAt       *time.Time
	RetiredAt        *time.Time
}

// owner: indexer; exactly-once local effect per (publication, generation)
type WorkosIndexPublicationReceipt struct {
	PublicationID        string
	ProjectionGeneration string
	RequestDigest        string
	Outcome              string
	SourceDigest         pgtype.Text
	ProcessedAt          time.Time
}

type WorkosIndexRebuildJob struct {
	ID                string
	Scope             string
	OwnerUserID       pgtype.UUID
	ProjectID         pgtype.UUID
	IdempotencyDigest string
	State             string
	TargetGeneration  string
	PhaseCursor       string
	SnapshotBoundary  string
	SourceCount       int64
	AppliedCount      int64
	TombstoneCount    int64
	FailureCategory   pgtype.Text
	CreatedAt         time.Time
	UpdatedAt         time.Time
	TerminalAt        *time.Time
}

type WorkosIndexRebuildJobRequest struct {
	IdempotencyKey string
	RequestDigest  string
	JobID          string
	CreatedAt      time.Time
}

// owner: indexer; owner-bound local directory mounts ingested as workspace documents (ADR-0017 §4)
type WorkosIndexWorkspaceSource struct {
	ID              string
	OwnerUserID     string
	ProjectID       string
	RootPath        string
	Status          string
	DegradedReason  string
	IndexedCount    int64
	SkippedCount    int64
	TombstonedCount int64
	LastSyncedAt    *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
