// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package indexerdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateGenerationIfEmpty = `-- name: ActivateGenerationIfEmpty :execrows
INSERT INTO workos_index.active_generation (generation_id)
SELECT $1
WHERE NOT EXISTS (SELECT 1 FROM workos_index.active_generation)
`

func (q *Queries) ActivateGenerationIfEmpty(ctx context.Context, generationID string) (int64, error) {
	result, err := q.db.Exec(ctx, activateGenerationIfEmpty, generationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activeGenerationID = `-- name: ActiveGenerationID :one

SELECT generation_id FROM workos_index.active_generation
`

// Indexer projection queries. Every statement touches only workos_index
// tables; Core schemas are reached exclusively through the private RPC
// client. Search reads only the active generation.
func (q *Queries) ActiveGenerationID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, activeGenerationID)
	var generation_id string
	err := row.Scan(&generation_id)
	return generation_id, err
}

const claimRunnableIndexJob = `-- name: ClaimRunnableIndexJob :one
UPDATE workos_index.index_jobs SET state = 'running', updated_at = $1
WHERE id IN (
    SELECT j.id FROM workos_index.index_jobs j
    WHERE j.state IN ('pending', 'running')
    ORDER BY j.created_at, j.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, owner_user_id, project_id, state, failure_category, created_at, updated_at
`

func (q *Queries) ClaimRunnableIndexJob(ctx context.Context, updatedAt time.Time) (WorkosIndexIndexJob, error) {
	row := q.db.QueryRow(ctx, claimRunnableIndexJob, updatedAt)
	var i WorkosIndexIndexJob
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.State,
		&i.FailureCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countGenerationDocuments = `-- name: CountGenerationDocuments :one
SELECT count(*) FROM workos_index.documents WHERE projection_generation = $1
`

func (q *Queries) CountGenerationDocuments(ctx context.Context, generationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGenerationDocuments, generationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIndexJobSources = `-- name: CountIndexJobSources :one
SELECT
    count(*) AS total,
    count(*) FILTER (WHERE state = 'completed') AS completed,
    count(*) FILTER (WHERE state = 'failed') AS failed
FROM workos_index.index_job_sources WHERE job_id = $1
`

type CountIndexJobSourcesRow struct {
	Total     int64
	Completed int64
	Failed    int64
}

func (q *Queries) CountIndexJobSources(ctx context.Context, jobID string) (CountIndexJobSourcesRow, error) {
	row := q.db.QueryRow(ctx, countIndexJobSources, jobID)
	var i CountIndexJobSourcesRow
	err := row.Scan(&i.Total, &i.Completed, &i.Failed)
	return i, err
}

const getBuildingGenerationForScope = `-- name: GetBuildingGenerationForScope :one
SELECT id FROM workos_index.projection_generations
WHERE status = 'building' AND scope = $1
  AND owner_user_id IS NOT DISTINCT FROM $2
  AND project_id IS NOT DISTINCT FROM $3
ORDER BY created_at DESC
LIMIT 1
`

type GetBuildingGenerationForScopeParams struct {
	Scope       string
	OwnerUserID pgtype.UUID
	ProjectID   pgtype.UUID
}

func (q *Queries) GetBuildingGenerationForScope(ctx context.Context, arg GetBuildingGenerationForScopeParams) (string, error) {
	row := q.db.QueryRow(ctx, getBuildingGenerationForScope, arg.Scope, arg.OwnerUserID, arg.ProjectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getConsumerCursor = `-- name: GetConsumerCursor :one
SELECT worker_id, cursor_publication_id, cursor_occurred_at, observed_watermark, updated_at
FROM workos_index.consumer_state
WHERE worker_id = $1
`

func (q *Queries) GetConsumerCursor(ctx context.Context, workerID string) (WorkosIndexConsumerState, error) {
	row := q.db.QueryRow(ctx, getConsumerCursor, workerID)
	var i WorkosIndexConsumerState
	err := row.Scan(
		&i.WorkerID,
		&i.CursorPublicationID,
		&i.CursorOccurredAt,
		&i.ObservedWatermark,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentStatus = `-- name: GetDocumentStatus :one
SELECT source_digest, tombstoned_at
FROM workos_index.documents
WHERE projection_generation = (SELECT generation_id FROM workos_index.active_generation)
  AND owner_user_id = $1 AND project_id = $2
  AND source_id = $3
`

type GetDocumentStatusParams struct {
	OwnerUserID string
	ProjectID   string
	SourceID    string
}

type GetDocumentStatusRow struct {
	SourceDigest string
	TombstonedAt *time.Time
}

func (q *Queries) GetDocumentStatus(ctx context.Context, arg GetDocumentStatusParams) (GetDocumentStatusRow, error) {
	row := q.db.QueryRow(ctx, getDocumentStatus, arg.OwnerUserID, arg.ProjectID, arg.SourceID)
	var i GetDocumentStatusRow
	err := row.Scan(&i.SourceDigest, &i.TombstonedAt)
	return i, err
}

const getIndexJob = `-- name: GetIndexJob :one
SELECT id, owner_user_id, project_id, state, failure_category, created_at, updated_at
FROM workos_index.index_jobs
WHERE id = $1 AND owner_user_id = $2
`

type GetIndexJobParams struct {
	ID          string
	OwnerUserID string
}

func (q *Queries) GetIndexJob(ctx context.Context, arg GetIndexJobParams) (WorkosIndexIndexJob, error) {
	row := q.db.QueryRow(ctx, getIndexJob, arg.ID, arg.OwnerUserID)
	var i WorkosIndexIndexJob
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.State,
		&i.FailureCategory,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndexJobRequest = `-- name: GetIndexJobRequest :one

SELECT owner_user_id, idempotency_key, request_digest, result, created_at
FROM workos_index.index_job_requests
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetIndexJobRequestParams struct {
	OwnerUserID    string
	IdempotencyKey string
}

// Repair/reindex jobs (IndexContext). The request mapping is the durable
// idempotency authority; job + sources + first-response snapshot commit in
// one transaction.
func (q *Queries) GetIndexJobRequest(ctx context.Context, arg GetIndexJobRequestParams) (WorkosIndexIndexJobRequest, error) {
	row := q.db.QueryRow(ctx, getIndexJobRequest, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosIndexIndexJobRequest
	err := row.Scan(
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getIndexJobSources = `-- name: GetIndexJobSources :many
SELECT job_id, artifact_id, expected_digest, state, outcome, updated_at
FROM workos_index.index_job_sources
WHERE job_id = $1
ORDER BY artifact_id
`

func (q *Queries) GetIndexJobSources(ctx context.Context, jobID string) ([]WorkosIndexIndexJobSource, error) {
	rows, err := q.db.Query(ctx, getIndexJobSources, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosIndexIndexJobSource
	for rows.Next() {
		var i WorkosIndexIndexJobSource
		if err := rows.Scan(
			&i.JobID,
			&i.ArtifactID,
			&i.ExpectedDigest,
			&i.State,
			&i.Outcome,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectTombstone = `-- name: GetProjectTombstone :one
SELECT owner_user_id, project_id, last_publication_id, archived_at
FROM workos_index.project_tombstones
WHERE owner_user_id = $1 AND project_id = $2
`

type GetProjectTombstoneParams struct {
	OwnerUserID string
	ProjectID   string
}

func (q *Queries) GetProjectTombstone(ctx context.Context, arg GetProjectTombstoneParams) (WorkosIndexProjectTombstone, error) {
	row := q.db.QueryRow(ctx, getProjectTombstone, arg.OwnerUserID, arg.ProjectID)
	var i WorkosIndexProjectTombstone
	err := row.Scan(
		&i.OwnerUserID,
		&i.ProjectID,
		&i.LastPublicationID,
		&i.ArchivedAt,
	)
	return i, err
}

const getReceipt = `-- name: GetReceipt :one
SELECT publication_id, projection_generation, request_digest, outcome, source_digest, processed_at
FROM workos_index.publication_receipts
WHERE publication_id = $1 AND projection_generation = $2
`

type GetReceiptParams struct {
	PublicationID        string
	ProjectionGeneration string
}

func (q *Queries) GetReceipt(ctx context.Context, arg GetReceiptParams) (WorkosIndexPublicationReceipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, arg.PublicationID, arg.ProjectionGeneration)
	var i WorkosIndexPublicationReceipt
	err := row.Scan(
		&i.PublicationID,
		&i.ProjectionGeneration,
		&i.RequestDigest,
		&i.Outcome,
		&i.SourceDigest,
		&i.ProcessedAt,
	)
	return i, err
}

const insertGeneration = `-- name: InsertGeneration :exec
INSERT INTO workos_index.projection_generations (id, scope, owner_user_id, project_id, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertGenerationParams struct {
	ID          string
	Scope       string
	OwnerUserID pgtype.UUID
	ProjectID   pgtype.UUID
	Status      string
	CreatedAt   time.Time
}

func (q *Queries) InsertGeneration(ctx context.Context, arg InsertGenerationParams) error {
	_, err := q.db.Exec(ctx, insertGeneration,
		arg.ID,
		arg.Scope,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertIndexJob = `-- name: InsertIndexJob :one
INSERT INTO workos_index.index_jobs (id, owner_user_id, project_id, state, created_at, updated_at)
VALUES ($1, $2, $3, 'pending', $4, $5)
RETURNING id
`

type InsertIndexJobParams struct {
	ID          string
	OwnerUserID string
	ProjectID   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) InsertIndexJob(ctx context.Context, arg InsertIndexJobParams) (string, error) {
	row := q.db.QueryRow(ctx, insertIndexJob,
		arg.ID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertIndexJobRequest = `-- name: InsertIndexJobRequest :exec
INSERT INTO workos_index.index_job_requests (owner_user_id, idempotency_key, request_digest, result, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIndexJobRequestParams struct {
	OwnerUserID    string
	IdempotencyKey string
	RequestDigest  string
	Result         []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertIndexJobRequest(ctx context.Context, arg InsertIndexJobRequestParams) error {
	_, err := q.db.Exec(ctx, insertIndexJobRequest,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}

const insertIndexJobSource = `-- name: InsertIndexJobSource :exec
INSERT INTO workos_index.index_job_sources (job_id, artifact_id, expected_digest, state, updated_at)
VALUES ($1, $2, $3, 'pending', $4)
`

type InsertIndexJobSourceParams struct {
	JobID          string
	ArtifactID     string
	ExpectedDigest string
	UpdatedAt      time.Time
}

func (q *Queries) InsertIndexJobSource(ctx context.Context, arg InsertIndexJobSourceParams) error {
	_, err := q.db.Exec(ctx, insertIndexJobSource,
		arg.JobID,
		arg.ArtifactID,
		arg.ExpectedDigest,
		arg.UpdatedAt,
	)
	return err
}

const listIndexJobSources = `-- name: ListIndexJobSources :many
SELECT job_id, artifact_id, expected_digest, state, outcome, updated_at
FROM workos_index.index_job_sources
WHERE job_id = $1
ORDER BY artifact_id
`

func (q *Queries) ListIndexJobSources(ctx context.Context, jobID string) ([]WorkosIndexIndexJobSource, error) {
	rows, err := q.db.Query(ctx, listIndexJobSources, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosIndexIndexJobSource
	for rows.Next() {
		var i WorkosIndexIndexJobSource
		if err := rows.Scan(
			&i.JobID,
			&i.ArtifactID,
			&i.ExpectedDigest,
			&i.State,
			&i.Outcome,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIndexJobFailed = `-- name: MarkIndexJobFailed :exec
UPDATE workos_index.index_jobs SET state = 'failed', failure_category = $1, updated_at = $2
WHERE id = $3 AND state = 'running'
`

type MarkIndexJobFailedParams struct {
	FailureCategory pgtype.Text
	UpdatedAt       time.Time
	ID              string
}

func (q *Queries) MarkIndexJobFailed(ctx context.Context, arg MarkIndexJobFailedParams) error {
	_, err := q.db.Exec(ctx, markIndexJobFailed, arg.FailureCategory, arg.UpdatedAt, arg.ID)
	return err
}

const promoteGeneration = `-- name: PromoteGeneration :execrows
UPDATE workos_index.active_generation
SET generation_id = $1
WHERE generation_id = (SELECT generation_id FROM workos_index.active_generation FOR UPDATE)
  AND $2 IN (SELECT generation_id FROM workos_index.active_generation)
  AND generation_id = $2
`

type PromoteGenerationParams struct {
	Target        string
	ExpectCurrent interface{}
}

func (q *Queries) PromoteGeneration(ctx context.Context, arg PromoteGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteGeneration, arg.Target, arg.ExpectCurrent)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchFreshness = `-- name: SearchFreshness :one
SELECT
    COALESCE((SELECT max(indexed_at) FROM workos_index.documents
              WHERE projection_generation = (SELECT generation_id FROM workos_index.active_generation)), 'epoch'::timestamptz)::timestamptz
    AS last_indexed_at
`

func (q *Queries) SearchFreshness(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, searchFreshness)
	var last_indexed_at time.Time
	err := row.Scan(&last_indexed_at)
	return last_indexed_at, err
}

const searchProjectDocuments = `-- name: SearchProjectDocuments :many
WITH q AS (
    SELECT websearch_to_tsquery('simple', $5) AS tsq
),
scored AS (
    SELECT d.source_id, d.source_digest, d.artifact_type, d.title, d.source_created_at, d.content,
           ((CASE WHEN d.title_tsv @@ q.tsq THEN ts_rank(d.title_tsv, q.tsq) ELSE 0.0::double precision END) * 2.0
           + (CASE WHEN d.body_tsv @@ q.tsq THEN ts_rank(d.body_tsv, q.tsq) ELSE 0.0::double precision END))::double precision AS score
    FROM workos_index.documents d, q
    WHERE d.projection_generation = $6
      AND d.owner_user_id = $7
      AND d.project_id = $8
      AND d.tombstoned_at IS NULL
      AND d.indexed_at <= $9
      AND (d.title_tsv @@ q.tsq OR d.body_tsv @@ q.tsq)
)
SELECT source_id, source_digest, artifact_type, title, source_created_at, content, score
FROM scored
WHERE score > 0
  AND (score < $1::double precision
       OR (score = $1::double precision
           AND (source_created_at < $2::timestamptz
                OR (source_created_at = $2::timestamptz
                    AND source_id < $3::text))))
ORDER BY score DESC, source_created_at DESC, source_id
LIMIT $4
`

type SearchProjectDocumentsParams struct {
	CursorScore     float64
	CursorCreatedAt time.Time
	CursorSourceID  string
	RowLimit        int32
	QueryText       string
	GenerationID    string
	OwnerUserID     string
	ProjectID       string
	SnapshotThrough time.Time
}

type SearchProjectDocumentsRow struct {
	SourceID        string
	SourceDigest    string
	ArtifactType    string
	Title           string
	SourceCreatedAt time.Time
	Content         string
	Score           float64
}

// Deterministic lexical page (ADR-0013 §5): rank over the built-in 'simple'
// tsquery, title hits weighted 2x, fixed tie-break (score DESC,
// source_created_at DESC, source_id ASC). The cursor triple uses sentinel
// values for the first page (score 1e9). The snapshot watermark excludes
// documents indexed after the chain started, so late arrivals never join an
// open page chain.
func (q *Queries) SearchProjectDocuments(ctx context.Context, arg SearchProjectDocumentsParams) ([]SearchProjectDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchProjectDocuments,
		arg.CursorScore,
		arg.CursorCreatedAt,
		arg.CursorSourceID,
		arg.RowLimit,
		arg.QueryText,
		arg.GenerationID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.SnapshotThrough,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProjectDocumentsRow
	for rows.Next() {
		var i SearchProjectDocumentsRow
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceDigest,
			&i.ArtifactType,
			&i.Title,
			&i.SourceCreatedAt,
			&i.Content,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneProjectDocuments = `-- name: TombstoneProjectDocuments :execrows
UPDATE workos_index.documents
SET tombstoned_at = $1, updated_at = $2
WHERE projection_generation = $3
  AND owner_user_id = $4 AND project_id = $5
  AND tombstoned_at IS NULL
`

type TombstoneProjectDocumentsParams struct {
	TombstonedAt         *time.Time
	UpdatedAt            time.Time
	ProjectionGeneration string
	OwnerUserID          string
	ProjectID            string
}

func (q *Queries) TombstoneProjectDocuments(ctx context.Context, arg TombstoneProjectDocumentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, tombstoneProjectDocuments,
		arg.TombstonedAt,
		arg.UpdatedAt,
		arg.ProjectionGeneration,
		arg.OwnerUserID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIndexJobSource = `-- name: UpdateIndexJobSource :exec
UPDATE workos_index.index_job_sources SET state = $1, outcome = $2, updated_at = $3
WHERE job_id = $4 AND artifact_id = $5
`

type UpdateIndexJobSourceParams struct {
	State      string
	Outcome    pgtype.Text
	UpdatedAt  time.Time
	JobID      string
	ArtifactID string
}

func (q *Queries) UpdateIndexJobSource(ctx context.Context, arg UpdateIndexJobSourceParams) error {
	_, err := q.db.Exec(ctx, updateIndexJobSource,
		arg.State,
		arg.Outcome,
		arg.UpdatedAt,
		arg.JobID,
		arg.ArtifactID,
	)
	return err
}

const updateIndexJobState = `-- name: UpdateIndexJobState :exec
UPDATE workos_index.index_jobs SET state = $1, updated_at = $2
WHERE id = $3
`

type UpdateIndexJobStateParams struct {
	State     string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateIndexJobState(ctx context.Context, arg UpdateIndexJobStateParams) error {
	_, err := q.db.Exec(ctx, updateIndexJobState, arg.State, arg.UpdatedAt, arg.ID)
	return err
}

const upsertConsumerCursor = `-- name: UpsertConsumerCursor :exec
INSERT INTO workos_index.consumer_state (worker_id, cursor_publication_id, cursor_occurred_at, observed_watermark, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (worker_id) DO UPDATE
SET cursor_publication_id = EXCLUDED.cursor_publication_id,
    cursor_occurred_at = EXCLUDED.cursor_occurred_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertConsumerCursorParams struct {
	WorkerID            string
	CursorPublicationID pgtype.UUID
	CursorOccurredAt    *time.Time
	ObservedWatermark   string
	UpdatedAt           time.Time
}

func (q *Queries) UpsertConsumerCursor(ctx context.Context, arg UpsertConsumerCursorParams) error {
	_, err := q.db.Exec(ctx, upsertConsumerCursor,
		arg.WorkerID,
		arg.CursorPublicationID,
		arg.CursorOccurredAt,
		arg.ObservedWatermark,
		arg.UpdatedAt,
	)
	return err
}

const upsertProjectTombstone = `-- name: UpsertProjectTombstone :exec
INSERT INTO workos_index.project_tombstones (owner_user_id, project_id, last_publication_id, archived_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_user_id, project_id) DO UPDATE
SET last_publication_id = EXCLUDED.last_publication_id, archived_at = EXCLUDED.archived_at
WHERE workos_index.project_tombstones.last_publication_id <= EXCLUDED.last_publication_id
`

type UpsertProjectTombstoneParams struct {
	OwnerUserID       string
	ProjectID         string
	LastPublicationID string
	ArchivedAt        time.Time
}

func (q *Queries) UpsertProjectTombstone(ctx context.Context, arg UpsertProjectTombstoneParams) error {
	_, err := q.db.Exec(ctx, upsertProjectTombstone,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.LastPublicationID,
		arg.ArchivedAt,
	)
	return err
}

const upsertReceipt = `-- name: UpsertReceipt :exec
INSERT INTO workos_index.publication_receipts (
    publication_id, projection_generation, request_digest, outcome, source_digest, processed_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
ON CONFLICT (publication_id, projection_generation) DO NOTHING
`

type UpsertReceiptParams struct {
	PublicationID        string
	ProjectionGeneration string
	RequestDigest        string
	Outcome              string
	SourceDigest         pgtype.Text
	ProcessedAt          time.Time
}

func (q *Queries) UpsertReceipt(ctx context.Context, arg UpsertReceiptParams) error {
	_, err := q.db.Exec(ctx, upsertReceipt,
		arg.PublicationID,
		arg.ProjectionGeneration,
		arg.RequestDigest,
		arg.Outcome,
		arg.SourceDigest,
		arg.ProcessedAt,
	)
	return err
}

const upsertSearchDocument = `-- name: UpsertSearchDocument :execrows
INSERT INTO workos_index.documents (
    projection_generation, owner_user_id, project_id, source_type, source_id,
    source_digest, artifact_type, title, content, source_created_at,
    last_publication_id, source_operation, indexed_at, updated_at
) VALUES (
    $1, $2, $3,
    'artifact.review.v1', $4, $5,
    $6, $7, $8,
    $9, $10,
    'review-artifact.upsert', $11, $12
)
ON CONFLICT (projection_generation, owner_user_id, project_id, source_id) DO UPDATE
SET source_digest = EXCLUDED.source_digest,
    artifact_type = EXCLUDED.artifact_type,
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    source_created_at = EXCLUDED.source_created_at,
    last_publication_id = EXCLUDED.last_publication_id,
    indexed_at = EXCLUDED.indexed_at,
    tombstoned_at = NULL,
    updated_at = EXCLUDED.updated_at
WHERE workos_index.documents.last_publication_id <= EXCLUDED.last_publication_id
   OR workos_index.documents.tombstoned_at IS NULL AND workos_index.documents.source_digest = EXCLUDED.source_digest
`

type UpsertSearchDocumentParams struct {
	ProjectionGeneration string
	OwnerUserID          string
	ProjectID            string
	SourceID             string
	SourceDigest         string
	ArtifactType         string
	Title                string
	Content              string
	SourceCreatedAt      time.Time
	LastPublicationID    string
	IndexedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) UpsertSearchDocument(ctx context.Context, arg UpsertSearchDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSearchDocument,
		arg.ProjectionGeneration,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.SourceID,
		arg.SourceDigest,
		arg.ArtifactType,
		arg.Title,
		arg.Content,
		arg.SourceCreatedAt,
		arg.LastPublicationID,
		arg.IndexedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const writableGenerationIDs = `-- name: WritableGenerationIDs :many
SELECT id FROM workos_index.projection_generations
WHERE status IN ('building', 'active')
  AND (scope = 'all' OR (scope = 'project' AND owner_user_id = $1::uuid
       AND project_id = $2::uuid))
`

type WritableGenerationIDsParams struct {
	OwnerUserID string
	ProjectID   string
}

func (q *Queries) WritableGenerationIDs(ctx context.Context, arg WritableGenerationIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, writableGenerationIDs, arg.OwnerUserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
