// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package browserpooldb

import (
	"context"
	"time"
)

type Querier interface {
	CloseBrowserSession(ctx context.Context, arg CloseBrowserSessionParams) (int64, error)
	CountActiveBrowserSessions(ctx context.Context, ownerUserID string) (int64, error)
	ExpireIdleBrowserSessions(ctx context.Context, updatedAt time.Time) ([]string, error)
	GetBrowserSession(ctx context.Context, arg GetBrowserSessionParams) (WorkosRuntimeBrowserSession, error)
	GetBrowserSessionByKey(ctx context.Context, arg GetBrowserSessionByKeyParams) (WorkosRuntimeBrowserSession, error)
	InsertBrowserSession(ctx context.Context, arg InsertBrowserSessionParams) (int64, error)
	UpdateBrowserSessionRunning(ctx context.Context, arg UpdateBrowserSessionRunningParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
