// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package browserpooldb

import (
	"context"
	"time"
)

const closeBrowserSession = `-- name: CloseBrowserSession :execrows
UPDATE workos_runtime.browser_sessions
SET state = $3, restart_count = $4, updated_at = $5, expires_at = $5
WHERE owner_user_id = $1 AND session_id = $2 AND state IN ('queued', 'running', 'restarting')
`

type CloseBrowserSessionParams struct {
	OwnerUserID  string    `json:"owner_user_id"`
	SessionID    string    `json:"session_id"`
	State        string    `json:"state"`
	RestartCount int32     `json:"restart_count"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CloseBrowserSession(ctx context.Context, arg CloseBrowserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeBrowserSession,
		arg.OwnerUserID,
		arg.SessionID,
		arg.State,
		arg.RestartCount,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveBrowserSessions = `-- name: CountActiveBrowserSessions :one
SELECT count(*) AS active
FROM workos_runtime.browser_sessions
WHERE owner_user_id = $1 AND state IN ('queued', 'running', 'restarting')
`

func (q *Queries) CountActiveBrowserSessions(ctx context.Context, ownerUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBrowserSessions, ownerUserID)
	var active int64
	err := row.Scan(&active)
	return active, err
}

const expireIdleBrowserSessions = `-- name: ExpireIdleBrowserSessions :many
UPDATE workos_runtime.browser_sessions
SET state = 'closed', updated_at = $1, expires_at = $1
WHERE state IN ('queued', 'running', 'restarting') AND expires_at < $1
RETURNING session_id::text AS session_id
`

func (q *Queries) ExpireIdleBrowserSessions(ctx context.Context, updatedAt time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, expireIdleBrowserSessions, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBrowserSession = `-- name: GetBrowserSession :one
SELECT session_id, owner_user_id, project_id, idempotency_key, request_digest,
       state, current_url, restart_count, created_at, updated_at, expires_at
FROM workos_runtime.browser_sessions
WHERE owner_user_id = $1 AND session_id = $2
`

type GetBrowserSessionParams struct {
	OwnerUserID string `json:"owner_user_id"`
	SessionID   string `json:"session_id"`
}

func (q *Queries) GetBrowserSession(ctx context.Context, arg GetBrowserSessionParams) (WorkosRuntimeBrowserSession, error) {
	row := q.db.QueryRow(ctx, getBrowserSession, arg.OwnerUserID, arg.SessionID)
	var i WorkosRuntimeBrowserSession
	err := row.Scan(
		&i.SessionID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.State,
		&i.CurrentUrl,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getBrowserSessionByKey = `-- name: GetBrowserSessionByKey :one
SELECT session_id, owner_user_id, project_id, idempotency_key, request_digest,
       state, current_url, restart_count, created_at, updated_at, expires_at
FROM workos_runtime.browser_sessions
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetBrowserSessionByKeyParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetBrowserSessionByKey(ctx context.Context, arg GetBrowserSessionByKeyParams) (WorkosRuntimeBrowserSession, error) {
	row := q.db.QueryRow(ctx, getBrowserSessionByKey, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosRuntimeBrowserSession
	err := row.Scan(
		&i.SessionID,
		&i.OwnerUserID,
		&i.ProjectID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.State,
		&i.CurrentUrl,
		&i.RestartCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertBrowserSession = `-- name: InsertBrowserSession :execrows
INSERT INTO workos_runtime.browser_sessions (
    session_id, owner_user_id, project_id, idempotency_key, request_digest,
    state, current_url, restart_count, created_at, updated_at, expires_at
) VALUES ($1, $2, $3, $4, $5, 'queued', $6, 0, $7, $7, $8)
ON CONFLICT (owner_user_id, idempotency_key) DO NOTHING
`

type InsertBrowserSessionParams struct {
	SessionID      string    `json:"session_id"`
	OwnerUserID    string    `json:"owner_user_id"`
	ProjectID      string    `json:"project_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	RequestDigest  string    `json:"request_digest"`
	CurrentUrl     string    `json:"current_url"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) InsertBrowserSession(ctx context.Context, arg InsertBrowserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBrowserSession,
		arg.SessionID,
		arg.OwnerUserID,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.CurrentUrl,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBrowserSessionRunning = `-- name: UpdateBrowserSessionRunning :execrows
UPDATE workos_runtime.browser_sessions
SET state = $3, current_url = $4, restart_count = $5, updated_at = $6
WHERE owner_user_id = $1 AND session_id = $2 AND state IN ('queued', 'running', 'restarting')
`

type UpdateBrowserSessionRunningParams struct {
	OwnerUserID  string    `json:"owner_user_id"`
	SessionID    string    `json:"session_id"`
	State        string    `json:"state"`
	CurrentUrl   string    `json:"current_url"`
	RestartCount int32     `json:"restart_count"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) UpdateBrowserSessionRunning(ctx context.Context, arg UpdateBrowserSessionRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBrowserSessionRunning,
		arg.OwnerUserID,
		arg.SessionID,
		arg.State,
		arg.CurrentUrl,
		arg.RestartCount,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
