// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package projectdb

import (
	"context"
)

type Querier interface {
	ActiveInstallationAppIDs(ctx context.Context, projectID string) ([]string, error)
	ApplyInstallationProjection(ctx context.Context, arg ApplyInstallationProjectionParams) (ApplyInstallationProjectionRow, error)
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (WorkosCoreProject, error)
	GetActiveInstallationByApp(ctx context.Context, arg GetActiveInstallationByAppParams) (GetActiveInstallationByAppRow, error)
	GetCreateRequest(ctx context.Context, arg GetCreateRequestParams) (WorkosCoreProjectCreateRequest, error)
	GetInstallationById(ctx context.Context, arg GetInstallationByIdParams) (GetInstallationByIdRow, error)
	GetInstallationRequest(ctx context.Context, arg GetInstallationRequestParams) (GetInstallationRequestRow, error)
	GetProject(ctx context.Context, arg GetProjectParams) (WorkosCoreProject, error)
	GetProjectByIdempotency(ctx context.Context, arg GetProjectByIdempotencyParams) (WorkosCoreProject, error)
	InsertCreateRequest(ctx context.Context, arg InsertCreateRequestParams) (int64, error)
	InsertInstallation(ctx context.Context, arg InsertInstallationParams) error
	InsertInstallationRequest(ctx context.Context, arg InsertInstallationRequestParams) (int64, error)
	InsertInstallationVersion(ctx context.Context, arg InsertInstallationVersionParams) error
	InsertProject(ctx context.Context, arg InsertProjectParams) (int64, error)
	InsertProjectEvent(ctx context.Context, arg InsertProjectEventParams) error
	InsertProjectOutbox(ctx context.Context, arg InsertProjectOutboxParams) error
	ListActiveInstallations(ctx context.Context, arg ListActiveInstallationsParams) ([]ListActiveInstallationsRow, error)
	ListInstallationVersionsAsc(ctx context.Context, installationID string) ([]WorkosCoreProjectAppInstallationVersion, error)
	ListInstallationVersionsPage(ctx context.Context, arg ListInstallationVersionsPageParams) ([]WorkosCoreProjectAppInstallationVersion, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]WorkosCoreProject, error)
	LockProjectForInstallation(ctx context.Context, arg LockProjectForInstallationParams) (LockProjectForInstallationRow, error)
	NextInstallationVersionSequence(ctx context.Context, installationID string) (int32, error)
	// Index-feed reconciliation page (ADR-0013): archived project scopes in
	// stable (archived_at, id) order. Only this module's own table is read.
	ReconcileArchivedProjects(ctx context.Context, arg ReconcileArchivedProjectsParams) ([]ReconcileArchivedProjectsRow, error)
	ResolveActiveInstallation(ctx context.Context, arg ResolveActiveInstallationParams) (ResolveActiveInstallationRow, error)
	SetInstallationGrants(ctx context.Context, arg SetInstallationGrantsParams) (SetInstallationGrantsRow, error)
	TombstoneInstallation(ctx context.Context, arg TombstoneInstallationParams) (int64, error)
	TrimInstallationVersions(ctx context.Context, arg TrimInstallationVersionsParams) error
	UpdateInstallationVersion(ctx context.Context, arg UpdateInstallationVersionParams) (int64, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (WorkosCoreProject, error)
}

var _ Querier = (*Queries)(nil)
