// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package projectdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :one
UPDATE workos_core.projects
SET archived_at = $1, updated_at = $1, revision = revision + 1
WHERE id = $2 AND owner_user_id = $3
  AND revision = $4 AND archived_at IS NULL
RETURNING id, owner_user_id, idempotency_key, name, icon, workspace_refs, harness_binding,
          installed_app_ids, default_agent_role, knowledge_collection_id, artifact_collection_id,
          revision, created_at, updated_at, archived_at
`

type ArchiveProjectParams struct {
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
	ID               string             `json:"id"`
	OwnerUserID      string             `json:"owner_user_id"`
	ExpectedRevision int64              `json:"expected_revision"`
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (WorkosCoreProject, error) {
	row := q.db.QueryRow(ctx, archiveProject,
		arg.ArchivedAt,
		arg.ID,
		arg.OwnerUserID,
		arg.ExpectedRevision,
	)
	var i WorkosCoreProject
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.Name,
		&i.Icon,
		&i.WorkspaceRefs,
		&i.HarnessBinding,
		&i.InstalledAppIds,
		&i.DefaultAgentRole,
		&i.KnowledgeCollectionID,
		&i.ArtifactCollectionID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, owner_user_id, idempotency_key, name, icon, workspace_refs, harness_binding,
       installed_app_ids, default_agent_role, knowledge_collection_id, artifact_collection_id,
       revision, created_at, updated_at, archived_at
FROM workos_core.projects
WHERE owner_user_id = $1 AND id = $2
`

type GetProjectParams struct {
	OwnerUserID string `json:"owner_user_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (WorkosCoreProject, error) {
	row := q.db.QueryRow(ctx, getProject, arg.OwnerUserID, arg.ID)
	var i WorkosCoreProject
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.Name,
		&i.Icon,
		&i.WorkspaceRefs,
		&i.HarnessBinding,
		&i.InstalledAppIds,
		&i.DefaultAgentRole,
		&i.KnowledgeCollectionID,
		&i.ArtifactCollectionID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getProjectByIdempotency = `-- name: GetProjectByIdempotency :one
SELECT id, owner_user_id, idempotency_key, name, icon, workspace_refs, harness_binding,
       installed_app_ids, default_agent_role, knowledge_collection_id, artifact_collection_id,
       revision, created_at, updated_at, archived_at
FROM workos_core.projects
WHERE owner_user_id = $1 AND idempotency_key = $2
`

type GetProjectByIdempotencyParams struct {
	OwnerUserID    string `json:"owner_user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetProjectByIdempotency(ctx context.Context, arg GetProjectByIdempotencyParams) (WorkosCoreProject, error) {
	row := q.db.QueryRow(ctx, getProjectByIdempotency, arg.OwnerUserID, arg.IdempotencyKey)
	var i WorkosCoreProject
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.Name,
		&i.Icon,
		&i.WorkspaceRefs,
		&i.HarnessBinding,
		&i.InstalledAppIds,
		&i.DefaultAgentRole,
		&i.KnowledgeCollectionID,
		&i.ArtifactCollectionID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :execrows
INSERT INTO workos_core.projects (
    id, owner_user_id, idempotency_key, name, icon, workspace_refs, harness_binding,
    installed_app_ids, default_agent_role, knowledge_collection_id, artifact_collection_id,
    revision, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (owner_user_id, idempotency_key) DO NOTHING
`

type InsertProjectParams struct {
	ID                    string             `json:"id"`
	OwnerUserID           string             `json:"owner_user_id"`
	IdempotencyKey        string             `json:"idempotency_key"`
	Name                  string             `json:"name"`
	Icon                  string             `json:"icon"`
	WorkspaceRefs         json.RawMessage    `json:"workspace_refs"`
	HarnessBinding        []byte             `json:"harness_binding"`
	InstalledAppIds       []string           `json:"installed_app_ids"`
	DefaultAgentRole      string             `json:"default_agent_role"`
	KnowledgeCollectionID string             `json:"knowledge_collection_id"`
	ArtifactCollectionID  string             `json:"artifact_collection_id"`
	Revision              int64              `json:"revision"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertProject,
		arg.ID,
		arg.OwnerUserID,
		arg.IdempotencyKey,
		arg.Name,
		arg.Icon,
		arg.WorkspaceRefs,
		arg.HarnessBinding,
		arg.InstalledAppIds,
		arg.DefaultAgentRole,
		arg.KnowledgeCollectionID,
		arg.ArtifactCollectionID,
		arg.Revision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProjectEvent = `-- name: InsertProjectEvent :exec
INSERT INTO workos_events.events (
    id, stream_type, stream_id, sequence, event_type, payload, occurred_at
) VALUES ($1, 'project', $2, $3, $4, $5, $6)
`

type InsertProjectEventParams struct {
	ID         string             `json:"id"`
	StreamID   string             `json:"stream_id"`
	Sequence   int64              `json:"sequence"`
	EventType  string             `json:"event_type"`
	Payload    json.RawMessage    `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertProjectEvent(ctx context.Context, arg InsertProjectEventParams) error {
	_, err := q.db.Exec(ctx, insertProjectEvent,
		arg.ID,
		arg.StreamID,
		arg.Sequence,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertProjectOutbox = `-- name: InsertProjectOutbox :exec
INSERT INTO workos_events.outbox (
    id, aggregate_type, aggregate_id, event_type, payload, occurred_at
) VALUES ($1, 'project', $2, $3, $4, $5)
`

type InsertProjectOutboxParams struct {
	ID          string             `json:"id"`
	AggregateID string             `json:"aggregate_id"`
	EventType   string             `json:"event_type"`
	Payload     json.RawMessage    `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertProjectOutbox(ctx context.Context, arg InsertProjectOutboxParams) error {
	_, err := q.db.Exec(ctx, insertProjectOutbox,
		arg.ID,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, owner_user_id, idempotency_key, name, icon, workspace_refs, harness_binding,
       installed_app_ids, default_agent_role, knowledge_collection_id, artifact_collection_id,
       revision, created_at, updated_at, archived_at
FROM workos_core.projects
WHERE owner_user_id = $1
  AND id > $2
  AND ($3::boolean OR archived_at IS NULL)
ORDER BY id
LIMIT $4
`

type ListProjectsParams struct {
	OwnerUserID     string `json:"owner_user_id"`
	Cursor          string `json:"cursor"`
	IncludeArchived bool   `json:"include_archived"`
	RowLimit        int32  `json:"row_limit"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]WorkosCoreProject, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.OwnerUserID,
		arg.Cursor,
		arg.IncludeArchived,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkosCoreProject
	for rows.Next() {
		var i WorkosCoreProject
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.IdempotencyKey,
			&i.Name,
			&i.Icon,
			&i.WorkspaceRefs,
			&i.HarnessBinding,
			&i.InstalledAppIds,
			&i.DefaultAgentRole,
			&i.KnowledgeCollectionID,
			&i.ArtifactCollectionID,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE workos_core.projects
SET name = $1, icon = $2, workspace_refs = $3,
    harness_binding = $4, revision = revision + 1,
    updated_at = $5
WHERE id = $6 AND owner_user_id = $7
  AND revision = $8 AND archived_at IS NULL
RETURNING id, owner_user_id, idempotency_key, name, icon, workspace_refs, harness_binding,
          installed_app_ids, default_agent_role, knowledge_collection_id, artifact_collection_id,
          revision, created_at, updated_at, archived_at
`

type UpdateProjectParams struct {
	Name             string             `json:"name"`
	Icon             string             `json:"icon"`
	WorkspaceRefs    json.RawMessage    `json:"workspace_refs"`
	HarnessBinding   []byte             `json:"harness_binding"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ID               string             `json:"id"`
	OwnerUserID      string             `json:"owner_user_id"`
	ExpectedRevision int64              `json:"expected_revision"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (WorkosCoreProject, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Icon,
		arg.WorkspaceRefs,
		arg.HarnessBinding,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerUserID,
		arg.ExpectedRevision,
	)
	var i WorkosCoreProject
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.IdempotencyKey,
		&i.Name,
		&i.Icon,
		&i.WorkspaceRefs,
		&i.HarnessBinding,
		&i.InstalledAppIds,
		&i.DefaultAgentRole,
		&i.KnowledgeCollectionID,
		&i.ArtifactCollectionID,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
